import styles from "./CodeWindowMockup.module.css";

// purely decorative mock-up of a generated pipeline file, shown in the
// hero section to visually back up the "generate YAML" pitch
function CodeWindowMockup() {
    return (
        <div className={styles.window}>
            <div className={styles.titleBar}>
                <div className={styles.dots}>
                    <span className={`${styles.dot} ${styles.red}`} />
                    <span className={`${styles.dot} ${styles.yellow}`} />
                    <span className={`${styles.dot} ${styles.green}`} />
                </div>
                <span className={styles.fileName}>YAML Wizard — pipeline.yml</span>
                <span className={styles.spacer} />
            </div>

            <pre className={styles.code}>
                <span className={styles.comment}>{"# ✦ Auto-generated by YAML Wizard"}</span>{"\n"}
                <span className={styles.key}>name</span>{": "}<span className={styles.string}>Production Deploy</span>{"\n\n"}
                <span className={styles.key}>on</span>{":"}{"\n"}
                {"  "}<span className={styles.key}>push</span>{":"}{"\n"}
                {"    "}<span className={styles.key}>branches</span>{": [ "}<span className={styles.string}>main</span>{" ]"}{"\n\n"}
                <span className={styles.key}>jobs</span>{":"}{"\n"}
                {"  "}<span className={styles.key}>build</span>{":"}{"\n"}
                {"    "}<span className={styles.key}>runs-on</span>{": "}<span className={styles.string}>ubuntu-latest</span>{"\n"}
                {"    "}<span className={styles.key}>steps</span>{":"}{"\n"}
                {"      "}{"- "}<span className={styles.key}>uses</span>{": "}<span className={styles.string}>actions/checkout@v4</span>{"\n"}
                {"      "}{"- "}<span className={styles.key}>run</span>{": "}<span className={styles.string}>{"npm ci && npm test"}</span>
            </pre>
        </div>
    );
}

export default CodeWindowMockup;
