import base64
import time
import httpx
from urllib.parse import urlparse, quote
from schemas.publish_yaml_schema import PublishResult
import uuid

_RETRYABLE_STATUS_CODES = {500, 502, 503, 504}
_MAX_RETRIES = 3
_BACKOFF_BASE = 2  # seconds



def publish_to_repo_tool(yaml_content: str, repo_url: str, platform: str, token: str, commit_message: str,file_path: str | None = None,
    branch: str = "main" , create_pr: bool = True, pr_branch: str | None = None,) -> PublishResult:

    platform = platform.lower()

    if pr_branch is None and create_pr:
        pr_branch = f"{branch}-yaml-wizard-{uuid.uuid4().hex[:8]}"

    if platform == "github":
        return _publish_github(
            yaml_content, repo_url, token, file_path, branch,
            commit_message, create_pr, pr_branch,)
    
    elif platform == "gitlab":
        return _publish_gitlab(
            yaml_content, repo_url, token, file_path, branch,
            commit_message, create_pr, pr_branch,)
    else:
        return PublishResult(success=False, message=f"Unknown platform: {platform}")



def _request_with_retry(method: str, url: str, **kwargs) -> httpx.Response:

    """Make an HTTP request with automatic retry on transient server errors."""

    last_exc: httpx.HTTPStatusError | None = None
    for attempt in range(_MAX_RETRIES + 1):
        resp = httpx.request(method, url, **kwargs)
        if resp.status_code not in _RETRYABLE_STATUS_CODES:
            resp.raise_for_status()
            return resp
        # Retryable error
        if attempt < _MAX_RETRIES:
            wait = _BACKOFF_BASE ** attempt  # 1s, 2s, 4s
            time.sleep(wait)
        else:
            resp.raise_for_status()  # raise on final attempt
    raise httpx.HTTPError(f"Request failed after {_MAX_RETRIES + 1} attempts")


# ── GITHUB ──────────────────────────────────────────────────────────────────


def _publish_github(yaml_content: str,repo_url: str,token: str,file_path: str | None,
    branch: str,commit_message: str | None,create_pr: bool,pr_branch: str,) -> PublishResult:
    
    """Publish YAML to a GitHub repository via the Contents API."""
    """directly to a branch or via pull request"""

    owner, repo = _parse_github_repo(repo_url)
    api_base = "https://api.github.com"
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    if file_path is None:
        file_path = ".github/workflows/ci.yml"


    target_branch = pr_branch if create_pr else branch

    try:
        # If creating a PR, first create the branch from the base
        if create_pr:
            _github_create_branch(api_base, headers, owner, repo, branch, pr_branch)

        # Check if file already exists (to get its SHA for updates)
        existing_sha = _github_get_file_sha(
            api_base, headers, owner, repo, file_path, target_branch,
        )

        # Create or update the file
        content_b64 = base64.b64encode(yaml_content.encode()).decode()
        payload: dict = {
            "message": commit_message,
            "content": content_b64,
            "branch": target_branch,
        }
        if existing_sha:
            payload["sha"] = existing_sha

        resp = _request_with_retry(
            "PUT",
            f"{api_base}/repos/{owner}/{repo}/contents/{file_path}",
            json=payload,
            headers=headers,
            timeout=30.0,
        )
        file_url = resp.json().get("content", {}).get("html_url", "")

        # Create PR if requested
        if create_pr:
            pr_result = _github_create_pr(
                api_base, headers, owner, repo,
                head=pr_branch, base=branch,
                title=f"ci: add CI/CD pipeline via YAML Wizard",
                body=(
                    f"This PR adds a CI/CD pipeline generated by YAML Wizard.\n\n"
                    f"**File:** `{file_path}`\n\n"
                    f"Please review the workflow before merging."
                ),
            )
            return PublishResult(
                success=True,
                message=f"Pull request created: {pr_result}",
                url=pr_result,
            )

        return PublishResult(
            success=True,
            message=f"File committed to {target_branch}: {file_path}",
            url=file_url,
        )
    
    except httpx.HTTPStatusError as e:
        error_body = e.response.text

        status = e.response.status_code
        if status == 401:
            return PublishResult(success=False, message="Authentication failed — check your token")
        elif status == 403:
            return PublishResult(success=False, message="Permission denied — missing required scopes")
        elif status == 404:
            return PublishResult(success=False, message=f"Repository not found: {owner}/{repo}")
        elif status == 409:
            return PublishResult(success=False, message=f"Conflict — file may have changed. {error_body}")
        elif status == 422:
            return PublishResult(success=False, message=f"Validation error: {error_body}")
        elif status == 500:
            return PublishResult(success=False, message="GitHub server error (500)")
        elif status in (502, 503, 504):
            return PublishResult(success=False, message=f"GitHub unavailable ({status}) — retry later")
        else:
            return PublishResult(success=False, message=f"HTTP error {status}: {error_body}")

    except httpx.RequestError as e:
        # Covers network issues (DNS, timeout, connection refused, etc.)
        return PublishResult(success=False, message=f"Network error: {str(e)}")

    except ValueError as e:
        return PublishResult(success=False, message=str(e))
    



def _parse_github_repo(repo_url: str) -> tuple[str, str]:

    """Extract owner/repo from a GitHub URL."""

    parsed = urlparse(repo_url)
    path = parsed.path.strip("/")
    if path.endswith(".git"):
        path = path[:-4]
    parts = path.split("/")
    if len(parts) >= 2:
        return parts[0], parts[1]
    raise ValueError(f"Cannot parse GitHub repo from URL: {repo_url}")



def _github_create_branch(
    api_base: str, headers: dict, owner: str, repo: str,
    source_branch: str, new_branch: str,) -> None:
    
    """Create a new branch from a source branch."""

    # Get the SHA of the source branch
    resp = httpx.get(
        f"{api_base}/repos/{owner}/{repo}/git/ref/heads/{source_branch}",
        headers=headers,
        timeout=15.0,
    )
    resp.raise_for_status()
    sha = resp.json()["object"]["sha"]

    # Create the new branch
    resp = _request_with_retry(
        "POST",
        f"{api_base}/repos/{owner}/{repo}/git/refs",
        json={"ref": f"refs/heads/{new_branch}", "sha": sha},
        headers=headers,
        timeout=15.0,
    )
    # 422 = branch already exists, which is fine
    if resp.status_code not in (201, 422):
        resp.raise_for_status()


def _github_get_file_sha(
    api_base: str, headers: dict, owner: str, repo: str, path: str, branch: str,) -> str | None:

    """Get the SHA of an existing file (needed for updates)."""

    try:
        resp = httpx.get(
            f"{api_base}/repos/{owner}/{repo}/contents/{path}",
            params={"ref": branch},
            headers=headers,
            timeout=15.0,
        )
        if resp.status_code == 200:
            return resp.json().get("sha")
    except httpx.HTTPError:
        pass
    return None


def _github_create_pr(
    api_base: str, headers: dict, owner: str, repo: str,
    head: str, base: str, title: str, body: str,) -> str:

    """Create a pull request and return its URL."""

    resp = _request_with_retry(
        "POST",
        f"{api_base}/repos/{owner}/{repo}/pulls",
        json={"title": title, "body": body, "head": head, "base": base},
        headers=headers,
        timeout=15.0,
    )
    return resp.json().get("html_url", "")




# ── GITLAB ──────────────────────────────────────────────────────────────────


def _publish_gitlab(
    yaml_content: str,
    repo_url: str,
    token: str,
    file_path: str | None,
    branch: str,
    commit_message: str,
    create_pr: bool,
    pr_branch: str,) -> PublishResult:

    """Publish YAML to a GitLab repository via the Repository Files API."""
    """directly to a branch or via merge request"""

    parsed = urlparse(repo_url)
    #https://gitlab.com/group/project
    #becomes: scheme: https + hostname: gitlab.com + path: /group/project
    #GitLab has multiple hosts so we extract it from repos, companies can have diff host than the public one
    gitlab_host = f"{parsed.scheme}://{parsed.hostname}"
    
    project_id = _parse_gitlab_project(repo_url)
    api_base = f"{gitlab_host}/api/v4" #GitLab API version 4 is the standard REST API base.
    headers = {"Authorization": f"Bearer {token}"}
    
    if file_path is None:
        file_path = ".gitlab-ci.yml"

    target_branch = pr_branch if create_pr else branch

    try:
        # Create branch if making merge request
        if create_pr:
            httpx.post(
                f"{api_base}/projects/{project_id}/repository/branches",
                params={"branch": pr_branch, "ref": branch},
                headers=headers,
                timeout=15.0,
            )
        print(" before FILE EXISTS:")


        # Check if file exists
        file_exists = _gitlab_file_exists(api_base, headers, project_id, file_path, target_branch)
        print("FILE EXISTS:", file_exists)
        # Create or update file
        encoded_path = file_path.replace("/", "%2F")
        payload = {
            "branch": target_branch,
            "content": yaml_content,
            "commit_message": commit_message,
        }

        if file_exists:
            resp = httpx.put(
                f"{api_base}/projects/{project_id}/repository/files/{encoded_path}",
                json=payload,
                headers=headers,
                timeout=30.0,
            )
        else:
            resp = httpx.post(
                f"{api_base}/projects/{project_id}/repository/files/{encoded_path}",
                json=payload,
                headers=headers,
                timeout=30.0,
            )
        resp.raise_for_status()

        # Create merge request if requested
        if create_pr:
            mr_resp = httpx.post(
                f"{api_base}/projects/{project_id}/merge_requests",
                json={
                    "source_branch": pr_branch,
                    "target_branch": branch,
                    "title": "ci: add CI/CD pipeline via YAML Wizard",
                    "description": (
                        f"This MR adds a CI/CD pipeline generated by YAML Wizard.\n\n"
                        f"**File:** `{file_path}`\n\n"
                        f"Please review the pipeline before merging."
                    ),
                },
                headers=headers,
                timeout=15.0,
            )
            mr_resp.raise_for_status()
            mr_url = mr_resp.json().get("web_url", "")
            return PublishResult(
                success=True,
                message=f"Merge request created: {mr_url}",
                url=mr_url,
            )

        file_url = f"{gitlab_host}/{repo_url.split(gitlab_host)[-1].strip('/')}/blob/{target_branch}/{file_path}"
        return PublishResult(
            success=True,
            message=f"File committed to {target_branch}: {file_path}",
            url=file_url,
        )
    except httpx.HTTPStatusError as e:
        status = e.response.status_code

        if status == 401:
            return PublishResult(success=False, message="Authentication failed — check your token")
        elif status == 403:
            return PublishResult(success=False, message="Permission denied — token may lack write access")
        elif status == 404:
            return PublishResult(success=False, message="Repository not found")
        elif status == 409:
            return PublishResult(success=False, message="Conflict — resource already exists or was modified")
        elif status == 422:
            return PublishResult(success=False, message="Validation error — check request payload")
        elif status == 429:
            return PublishResult(success=False, message="Rate limit exceeded — try again later")
        elif status >= 500:
            return PublishResult(success=False, message="GitLab server error — try again later")

        return PublishResult(
            success=False,
            message=f"GitLab API error (HTTP {status})"
        )
    except httpx.HTTPError as e:
        return PublishResult(
            success=False,
            message="Network error while contacting GitLab"
        )
    except ValueError as e:
        return PublishResult(success=False, message=str(e))



def _gitlab_file_exists(api_base: str, headers: dict, project_id: str, path: str, branch: str) -> bool:
    encoded_path = quote(path, safe="") #encodes ALL unsafe URL characters, not just /, whitespaces, # 

    url = f"{api_base}/projects/{project_id}/repository/files/{encoded_path}"

    resp = httpx.get(
        url,
        params={"ref": branch},
        headers=headers,
        timeout=15.0,
    )

    print("FILE CHECK:", resp.status_code, resp.text)

    if resp.status_code == 200:
        return True
    if resp.status_code == 404:
        return False
    raise Exception(f"GitLab file check failed: {resp.status_code} - {resp.text}")
    
def _parse_gitlab_project(repo_url: str) -> str:

    """Extract URL-encoded project path from a GitLab URL."""

    # GitLab API does NOT use raw paths like:group/project
    # It requires URL-encoded project path:(group%2Fproject)<- our output

    parsed = urlparse(repo_url)
    path = parsed.path.strip("/")
    if path.endswith(".git"):
        path = path[:-4]
    return path.replace("/", "%2F")