import gStyles from "../../global.module.css"
import styles from './HistoryBar.module.css'
import type { Pipeline } from "../../types";
import { useEffect, useMemo, useRef, useState } from "react";

import { FiFilter } from "react-icons/fi";
import { IoClose } from "react-icons/io5";

import { HiOutlineDownload, HiOutlineUpload } from "react-icons/hi";
import { MdDeleteOutline } from "react-icons/md";
import { CgSync } from "react-icons/cg";

type HBProps = {
    pipelines: Pipeline[],
    pipeline: Pipeline | null,
    setPipeline: React.Dispatch<React.SetStateAction<Pipeline | null>>,

}
function HistoryBar({ pipelines, pipeline, setPipeline }: HBProps){
    const [isHover, setIsHover] = useState<boolean>(false);
    const [hoverPipeline, setHoverPipeline] = useState<Pipeline | null>(null);
    
    const [query, setQuery] = useState<string>("");
    const [openFilterMenu, setOpenFilterMenu] = useState<boolean>(false);
    const [filterGenerated, setFilterGenerated] = useState<boolean | null>(null);
    const [filterActive, setFilterActive] = useState<boolean | null>(null);
    const [filterAuthor, setFilterAuthor] = useState<string[]>([]);
    const [filterBranch, setFilterBranch] = useState<string[]>([]);

    const filterRef = useRef<HTMLDivElement | null>(null);
    
    const authors = useMemo(()=>{
        return[...new Set(pipelines.map(p => p.author))].sort();
    }, [pipelines]);
    const branches  = useMemo(()=>{
        return[...new Set(pipelines.map(p => p.branch))].sort();
    }, [pipelines]);

    // filter pipelines by query and selected fields
    const filteredPipelines = useMemo(() => {
        return pipelines ? pipelines
            .filter(p => (
                p.name.toLowerCase().includes(query.toLowerCase()) &&
                (filterGenerated === null || p.is_generated_by_wizard === filterGenerated) &&
                (filterActive === null || p.is_active === filterActive) &&
                (filterBranch.length === 0 || filterBranch.includes(p.branch)) &&
                (filterAuthor.length === 0 || filterAuthor.includes(p.author))
            ))
            .sort((a,b) => new Date(b.updated_at).getTime() - new Date(a.updated_at).getTime()) : [];
    }, [pipelines, query, filterGenerated, filterActive, filterAuthor, filterBranch]);

    // Close filter menu on outside click
    useEffect(
        () => {
            function handleClickOutside(e: MouseEvent) {
                if (filterRef.current &&
                    !filterRef.current.contains(e.target as Node)) {
                    setOpenFilterMenu(false);
                }
            }

            document.addEventListener("mousedown", handleClickOutside);
            return () => {
                document.removeEventListener("mousedown", handleClickOutside);
            };
        }
    , []);

    //download file by content
    const downloadYaml=(pipeline: Pipeline)=>{
        const yaml=pipeline?.content;
        const blob=new Blob([yaml],{type:"text/yaml"});
        const url=URL.createObjectURL(blob);
        const a=document.createElement("a");
        a.href=url;
        a.download=pipeline.name + ".yml";
        a.click();
        URL.revokeObjectURL(url);
    };


    return(
        <div className={styles.historyBar}>
            <div className={styles.topContainer}>
                <p className={styles.header}>Version History</p>
                <button className={`${styles.syncBtn} ${gStyles.clickable}`}
                    title="Sync"><CgSync/></button>
            </div>
            <div className={styles.searchContainer}>
                <input type="text" className={styles.searchBar} name="searchBar" value={query}
                    placeholder="Search..." onChange={(e) => setQuery(e.target.value)}/>
                <IoClose onClick={() => setQuery("")} className={`${styles.deleteTextIcon} ${gStyles.clickable}`}/>

                <div className={styles.filterContainer} ref={filterRef}>
                    <FiFilter className={`${styles.filterIcon} ${gStyles.clickable}`} title="Filter"
                        onClick={() => setOpenFilterMenu(prev => !prev)} />

                    {openFilterMenu && (
                    <div className={styles.filterMenu}>
                        <span className={styles.filterHeader}>Source</span>
                        <div className={styles.options}>
                            <span title="Generated By YAMLWizard" className={`${styles.option} ${gStyles.clickable}
                                ${filterGenerated === true? styles.selected : `${styles.notSelected}`}`} 
                                onClick={() => {
                                    filterGenerated? setFilterGenerated(null) : setFilterGenerated(true)
                                }}>
                                YAMLWizard</span>
                            <span className={`${styles.option} ${gStyles.clickable} 
                                ${filterGenerated === false? styles.selected : `${styles.notSelected}`}`}
                                title="Fetched From Repo"
                                onClick={() => {
                                    (filterGenerated === false)? setFilterGenerated(null) : setFilterGenerated(false)
                                }}>
                                Repo</span>
                        </div>

                        <div className={styles.divider} />

                        <span className={styles.filterHeader}>Status</span> 
                        <div className={styles.options}>
                            <span className={`${styles.option} ${gStyles.clickable}
                                ${filterActive? styles.selected : `${styles.notSelected}`}`}
                                onClick={() => {
                                    filterActive ? setFilterActive(null) : setFilterActive(true)
                                }}>
                                Active</span>
                            <span className={`${styles.option} ${gStyles.clickable}
                                ${filterActive === false? styles.selected : `${styles.notSelected}`}`}
                                onClick={() => {
                                    (filterActive === false) ? setFilterActive(null) : setFilterActive(false)
                                }}>
                                Inactive</span>
                        </div>

                        <div className={styles.divider} />

                        <div className={styles.filterHeader}>
                            <span>Branch</span>
                            <IoClose onClick={() => setFilterBranch([])} title="Remove All"
                                className={`${styles.removeFilter} ${gStyles.clickable}`}/>
                        </div>
                        <div className={styles.options}>
                            {branches.map(branch => (
                                <span key={branch} className={`${styles.option} ${gStyles.clickable}
                                    ${filterBranch.find(b => branch === b) ? styles.selected: `${styles.notSelected}`}`}
                                    onClick={() => {
                                        const foundBranch = filterBranch.includes(branch);
                                        foundBranch ? setFilterBranch(filterBranch.filter(b=>b != branch))
                                        : setFilterBranch([...filterBranch, branch])
                                    }}>
                                    {branch}</span>
                            ))}
                        </div>

                        <div className={styles.divider} />

                        <div className={styles.filterHeader}>
                            <span>Author</span> 
                            <IoClose onClick={() => setFilterAuthor([])} title="Remove All"
                                className={`${styles.removeFilter} ${gStyles.clickable}`}/>
                        </div>
                        <div className={styles.options}>
                            {authors.map(author => (
                                <span key={author} className={`${styles.option} ${gStyles.clickable}
                                    ${filterAuthor.find(a => author === a) ? styles.selected : `${styles.notSelected}`}`}
                                    onClick={() => {
                                        const foundAuthor = filterAuthor.includes(author);
                                        foundAuthor? setFilterAuthor(filterAuthor.filter(a=>a != author))
                                        : setFilterAuthor([...filterAuthor, author])
                                    }}>
                                    {author}</span>
                            ))}
                        </div>
                    </div>
                )}
                </div>
            </div>
            {filteredPipelines.length > 0 ? <>
            <div className={styles.namesContainer}>
                {filteredPipelines.map((p, index) => {
                    return(
                    <div key={index} className={`${styles.pipelineTab} 
                        ${(p.id === pipeline?.id)? styles.active : gStyles.clickable}`}
                        onPointerOver={()=>{setHoverPipeline(p);setIsHover(true);}}
                        onPointerLeave={()=>{setHoverPipeline(null);setIsHover(false);}}>

                        <p className={`${styles.pipelineName} ${gStyles.clickable}`}
                            onClick={() => {
                                setPipeline(p);
                                sessionStorage.setItem("pipeline_id", p.id.toString());
                            }}>{p.name}</p>

                        {isHover && <div className={styles.pipelineBtns}>
                            {!(hoverPipeline?.is_active) && <>
                                <MdDeleteOutline title="Delete From History"
                                    className={`${styles.filterIcon} ${gStyles.clickable}`}/>
                                <HiOutlineUpload title="Activate Pipeline"
                                    className={`${styles.filterIcon} ${gStyles.clickable}`}/>
                            </>}
                            <HiOutlineDownload onClick={()=>downloadYaml(p)} title="Download File"
                                className={`${styles.filterIcon} ${gStyles.clickable}`}/>
                        </div>}
                        <span className={styles.subInfo}>{p.branch}</span>
                    </div>
                );})}
            </div> 
            </> : <p className={styles.noPipelines}>No pipelines found.</p>}
        </div>
    );
}

export default HistoryBar;