.docs_template:
  artifacts: &id001
    paths:
    - public
  image: alpine
  script: &id002
  - apk --no-cache add py3-pip python3-dev make
  - pip install sphinx
  - cd docs
  - make html
  - cd ..
  - mv docs/_build/html public
build-image:
  image: docker:git
  only:
  - dev/2025
  - conf/2025
  script:
  - apk update && apk add git
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker build --pull -f docker/Dockerfile -t $CONTAINER_IMAGE .
  - docker push $CONTAINER_IMAGE
  services:
  - docker:dind
  stage: build
build-sphinx:
  artifacts: *id001
  except:
  - master
  - conf/2025
  - dev/2025
  image: alpine
  script: *id002
  stage: build
k8s-deploy-prod:
  environment:
    name: 2025/prod
    url: https://2025.everythingopen.au/
  image: google/cloud-sdk
  only:
  - conf/2025
  script:
  - echo "${CA_CERT}" > cert.crt
  - kubectl config set-cluster cluster --server="${KUBE_SERVER}" --embed-certs=true
    --certificate-authority=cert.crt
  - kubectl config set-context cluster --cluster=cluster --namespace=eo2025-prod --user=gitlab-ci
  - kubectl config use-context cluster
  - kubectl --token "${KUBE_TOKEN}" set image deployment/symposion-app symposion-app=$CONTAINER_IMAGE
  stage: deploy
  when: manual
k8s-deploy-staging:
  environment:
    name: 2025/staging
    url: https://eo2025-staging.osaconftools.net/
  image: google/cloud-sdk
  only:
  - dev/2025
  script:
  - echo "${CA_CERT}" > cert.crt
  - kubectl config set-cluster cluster --server="${KUBE_SERVER}" --embed-certs=true
    --certificate-authority=cert.crt
  - kubectl config set-context cluster --cluster=cluster --namespace=eo2025-staging
    --user=gitlab-ci
  - kubectl config use-context cluster
  - kubectl --token "${KUBE_TOKEN}" set image deployment/symposion-app symposion-app=$CONTAINER_IMAGE
  stage: deploy
  when: manual
pages:
  artifacts: *id001
  environment:
    name: docs
    url: https://laconfdev.gitlab.io/symposion_app/
  image: alpine
  only:
  - master
  - conf/2025
  script: *id002
  stage: build
stages:
- build
- deploy
variables:
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE/$CONTAINER_PREFIX:$CI_COMMIT_SHA
  CONTAINER_PREFIX: 2025
  DOCKER_TLS_CERTDIR: /certs
