build:
  artifacts:
    expire_in: 15 mins
    paths:
    - node_modules/
    - out/
    - dist/
    - '*.vsix'
  script:
  - pnpm run clean
  - pnpm install --frozen-lockfile
  - pnpm add --global @vscode/vsce
  - pnpm run package
  - pnpm run build
  - pnpm run lint
  stage: build
cache:
  paths:
  - node_modules/
  - .vscode-test/
image: registry.gitlab.com/berublan/vscode-log-viewer
stages:
- build
- test
test insiders:
  script:
  - Xvfb -ac $DISPLAY &
  - pnpm run test insiders
  stage: test
test minimum:
  script:
  - Xvfb -ac $DISPLAY &
  - pnpm run test minimum
  stage: test
test stable:
  script:
  - Xvfb -ac $DISPLAY &
  - pnpm run test stable
  stage: test
variables:
  DISPLAY: :99.0
