build:linux:
  script:
  - android create project --name Plop --target android-19 --package net.mizux.plop
    --activity MainActivity --gradle -v 2.1.3 -p .
  - cp -r updated-gradle/* .
  - ./gradlew
  stage: build
image: mizux/android:latest
stages:
- build
- test
test:linux:
  script:
  - echo "TEST COMING SOON..."
  stage: test
