pages:
  artifacts:
    paths:
    - public
  image: python
  script:
  - apt-get --yes update && apt-get --yes install git
  - pip install -r requirements.txt
  - pip install -U setuptools
  - python setup.py docs
  - cp -r docs/_build/html/ .
  - mv html public
  stage: docs
  tags:
  - docker
stages:
- docs
