assembleDebug:
  script:
  - ./gradlew assembleDebug
  stage: build
before_script:
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew
cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/
image: jangrewe/gitlab-ci-android
lintDebug:
  script:
  - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint
  stage: build
stages:
- build
- test
testDebug:
  script:
  - ./gradlew -Pci --console=plain :app:testDebug
  stage: test
