before_script:
- docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
build:
  script:
  - docker build -t $IMAGE_TAG1 .
  - docker tag $IMAGE_TAG1 $IMAGE_TAG2
  - docker push $IMAGE_TAG1
  - docker push $IMAGE_TAG2
  stage: build
  tags:
  - docker
image: alpine:latest
stages:
- build
- test
- deploy
test1:
  script: echo "test1"
  stage: test
  tags:
  - docker
test2:
  script: echo "test2"
  stage: test
  tags:
  - docker
variables:
  IMAGE_TAG1: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  IMAGE_TAG2: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
