.fragment-1:
  script: &id001
  - make vvars || (make dump-generated-makefiles; exit 1)
.fragment-2:
  script: &id002
  - make DEBUG=0 && make installcheck
  - strip dte && du -k -h dte
  - tools/objsize.sh dte
  - make bench DEBUG=0 CFLAGS=-O3
.manual-test:
  extends: .test
  when: manual
.pages:
  artifacts:
    expire_in: 60 days
    name: dte-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA
    paths:
    - public
  coverage: '/^ *lines\.*: *(\d+\.\d+\%) .*$/'
  image: registry.gitlab.com/craigbarnes/dockerfiles/cdev-arch
  needs: []
  script:
  - make docs htmlgz-aux
  - make gcovr-html
  - make portable
  - ls -l public/dte-*.tar.gz
  - tree public/
  stage: dist
.test:
  needs: []
  script:
  - *id001
  - make
  - cat build/gen/build-defs.h
  - ldd dte
  - make check
  - make check LDFLAGS=-static
  - *id002
  stage: test
alpine:
  extends: .test
  image: registry.gitlab.com/craigbarnes/dockerfiles/cdev-alpine
android:
  image: registry.gitlab.com/craigbarnes/dockerfiles/android-ndk
  needs: []
  script:
  - make CC="$CC_AARCH64"
  - cat build/gen/build-defs.h
  - make CC="$CC_ARMV7A"
  - make CC="$CC_I686"
  - make CC="$CC_X86_64"
  stage: test
  when: manual
arch:
  artifacts:
    expire_in: 30 days
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build/coverage.xml
  image: registry.gitlab.com/craigbarnes/dockerfiles/cdev-arch
  needs: []
  script:
  - *id001
  - make check-source check-clang-tidy
  - make check USE_SANITIZER=1
  - make coverage-xml
  - *id002
  stage: test
debian:
  image: registry.gitlab.com/craigbarnes/dockerfiles/cdev-debian
  needs: []
  script:
  - make check CC='ccache clang'
  - make check CC='ccache clang' LDFLAGS=-static
  - make check CC='ccache gcc'
  - make check CC='ccache gcc' LDFLAGS=-static
  - make check CFLAGS='-Og -funsigned-char'
  - make check CFLAGS='-Og -fsigned-char'
  - make check
  - make installcheck
  - cat build/gen/build-defs.h
  - sed 's/ 1$/ 0/' build/gen/build-defs.h > build/gen/build-defs-tmp.h
  - mv build/gen/build-defs-tmp.h build/gen/build-defs.h
  - make check
  - cat build/gen/build-defs.h
  - make CC='ccache arm-linux-gnueabihf-gcc'
  - make CC='ccache arm-linux-gnueabihf-gcc' LDFLAGS=-static
  - make CC='ccache aarch64-linux-gnu-gcc'
  - make CC='ccache aarch64-linux-gnu-gcc' LDFLAGS=-static
  - make clean && make distcheck
  - make bench DEBUG=0 CFLAGS=-O3
  stage: test
  when: manual
debian-oldstable:
  extends: .manual-test
  image: registry.gitlab.com/craigbarnes/dockerfiles/cdev-debian-oldstable
default:
  before_script:
  - ln -s tools/Config-CI.mk Config.mk
  - export CC="ccache ${CC:-gcc}"
  - git fetch https://gitlab.com/craigbarnes/dte.git 'refs/tags/v*:refs/tags/v*'
  interruptible: true
pages:
  extends: .pages
  rules:
  - if: $CI_COMMIT_BRANCH == "master"
pages:non-master:
  extends: .pages
  rules:
  - if: $CI_COMMIT_BRANCH != "master"
rocky-8:
  extends: .manual-test
  image: registry.gitlab.com/craigbarnes/dockerfiles/cdev-rocky-8
rocky-9:
  extends: .manual-test
  image: registry.gitlab.com/craigbarnes/dockerfiles/cdev-rocky-9
stages:
- test
- dist
ubuntu:
  extends: .manual-test
  image: registry.gitlab.com/craigbarnes/dockerfiles/cdev-ubuntu
