before_script:
- make init
compile-for-production:
  artifacts:
    expire_in: 30 minutes
    untracked: true
  dependencies:
  - get-dependencies
  script:
  - make compile
  stage: compile
  variables:
    MIX_ENV: prod
compile-for-test:
  artifacts:
    expire_in: 30 minutes
    untracked: true
  dependencies:
  - get-dependencies
  script:
  - make compile
  stage: compile
  variables:
    MIX_ENV: test
get-dependencies:
  artifacts:
    expire_in: 30 minutes
    paths:
    - deps
    - mix.lock
  script:
  - make deps
  stage: setup
image: elixir:latest
lint:
  allow_failure: true
  dependencies:
  - get-dependencies
  - compile-for-test
  script:
  - make lint
  stage: test
  variables:
    MIX_ENV: test
stages:
- setup
- compile
- test
- build
- publish
- deploy
tests:
  coverage: /\[TOTAL\]\s+(\d+\.\d+)%/
  dependencies:
  - get-dependencies
  - compile-for-test
  script:
  - export $(cat .env | xargs)
  - make test
  services:
  - elasticsearch:5
  stage: test
  variables:
    MIX_ENV: test
