build:
  artifacts:
    paths:
    - /builds/${CI_PROJECT_PATH}/*.log
    when: always
  script:
  - cat /proc/cpuinfo
  - apk add --update qemu-system-x86_64 qemu-img
  - packer build -timestamp-ui tests/packer.json
  stage: build
  variables:
    PACKER_LOG: 1
image:
  entrypoint:
  - /usr/bin/env
  - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  name: hashicorp/packer:1.4.2
stages:
- validate
- build
- test
- deploy
validate:
  script:
  - packer validate tests/packer.json
  stage: validate
