.build_job:
  artifacts: &id001
    expire_in: 1 day
    paths:
    - result/*
  script: &id002
  - ci-build-pkg
  stage: build
  tags: &id003
  - docker
before_script:
- unset http_proxy ; unset https_proxy
- env | grep ^CI_
build_centos_6:
  artifacts: *id001
  image: buildpkg/centos:6
  script: *id002
  stage: build
  tags: *id003
build_centos_7:
  artifacts: *id001
  image: buildpkg/centos:7
  script: *id002
  stage: build
  tags: *id003
build_debian_bookworm:
  artifacts: *id001
  image: buildpkg/debian:bookworm
  script: *id002
  stage: build
  tags: *id003
build_debian_bullseye:
  artifacts: *id001
  image: buildpkg/debian:bullseye
  script: *id002
  stage: build
  tags: *id003
build_debian_buster:
  artifacts: *id001
  image: buildpkg/debian:buster
  script: *id002
  stage: build
  tags: *id003
build_debian_jessie:
  artifacts: *id001
  image: buildpkg/debian:jessie
  script: *id002
  stage: build
  tags: *id003
build_debian_stretch:
  artifacts: *id001
  image: buildpkg/debian:stretch
  script: *id002
  stage: build
  tags: *id003
build_fedora_24:
  artifacts: *id001
  image: buildpkg/fedora:24
  script: *id002
  stage: build
  tags: *id003
build_fedora_25:
  artifacts: *id001
  image: buildpkg/fedora:25
  script: *id002
  stage: build
  tags: *id003
build_ubuntu_bionic:
  artifacts: *id001
  image: buildpkg/ubuntu:bionic
  script: *id002
  stage: build
  tags: *id003
build_ubuntu_focal:
  artifacts: *id001
  image: buildpkg/ubuntu:focal
  script: *id002
  stage: build
  tags: *id003
build_ubuntu_jammy:
  artifacts: *id001
  image: buildpkg/ubuntu:jammy
  script: *id002
  stage: build
  tags: *id003
build_ubuntu_kinetic:
  artifacts: *id001
  image: buildpkg/ubuntu:kinetic
  script: *id002
  stage: build
  tags: *id003
build_ubuntu_lunar:
  artifacts: *id001
  image: buildpkg/ubuntu:lunar
  script: *id002
  stage: build
  tags: *id003
build_ubuntu_trusty:
  artifacts: *id001
  image: buildpkg/ubuntu:trusty
  script: *id002
  stage: build
  tags: *id003
build_ubuntu_xenial:
  artifacts: *id001
  image: buildpkg/ubuntu:xenial
  script: *id002
  stage: build
  tags: *id003
deploy_production:
  dependencies:
  - deploy_staging
  - sign
  environment:
    name: Production
    url: http://www.example.com
  image: buildpkg/ubuntu:xenial
  only:
  - master
  script:
  - ci-deploy-pkg production
  stage: production
  tags:
  - docker
  when: manual
deploy_staging:
  dependencies:
  - pages
  - sign
  environment:
    name: Staging
    url: http://www.example.com
  image: buildpkg/ubuntu:xenial
  only:
  - master
  script:
  - ci-deploy-pkg staging
  stage: staging
  tags:
  - docker
  when: manual
pages:
  artifacts:
    paths:
    - public
  dependencies:
  - sign
  environment:
    name: PPA
    url: http://${CI_PROJECT_NAMESPACE}.${PAGES_HOST}/${CI_PROJECT_NAME}
  image: buildpkg/debian:stretch
  only:
  - master
  script:
  - ci-pages-ppa
  - ci-pages-home
  - ci-pages-tree
  stage: deploy
  tags:
  - docker
  variables:
    PAGES_DIR: public
    PAGES_HOST: gitlab.io
sign:
  artifacts:
    expire_in: 1 day
    paths:
    - result/*
  dependencies:
  - build_debian_jessie
  - build_debian_stretch
  - build_debian_buster
  - build_ubuntu_trusty
  - build_ubuntu_xenial
  - build_ubuntu_yakkety
  - build_ubuntu_zesty
  - build_centos_6
  - build_centos_7
  - build_fedora_24
  - build_fedora_25
  image: buildpkg/debian:stretch
  script:
  - ci-sign-pkg
  stage: sign
  tags:
  - docker
stages:
- build
- sign
- deploy
- staging
- production
