after_script:
- $CI_PROJECT_DIR/scripts/after_script.sh
before_script:
- $CI_PROJECT_DIR/scripts/before_script.sh
- cd "$MINETEST_DIR"
build:linux_client:
  image: ubuntu:trusty
  script:
  - $CI_PROJECT_DIR/scripts/build/linux_client.sh
  stage: build
build:linux_server:
  image: ubuntu:trusty
  script:
  - $CI_PROJECT_DIR/scripts/build/linux_server.sh
  stage: build
stages:
- build
variables:
  BUILD_THREADS: 3
  MINETEST_DIR: $CI_PROJECT_DIR/minetest
