e2e:
  before_script:
  - cp -R /app/node_modules .
  script:
  - npm run test:e2e -- --headless --record --key $CYPRESS_RECORD_KEY
  stage: test
image: registry.gitlab.com/cape-modeler/frontend:latest
lint:
  before_script:
  - cp -R /app/node_modules .
  script:
  - npm run lint -- --no-fix
  stage: lint
pages:
  artifacts:
    paths:
    - public
  before_script:
  - cp -R /app/node_modules .
  only:
  - tags
  script:
  - npm run build
  - mv public public-vue
  - mv dist public
  stage: deploy
stages:
- lint
- test
- after
- deploy
unit:
  after_script:
  - ./cc-test-reporter after-build
  artifacts:
    paths:
    - coverage
  before_script:
  - cp -R /app/node_modules .
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  script:
  - npm run test:unit -- --ci
  stage: test
