before_script:
- apt-get update -yq
cache:
  paths:
  - apt/
  - cargo/
  - target/
image: rust:latest
stages:
- test
- build
test:
  script:
  - rustc --version
  - cargo --version
  - cargo test --verbose
  stage: test
variables:
  APT_CACHE_DIR: $CI_PROJECT_DIR/apt
  CARGO_HOME: $CI_PROJECT_DIR/cargo
