before_script:
- docker info
- docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
- apk update
- apk upgrade
- apk add python python-dev py-pip build-base
- pip install requests
build_image:
  script:
  - docker build -t  $PIPELINE_IMAGE_NAME .
  - docker push $PIPELINE_IMAGE_NAME
  stage: build
image: docker:latest
push_to_registy:
  only:
  - master
  script:
  - docker pull $PIPELINE_IMAGE_NAME
  - docker tag $PIPELINE_IMAGE_NAME $RELEASE_IMAGE_NAME
  - docker push $RELEASE_IMAGE_NAME
  stage: publish
run_tests:
  script:
  - docker pull $PIPELINE_IMAGE_NAME
  - docker run -d -p 5000:5000 $PIPELINE_IMAGE_NAME python test.py
  stage: test
services:
- docker:dind
stages:
- build
- test
- publish
variables:
  PIPELINE_IMAGE_NAME: registry.gitlab.com/dfederschmidt/docker-pipenv-sample:$CI_BUILD_REF_NAME
  RELEASE_IMAGE_NAME: registry.gitlab.com/dfederschmidt/docker-pipenv-sample:latest
