build and register container for ppe:
  image: docker:stable
  only:
  - master
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  - docker build -t $CI_REGISTRY_IMAGE:latest .
  - docker push $CI_REGISTRY_IMAGE:latest
  services:
  - docker:dind
  stage: register-container-ppe
build and register container for release:
  except:
  - branches
  image: docker:stable
  only:
  - tags
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
  - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  services:
  - docker:dind
  stage: register-container-release
build and register container for test:
  image: docker:stable
  only:
  - develop
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  - docker build -t $CI_REGISTRY_IMAGE:develop .
  - docker push $CI_REGISTRY_IMAGE:develop
  services:
  - docker:dind
  stage: register-container-test
build asset:
  artifacts:
    paths:
    - target
  image: maven:3.6.0-jdk-8
  only:
  - develop
  - master
  - tags
  script:
  - mvn clean package -U -B -DskipTests
  stage: build-asset
deploy to edp ppe:
  image: appropriate/curl
  only:
  - master
  script:
  - curl -sSfI https://$EDP2_JENKINS_USER:$EDP2_JENKINS_PW@$EDP2_JENKINS_BASEURL/$JENKINS_JOB_PPE/build?token=$EDP2_JENKINS_TOKEN
  stage: deploy-edp-ppe
setup okd app:
  image: ebits/openshift-client
  only:
  - develop
  script:
  - oc login "$OKD_MASTER_URL" --token="$OKD_TOKEN_EDP2" --insecure-skip-tls-verify
  - oc import-image $CI_PROJECT_NAME --from=$CI_REGISTRY_IMAGE:develop --confirm
  - oc get services $CI_PROJECT_NAME 2> /dev/null || oc new-app --name=$CI_PROJECT_NAME
    --image-stream=$CI_PROJECT_NAME
  - oc get routes $CI_PROJECT_NAME 2> /dev/null || oc create route edge --service=$CI_PROJECT_NAME
    --hostname=$CI_PROJECT_NAME-$OKD_EDP2_PROJECT.$OKD_DOMAIN --insecure-policy=Redirect
    --port=$APPLICATION_PORT
  stage: deploy-okd
  tags:
  - fokus-okd
stages:
- build-asset
- register-container-test
- register-container-ppe
- register-container-release
- deploy-okd
- deploy-edp-ppe
variables:
  APPLICATION_PORT: 8080
  JENKINS_JOB_PPE: ppe-metrics
  JENKINS_JOB_PROD: prod-metrics
