coverage:
  artifacts:
    expire_in: 30 days
    paths:
    - public
  dependencies:
  - rspec
  only:
  - master
  script:
  - mv coverage/ public/
  stage: test_badge
image: ruby:2.3
rspec:
  artifacts:
    paths:
    - coverage/
  script:
  - cp config/mongoid-ci.yml config/mongoid.yml
  - gem install bundler --no-ri --no-rdoc
  - bundle check || bundle install
  - bundle exec rspec
  services:
  - mongo:latest
  stage: test
  variables:
    MONGO_HOST: mongo
    MONGO_PASSWORD: admin
    MONGO_PORT: '27017'
    MONGO_USER: admin
stages:
- test
- test_badge
