.release_base_scripts: &id003
  before_script:
  - set -- $CI_BUILD_NAME
  - export RUBY_VERSION=$2
  - export IMAGE_DIR=base
  - export IMAGE_NAME=$CI_REGISTRY_IMAGE:$RUBY_VERSION
  - cp $IMAGE_DIR/Dockerfile.template $IMAGE_DIR/Dockerfile
  - sed -i "s@ruby:ruby_version@ruby:$RUBY_VERSION@g" $IMAGE_DIR/Dockerfile
  only: &id001
  - master
  script: &id002
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  - docker build -t $IMAGE_NAME -f $IMAGE_DIR/Dockerfile $IMAGE_DIR/
  - docker push $IMAGE_NAME
  stage: release_base
.release_other: &id004
  before_script:
  - set -- $CI_BUILD_NAME
  - export RUBY_VERSION=$2
  - export EXTENDED_NAME=$3
  - export IMAGE_DIR=$EXTENDED_NAME
  - export BASE_IMAGE_NAME=$CI_REGISTRY_IMAGE:$RUBY_VERSION
  - export IMAGE_NAME=$BASE_IMAGE_NAME-$EXTENDED_NAME
  - cp $IMAGE_DIR/Dockerfile.template $IMAGE_DIR/Dockerfile
  - sed -i  "s@base_image_name@$BASE_IMAGE_NAME@g" $IMAGE_DIR/Dockerfile
  only: *id001
  script: *id002
  stage: release_other
.release_scripts:
  only: *id001
  script: *id002
before_script:
- docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
image: docker:git
release 2.1: *id003
release 2.1 firefox: *id004
release 2.1 google-chrome: *id004
release 2.3: *id003
release 2.3 google-chrome: *id004
services:
- docker:dind
stages:
- test
- release_base
- release_other
test:
  script:
  - echo 'Pending!'
  stage: test
variables:
  DOCKER_DRIVER: overlay
