build-client-code:
  artifacts:
    expire_in: 1 day
    paths:
    - aws-client/UnicornLambdaCode.zip
  before_script:
  - apt-get update -qq && apt-get install -y -qq zip
  image: node:16
  script:
  - cd aws-client/UnicornLambdaCode
  - npm install
  - zip -r ../UnicornLambdaCode.zip *
  - cd ../..
  stage: build
clean-all:
  before_script:
  - pip install awscli
  environment:
    action: stop
    name: ${CI_COMMIT_REF_SLUG}
  except:
  - master
  image: python:latest
  script:
  - aws s3 rm s3://${AWS_S3_BUCKET_NAME}/${CI_COMMIT_REF_SLUG} --recursive
  - aws s3 rm s3://${AWS_S3_BUCKET_NAME}/chalice/${CI_COMMIT_REF_SLUG} --recursive
  - aws cloudformation delete-stack ${AWS_API_STACK_NAME}
  stage: deploy-client
  when: manual
create-s3:
  before_script:
  - pip install awscli
  image: python:latest
  only:
  - master
  script:
  - aws cloudformation deploy --template-file aws-unicorn/aws-client-s3.yml --stack-name
    ${AWS_S3_STACK_NAME} --no-fail-on-empty-changeset --region ca-central-1
  - aws cloudformation deploy --template-file aws-unicorn/aws-client-s3.yml --stack-name
    ${AWS_S3_STACK_NAME} --no-fail-on-empty-changeset --region us-east-1
  stage: build
deploy-api:
  artifacts:
    paths:
    - aws-unicorn/endpoint-url.output
  before_script:
  - pip install awscli chalice
  image: python:latest
  script:
  - cd aws-unicorn
  - pip install -r requirements.txt
  - chalice package --stage prod package/
  - aws cloudformation package --template-file package/sam.json --s3-bucket ${AWS_S3_BUCKET_NAME}
    --s3-prefix chalice/${CI_COMMIT_REF_SLUG}/ --force-upload --output-template-file
    cloud-formation-packaged.yml
  - aws cloudformation deploy --template-file cloud-formation-packaged.yml --stack-name
    ${AWS_API_STACK_NAME} --capabilities CAPABILITY_IAM --no-fail-on-empty-changeset
  - aws cloudformation describe-stacks --stack-name ${AWS_API_STACK_NAME} --query
    "Stacks[].Outputs[?OutputKey=='EndpointURL'][] | [0].OutputValue" --output text
    > endpoint-url.output
  - cat endpoint-url.output
  stage: deploy-api
deploy-client:
  before_script:
  - pip install awscli
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    on_stop: clean-all
    url: ${AWS_TEMPLATE_URL}
  image: python:latest
  script:
  - sed -i -e "s|{{ACCOUNT_ID}}|${AWS_ACCOUNT_ID}|g" aws-client/UnicornAccessRole.yml
  - sed -i -e "s|{{ENDPOINT_URL}}|$(cat aws-unicorn/endpoint-url.output)|g" aws-client/UnicornAccessRole.yml
  - sed -i -e "s|{{CHILD_TEMPLATE_URL}}|${AWS_CHILD_TEMPLATE_URL}|g" aws-client/UnicornAccessRole.yml
  - sed -i -e "s|{{BUCKET_NAME}}|${AWS_S3_BUCKET_NAME}|g" aws-client/UnicornAccessRole.yml
  - aws s3 cp aws-client s3://${AWS_S3_BUCKET_NAME}/${CI_COMMIT_REF_SLUG} --recursive
    --exclude UnicornLambdaCode/* --acl public-read
  - echo ${AWS_TEMPLATE_URL}
  stage: deploy-client
deploy-client-us-east-1:
  before_script:
  - pip install awscli
  image: python:latest
  only:
  - master
  script:
  - sed -i -e "s|{{ACCOUNT_ID}}|${AWS_ACCOUNT_ID}|g" aws-client/UnicornAccessRole.yml
  - sed -i -e "s|{{ENDPOINT_URL}}|$(cat aws-unicorn/endpoint-url.output)|g" aws-client/UnicornAccessRole.yml
  - sed -i -e "s|{{CHILD_TEMPLATE_URL}}|${AWS_CHILD_TEMPLATE_URL}|g" aws-client/UnicornAccessRole.yml
  - sed -i -e "s|{{BUCKET_NAME}}|${AWS_S3_BUCKET_NAME}|g" aws-client/UnicornAccessRole.yml
  - aws s3 cp aws-client s3://${AWS_S3_BUCKET_NAME}/${CI_COMMIT_REF_SLUG} --recursive
    --exclude UnicornLambdaCode/* --acl public-read
  - echo ${AWS_TEMPLATE_URL}
  stage: deploy-client
  variables:
    AWS_DEFAULT_REGION: us-east-1
stages:
- build
- deploy-api
- deploy-client
variables:
  AWS_API_STACK_NAME: ${AWS_CLIENT_NAME}-api-${CI_COMMIT_REF_SLUG}
  AWS_CHILD_TEMPLATE_URL: https://s3.${AWS_DEFAULT_REGION}.amazonaws.com/${AWS_CLIENT_NAME}-${AWS_DEFAULT_REGION}/${CI_COMMIT_REF_SLUG}/UnicornAccessRoleChild.yml
  AWS_CLIENT_NAME: aws-client
  AWS_DEFAULT_REGION: ca-central-1
  AWS_S3_BUCKET_NAME: ${AWS_CLIENT_NAME}-${AWS_DEFAULT_REGION}
  AWS_S3_STACK_NAME: ${AWS_CLIENT_NAME}-s3
  AWS_TEMPLATE_URL: https://s3.${AWS_DEFAULT_REGION}.amazonaws.com/${AWS_CLIENT_NAME}-${AWS_DEFAULT_REGION}/${CI_COMMIT_REF_SLUG}/UnicornAccessRole.yml
