.clean:
  before_script: &id010 []
  cache: &id001 {}
  dependencies: &id002 []
.insights_script:
  artifacts: &id007
    expire_in: 31d
    paths:
    - ./data
  before_script: &id008
  - mkdir ./data
  image: ruby:2.6
  tags: &id009
  - gitlab-org
.production:
  except: &id003
    refs:
    - schedules
  only: &id004
    refs:
    - master
.review:
  except: &id005
    refs:
    - master
  only: &id006
    refs:
    - branches
build_production_image:
  before_script: []
  cache: *id001
  dependencies: *id002
  except: *id003
  only: *id004
  script:
  - docker build -t $CI_REGISTRY_IMAGE/gitlab-insights-production:$CI_COMMIT_REF_NAME
    -t $CI_REGISTRY_IMAGE/gitlab-insights-production:latest .
  stage: build
  tags:
  - gitlab-insights-docker
build_review_image:
  before_script: []
  cache: *id001
  dependencies: *id002
  except: *id005
  only: *id006
  script:
  - docker build -t $CI_REGISTRY_IMAGE/gitlab-insights-review:$CI_COMMIT_REF_NAME
    -t $CI_REGISTRY_IMAGE/gitlab-insights-review:latest .
  stage: build
  tags:
  - gitlab-insights-docker
community_mrs:
  artifacts: *id007
  before_script: *id008
  cache: *id001
  dependencies: *id002
  image: ruby:2.6
  only:
    refs:
    - schedules
    variables:
    - $COMMUNITY_MRS
  script:
  - gem install httparty --no-document
  - bin/community-mrs --token $API_TOKEN --dev-token $DEV_API_TOKEN --format csv
  stage: build
  tags: *id009
deploy:
  before_script: *id010
  cache: *id001
  dependencies: *id002
  environment:
    name: production
    url: https://quality-dashboard.gitlap.com
  except:
  - schedules
  only:
  - master
  script:
  - docker stop insights-production || true
  - docker rm insights-production || true
  - docker run -d -P -e "VIRTUAL_HOST=quality-dashboard.gitlap.com" -e "LETSENCRYPT_HOST=quality-dashboard.gitlap.com"
    -e "LETSENCRYPT_EMAIL=$LE_EMAIL" -e "RAILS_ENV=production" -e "SECRET_KEY_BASE=$SECRET_KEY_BASE_PROD"
    -e "SECRET_TOKEN=$SECRET_TOKEN_PROD" -e "DATABASE_USERNAME=$DATABASE_USERNAME"
    -e "DATABASE_PASSWORD=$DATABASE_PASSWORD" --name insights-production --network
    insights-net --link postgresql:postgresql $CI_REGISTRY_IMAGE/gitlab-insights-production:$CI_COMMIT_REF_NAME
  stage: deploy
  tags:
  - gitlab-insights-docker
  variables:
    GIT_STRATEGY: none
failed_flaky_checks:
  artifacts: *id007
  before_script: *id008
  cache: *id001
  dependencies: *id002
  image: ruby:2.6
  only:
    refs:
    - schedules
    variables:
    - $FAILED_FLAKY_CHECKS
  script:
  - gem install httparty --no-document
  - bin/failed-flaky-checks --token $API_TOKEN --format csv --start-date $(date -d
    "-1 day" "+%Y-%m-%d")
  stage: build
  tags: *id009
maintainers-gitlab:
  artifacts: *id007
  before_script: *id008
  cache: *id001
  dependencies: *id002
  image: ruby:2.6
  only:
    refs:
    - schedules
    variables:
    - $MAINTAINERS
  script:
  - gem install httparty --no-document
  - bin/maintainers --token $API_TOKEN --project $PROJECT
  stage: build
  tags: *id009
  variables:
    PROJECT: gitlab-org/gitlab
pipelines_duration:
  artifacts: *id007
  before_script: *id008
  cache: *id001
  dependencies: *id002
  image: ruby:2.6
  only:
    refs:
    - schedules
    variables:
    - $PIPELINES_DURATION
  script:
  - gem install httparty --no-document
  - bin/pipelines-duration --token $API_TOKEN --format csv --start-date $(date -d
    "-1 day" "+%Y-%m-%d")
  stage: build
  tags: *id009
populate_prod_db:
  before_script: *id010
  cache: *id001
  dependencies: *id002
  only:
    refs:
    - schedules
    variables:
    - $POPULATE_PROD_DB
  retry: 2
  script:
  - docker stop insights-production-db-populate || true
  - docker rm insights-production-db-populate || true
  - docker run -i -P -e "RAILS_ENV=production" -e "DATABASE_USERNAME=$DATABASE_USERNAME"
    -e "DATABASE_PASSWORD=$DATABASE_PASSWORD" --name insights-production-db-populate
    --network insights-net --link postgresql:postgresql $CI_REGISTRY_IMAGE/gitlab-insights-production:latest
    /bin/bash -c "bundle exec rake 'gitlab_insights:populate[$API_TOKEN, $API_TOKEN_DEV]'"
  - docker rm insights-production-db-populate
  stage: populate
  tags:
  - gitlab-insights-docker
  variables:
    GIT_STRATEGY: none
populate_review_db:
  before_script: *id010
  cache: *id001
  dependencies: *id002
  except: *id005
  only: *id006
  retry: 2
  script:
  - docker stop insights-review-db-populate || true
  - docker rm insights-review-db-populate || true
  - docker run -i -P -e "RAILS_ENV=review" -e "DATABASE_USERNAME=$DATABASE_USERNAME"
    -e "DATABASE_PASSWORD=$DATABASE_PASSWORD" --name insights-review-db-populate --network
    insights-net --link postgresql:postgresql $CI_REGISTRY_IMAGE/gitlab-insights-review:latest
    /bin/bash -c "bundle exec rake 'gitlab_insights:populate[$API_TOKEN, $API_TOKEN_DEV]'"
  - docker rm insights-review-db-populate
  stage: populate
  tags:
  - gitlab-insights-docker
  variables:
    GIT_STRATEGY: none
  when: manual
review:
  before_script: *id010
  cache: *id001
  dependencies: *id002
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    on_stop: review_stop
    url: https://$CI_COMMIT_REF_SLUG-review.quality-dashboard.gitlap.com
  except:
  - master
  only:
  - branches
  script:
  - docker stop insights-$CI_COMMIT_REF_NAME || true
  - docker rm insights-$CI_COMMIT_REF_NAME || true
  - docker run -d -P -e "VIRTUAL_HOST=$CI_COMMIT_REF_SLUG-review.quality-dashboard.gitlap.com"
    -e "LETSENCRYPT_HOST=$CI_COMMIT_REF_SLUG-review.quality-dashboard.gitlap.com"
    -e "LETSENCRYPT_EMAIL=$LE_EMAIL" -e "RAILS_ENV=review" -e "SECRET_KEY_BASE=$SECRET_KEY_BASE_REVIEW"
    -e "SECRET_TOKEN=$SECRET_TOKEN_REVIEW" -e "DATABASE_USERNAME=$DATABASE_USERNAME"
    -e "DATABASE_PASSWORD=$DATABASE_PASSWORD" --name insights-$CI_COMMIT_REF_NAME
    --network insights-net --link postgresql:postgresql $CI_REGISTRY_IMAGE/gitlab-insights-review:$CI_COMMIT_REF_NAME
  stage: deploy
  tags:
  - gitlab-insights-docker
  variables:
    GIT_STRATEGY: none
review_stop:
  before_script: *id010
  cache: *id001
  dependencies: *id002
  environment:
    action: stop
    name: review/$CI_COMMIT_REF_SLUG
  except:
  - master
  only:
  - branches
  script:
  - docker stop insights-$CI_COMMIT_REF_NAME || true
  - docker rm insights-$CI_COMMIT_REF_NAME || true
  - docker rmi $CI_REGISTRY_IMAGE/gitlab-insights-review:$CI_COMMIT_REF_NAME || true
  stage: deploy
  tags:
  - gitlab-insights-docker
  variables:
    GIT_STRATEGY: none
  when: manual
rspec:
  artifacts:
    expire_in: 31d
    reports:
      junit: junit_rspec.xml
    when: always
  before_script:
  - bundle install --clean --without=production --jobs=$(nproc) --path=vendor --retry=3
    --quiet
  - bin/rake db:test:prepare
  cache:
    key:
      files:
      - Gemfile.lock
      prefix: ${CI_JOB_NAME}
    paths:
    - vendor/ruby
  image: registry.gitlab.com/gitlab-org/gitlab-build-images:ruby-2.6.3-git-2.22-chrome-73.0-node-12.x-yarn-1.21-graphicsmagick-1.3.34-docker-19.03.1
  script:
  - bundle exec rspec --color --format documentation --format RspecJunitFormatter
    --out junit_rspec.xml
  services:
  - postgres:9.6.17
  stage: test
  tags:
  - gitlab-org
  variables:
    DATABASE_URL: postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB
    POSTGRES_HOST_AUTH_METHOD: trust
stages:
- test
- build
- deploy
- populate
