build:
  before_script:
  - echo "Running build $CI_JOB_ID for commit $CI_COMMIT_SHA with commit ref name
    $CI_COMMIT_REF_NAME"
  - mkdir $HOME/.docker
  - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
  - docker info
  image: $MUSIT_DOCKER_REGISTRY/musit/docker-scala-sbt
  only:
  - master@MUSIT-Norway/musit
  script:
  - sbt docker:publish
  services:
  - $MUSIT_DOCKER_REGISTRY/library/docker:dind
  stage: build
  tags:
  - docker
  - musit
  - utv
  variables:
    DOCKER_DRIVER: overlay
cache:
  paths:
  - cache
  untracked: true
stages:
- test
- build
test:
  coverage: /\[info]\sAll\sdone\.\sCoverage\swas\s\[(.*)%\]/
  image: registry.gitlab.com/musit-norway/docker-scala-sbt
  script:
  - echo "Building and running tests..."
  - sbt clean scalastyle scalafmt
  - git status
  - git diff --exit-code || (echo "ERROR Scala formatting check failed, see differences
    above."; false)
  - if [[ -n "$CODACY_PROJECT_TOKEN" ]]; then echo "Running with code coverage...";
    sbt coverage allTests:test coverageReport; sbt coverageAggregate; sbt codacyCoverage;
    else echo "Coverage reporting disabled for forks"; sbt allTests:test; fi
  services:
  - name: postgres:latest
  - alias: elasticsearch
    name: registry.gitlab.com/musit-norway/docker-elasticsearch:latest
  stage: test
  tags:
  - docker
  - shared
  variables:
    ELASTICSEARCH_HOST: elasticsearch
    ELASTICSEARCH_PORT: 9200
    MUSIT_FUTURE_INTERVAL: '50'
    MUSIT_FUTURE_TIMEOUT: '15000'
    POSTGRES_DB: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres
    SYMBIOTIC_POSTGRES_HOST: postgres
variables:
  COURSIER_CACHE: /root/cache/coursier
  DOCKER_DRIVER: overlay
