build:
  artifacts:
    paths:
    - dist/
  dependencies:
  - setup
  only:
  - master
  script:
  - npm run build
  stage: build
  when: on_success
deploy:
  before_script:
  - apt-get update -y
  - apt-get install rsync openssh-client -y
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  dependencies:
  - setup
  - build
  environment:
    name: Demo
  only:
  - master
  script:
  - rsync -hrvz --delete --exclude=_ -e 'ssh -i id_rsa' dist/ fro@frodesigns.com:/home/fro/pwa-skeleton/
  stage: deploy
  when: on_success
image: node:latest
setup:
  artifacts:
    paths:
    - node_modules/
  only:
  - master
  script:
  - npm install
  stage: setup
stages:
- setup
- build
- deploy
