before_script:
- npm install --ignore-scripts
build:
  artifacts:
    expire_in: 30 min
    paths:
    - dist
  only:
  - /^v\d\.\d\.\d$/
  script:
  - npm run build
  stage: build
build:api:
  artifacts:
    expire_in: 30 min
    paths:
    - api
  only:
  - /^v\d\.\d\.\d$/
  script:
  - npm run build:api
  stage: build
cache:
  key: $CI_PROJECT_ID
  paths:
  - node_modules
image: node:boron-alpine
lint:
  script:
  - npm run lint
  stage: lint
pages:
  artifacts:
    paths:
    - public
  dependencies:
  - build
  - build:api
  - test:coverage
  only:
  - /^v\d\.\d\.\d$/
  script:
  - mkdir -p public/coverage
  - mkdir -p public/api
  - cp -r coverage/* public/coverage/
  - cp -r api/* public/api/
  stage: deploy
publish:
  dependencies:
  - build
  - build:api
  only:
  - /^v\d\.\d\.\d$/
  script:
  - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
  - npm publish --access public
  stage: deploy
stages:
- lint
- test
- build
- deploy
test:coverage:
  artifacts:
    expire_in: 30 min
    paths:
    - coverage
  coverage: /Statements\s+:\s(\d+(?:\.\d+)?%)/
  script:
  - npm run test:coverage
  stage: test
test:node:4:
  allow_failure: true
  image: node:argon-alpine
  script:
  - npm run test
  stage: test
test:node:6:
  script:
  - npm run test
  stage: test
test:node:7:
  image: node:alpine
  script:
  - npm run test
  stage: test
