before_script:
- chmod o=-w "../${CI_PROJECT_NAME}"
- curl -fsSL https://get.docker.com | sh
- pip install ansible ansible-lint docker-py
- chmod o=-w tests
- cd tests
check_dist:
  script:
  - ansible-playbook --syntax-check test_docker_distrib.yml
  stage: check
check_std:
  script:
  - ansible-playbook --syntax-check test_docker_install.yml
  stage: check
distributed:
  script:
  - ansible-playbook test_docker_distrib.yml -v -e "minio_port=9000"
  - echo "idempotence test"
  - ansible-playbook test_docker_distrib.yml -e "minio_port=9000"
  - tail ansible.log | grep 'minio.*changed=0.*unreachable=0.*failed=0'
  stage: tests
image: ansible/ansible:centos7
lint:
  script:
  - ansible-lint *.yml
  stage: check
services:
- docker:dind
stages:
- check
- tests
standalone:
  script:
  - ansible-playbook test_docker_install.yml -v -e "minio_port=9000"
  - echo "idempotence test"
  - ansible-playbook test_docker_install.yml -e "minio_port=9000"
  - tail ansible.log | grep 'minio.*changed=0.*unreachable=0.*failed=0'
  stage: tests
