deploy_codegrant_to_lambda:
  before_script:
  - npm i -g serverless
  only:
    refs:
    - master
  script:
  - cd codegrant_display
  - sls deploy
  stage: deploy
deploy_logic_to_lambda:
  before_script:
  - npm i -g serverless
  only:
    refs:
    - master
  script:
  - cd main
  - npm install
  - sls deploy
  stage: deploy
image: node:8.1.0
stages:
- deploy
