.race_detector:
  script:
  - make race
  stage: test
before_script:
- apk add --no-cache git build-base bash
- mkdir -p /go/src/gitlab.com/$CI_PROJECT_NAMESPACE /go/src/_/builds
- cp -r $CI_PROJECT_DIR /go/src/gitlab.com/$CI_PROJECT_PATH
- ln -s /go/src/gitlab.com/$CI_PROJECT_NAMESPACE /go/src/_/builds/$CI_PROJECT_NAMESPACE
- make dep
cache:
  paths:
  - /go/src/github.com
  - /go/src/gitlab.com
  - /go/src/golang.org
  - /go/src/google.golang.org
  - /go/src/gopkg.in
code_coverage:
  script:
  - make coverage
  stage: test
image: golang:alpine
lint_code:
  script:
  - go get github.com/go-critic/go-critic/cmd/gocritic
  - go install github.com/go-critic/go-critic/cmd/gocritic
  - make lint
  stage: test
stages:
- test
unit_tests:
  script:
  - make test
  stage: test
