before_script:
- chmod +x gradlew
- printf "mvnMakerTimUsername=$MVN_USER\n" > gradle.properties
- printf "mvnMakerTimPassword=$MVN_PASS\n" >> gradle.properties
- printf "globVersion=1.$(git rev-list --all --count)\n" >> gradle.properties
deploy:
  script:
  - ./gradlew publish
  stage: deploy
image: openjdk:8-jdk
stages:
- test
- deploy
test:
  script:
  - ./gradlew test
  stage: test
variables:
  GRADLE_OPTS: -Dorg.gradle.daemon=false
