.build:
  artifacts: &id001
    paths:
    - conda-bld
    - config.log
    - build.log
    when: always
  script: &id003
  - cd "${CI_PROJECT_DIR}/recipe"
  - export CF_COMPILER_STACK="comp4"
  - sudo ln -s /usr/lib64/libssl.so.1.0.1e /usr/lib64/libssl.so.1.0.0
  - sudo ln -s /usr/lib64/libcrypto.so.1.0.1e /usr/lib64/libcrypto.so.1.0.0
  - conda build . --variant-config-files conda_build_config.yaml --python ${PYTHON_VERSION}
    --output-folder "${CI_PROJECT_DIR}/conda-bld" --no-test 2>&1 | tee "${CI_PROJECT_DIR}/build-log.txt"
  stage: build
.configure:
  before_script: &id002
  - sudo yum update -y -q
  - sudo yum install -y -q bzip2 make patch sudo tar which libXext-devel libXrender-devel
    libSM-devel libX11-devel mesa-libGL-devel
  - sudo yum install -y -q centos-release-scl yum-utils
  - sudo yum-config-manager --enable rhel-server-rhscl-7-rpms
  - sudo yum install -y -q devtoolset-7-binutils devtoolset-7-gcc devtoolset-7-gcc-gfortran
    devtoolset-7-gcc-c++
  - export PATH="/opt/rh/devtoolset-7/root/usr/bin:$PATH"
  - conda config --add channels pkgw-forge
  - conda config --add channels defaults
  - conda config --add channels conda-forge/label/cf201901
  - conda config --add channels conda-forge
  - conda update -y -q --no-channel-priority conda conda-build
.deploy:
  except: &id004
  - triggers
  script: &id005
  - if [[ ${CI_COMMIT_REF_NAME} = 'master' ]] ; then anaconda -t $ANACONDA_TOKEN upload
    $CI_PROJECT_DIR/conda-bld/linux-64/*.tar.bz2 -u ${CI_PROJECT_NAMESPACE} --force
    --no-progress ; else anaconda -t $ANACONDA_TOKEN upload $CI_PROJECT_DIR/conda-bld/linux-64/*.tar.bz2
    -u ${CI_PROJECT_NAMESPACE} --label dev --force --no-progress ; fi
  stage: deploy
.py27:
  PYTHON_VERSION: '2.7'
.py36:
  PYTHON_VERSION: '3.6'
.py37:
  PYTHON_VERSION: '3.7'
.test:
  artifacts: &id006
    paths:
    - environment-py${PYTHON_VERSION/./}.yml
  script: &id007
  - cp -r $CI_PROJECT_DIR/conda-bld/* /opt/conda/conda-bld/
  - conda index /opt/conda/conda-bld/
  - cd "${CI_PROJECT_DIR}/recipe"
  - export CF_COMPILER_STACK="comp4"
  - conda build . --variant-config-files conda_build_config.yaml --python ${PYTHON_VERSION}
    --test
  stage: test
build-py27:
  artifacts: *id001
  before_script: *id002
  script: *id003
  stage: build
  variables:
    PYTHON_VERSION: '2.7'
build-py36:
  artifacts: *id001
  before_script: *id002
  script: *id003
  stage: build
  variables:
    PYTHON_VERSION: '3.6'
build-py37:
  artifacts: *id001
  before_script: *id002
  script: *id003
  stage: build
  variables:
    PYTHON_VERSION: '3.7'
deploy-py27:
  dependencies:
  - build-py27
  except: *id004
  script: *id005
  stage: deploy
deploy-py36:
  dependencies:
  - build-py36
  except: *id004
  script: *id005
  stage: deploy
deploy-py37:
  dependencies:
  - build-py37
  except: *id004
  script: *id005
  stage: deploy
image: registry.gitlab.com/ostrokach-docker/conda:latest
stages:
- build
- test
- deploy
test-py27:
  artifacts: *id006
  before_script: *id002
  dependencies:
  - build-py27
  script: *id007
  stage: test
  variables:
    PYTHON_VERSION: '2.7'
test-py36:
  artifacts: *id006
  before_script: *id002
  dependencies:
  - build-py36
  script: *id007
  stage: test
  variables:
    PYTHON_VERSION: '3.6'
test-py37:
  artifacts: *id006
  before_script: *id002
  dependencies:
  - build-py37
  script: *id007
  stage: test
  variables:
    PYTHON_VERSION: '3.7'
