.compile_svgs:
  artifacts:
    expire_in: 1 day
    paths:
    - img-*.pdf*
    - svg/*.svg
  image: finwood/inkscape
  script:
  - make svgs
  stage: pre-build
.render_templates:
  artifacts:
    expire_in: 1 day
    untracked: true
  image: registry.gitlab.com/finwood/rt2
  script:
  - make templates
  stage: pre-build
cache:
  key: $CI_COMMIT_REF_NAME
  untracked: true
compile:
  artifacts:
    expire_in: 4 weeks
    paths:
    - latex.out/
  image: finwood/latex
  script:
  - make pdf
  stage: build
stages:
- pre-build
- build
variables:
  TZ: Europe/Berlin
