.build:
  script:
  - docker build -t ${IMAGE_TAG} -f ${DOCKERFILE} ${CONTEXT}
  - docker push ${IMAGE_TAG}
  stage: build
before_script:
- docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
image: docker:19.03.12
include:
- /gitlab-build-defs/dev-environment.yml
- /gitlab-build-defs/publish.yml
services:
- docker:19.03.13-dind
stages:
- build
- test-dev
- test-publish
