before_script:
- mkdir -p _ccache
- export CCACHE_BASEDIR=${PWD}
- export CCACHE_DIR=${PWD}/_ccache
build-meson:
  artifacts:
    expire_in: 1 week
    paths:
    - bld/meson-dist/vala-panel*.tar.xz
  image: alpine:edge
  script:
  - apk add --no-cache python3 gtk+3.0-dev vala meson ninja libxkbcommon-dev libcanberra
    libgweather4-dev libgtop-dev build-base gobject-introspection-dev git py3-pip
  - meson bld --prefix=/usr && cd bld
  - ninja install
  stage: build
cache:
  paths:
  - _ccache/
release-main:
  image: alpine:edge
  only:
  - tags
  script:
  - apk add --no-cache python3
  - pip3 install gitlab_release
  - python3 -m gitlab_release ${PRIVATE_TOKEN} build/vala-panel*.tar.xz
  stage: release
stages:
- build
- release
