.distribution:
  script:
  - make tests
  stage: dist
archlinux:
  before_script:
  - pacman -Syu --noconfirm --noprogressbar make grep pass git jq kcov
  extends: .distribution
  image: archlinux
debian:
  before_script:
  - apt-get update -q && apt-get install -y make pass grep wget git xz-utils
  extends: .distribution
  image: debian
fedora:
  before_script:
  - dnf -y install make gpg pass grep git findutils --setopt=install_weak_deps=False
  extends: .distribution
  image: fedora
pages:
  artifacts:
    expire_in: 2 days
    paths:
    - public
  dependencies:
  - tests
  rules:
  - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
  - mv kcov/ public/
  stage: deploy
shellcheck:
  image: koalaman/shellcheck-alpine
  script:
  - shellcheck --shell=bash update.bash tests/commons tests/results
  stage: lint
stages:
- lint
- tests
- dist
- deploy
tests:
  artifacts:
    expire_in: 2 days
    paths:
    - kcov/
  before_script:
  - pacman -Syu --noconfirm --noprogressbar make grep pass git jq kcov
  image: archlinux
  script:
  - make tests COVERAGE=true
  - mv /tmp/tests/pass-update/kcov kcov/
  stage: tests
ubuntu:
  before_script:
  - apt-get update -q && apt-get install -y make pass grep git
  extends: .distribution
  image: ubuntu
