.base_docker:
  before_script: &id001
  - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
  image: ${DOCKER_REGISTRY}/docker:${NIGHTLY_IMAGE_TAG}
  services: &id002
  - docker:dind
.base_docker_retagging:
  before_script: *id001
  image: ${DOCKER_REGISTRY}/docker:${NIGHTLY_IMAGE_TAG}
  only: &id009
  - master
  script: &id008
  - docker pull "${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
  - docker tag "${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}" "${DOCKER_REGISTRY}/${IMAGE_NAME}:latest"
  - docker tag "${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}" "${DOCKER_REGISTRY}/${IMAGE_NAME}:${CI_PIPELINE_IID}"
  - docker push "${DOCKER_REGISTRY}/${IMAGE_NAME}:latest"
  - docker push "${DOCKER_REGISTRY}/${IMAGE_NAME}:${CI_PIPELINE_IID}"
  services: *id002
.base_go:
  before_script: &id003
  - mkdir -p "/go/src/gitlab.com/1git"
  - ln -svf "/builds/1git/1git" "/go/src/gitlab.com/1git"
  - cd "/go/src/gitlab.com/1git/1git"
  image: ${DOCKER_REGISTRY}/golang:${NIGHTLY_IMAGE_TAG}
.build_go:
  artifacts: &id004
    paths:
    - ${PROJECT_PATH}/out/${ARTIFACT_NAME}
  before_script: *id003
  image: ${DOCKER_REGISTRY}/golang:${NIGHTLY_IMAGE_TAG}
  script: &id005
  - cd "${PROJECT_PATH}"
  - go build -race -o "out/${ARTIFACT_NAME}"
  variables:
    TARGET_ARCH: amd64
    TARGET_OS: linux
.build_vuejs:
  artifacts: &id006
    paths:
    - ${PROJECT_PATH}/dist
  image: node:latest
  script: &id007
  - cd "${PROJECT_PATH}"
  - npm install
  - npm run build
build-centos-builder:
  before_script: *id001
  image: ${DOCKER_REGISTRY}/docker:${NIGHTLY_IMAGE_TAG}
  only:
  - schedules
  script:
  - cd docker/centos/builder
  - docker build -t "${DOCKER_REGISTRY}/golang:${NIGHTLY_IMAGE_TAG}" .
  - docker build -t "${DOCKER_REGISTRY}/golang-linter:${NIGHTLY_IMAGE_TAG}" -f Dockerfile.linter
    .
  - docker push "${DOCKER_REGISTRY}/golang:${NIGHTLY_IMAGE_TAG}"
  - docker push "${DOCKER_REGISTRY}/golang-linter:${NIGHTLY_IMAGE_TAG}"
  services: *id002
  stage: nightly_build_phase1
build-centos-kubectl:
  before_script: *id001
  image: ${DOCKER_REGISTRY}/docker:${NIGHTLY_IMAGE_TAG}
  only:
  - schedules
  script:
  - cd docker/centos/kubectl
  - docker build -t "${DOCKER_REGISTRY}/kubectl:${NIGHTLY_IMAGE_TAG}" .
  - docker push "${DOCKER_REGISTRY}/kubectl:${NIGHTLY_IMAGE_TAG}"
  services: *id002
  stage: nightly_build_phase1
build-container-cypress:
  before_script: *id001
  dependencies: []
  image: ${DOCKER_REGISTRY}/docker:${NIGHTLY_IMAGE_TAG}
  only:
  - schedules
  script:
  - docker build -t "${DOCKER_REGISTRY}/cypress:${NIGHTLY_IMAGE_TAG}" docker/cypress
  - docker push "${DOCKER_REGISTRY}/cypress:${NIGHTLY_IMAGE_TAG}"
  services: *id002
  stage: build_phase1
build-container-docker:
  before_script: *id001
  image: docker:stable
  only:
  - schedules
  script:
  - docker build -t "${DOCKER_REGISTRY}/docker:${NIGHTLY_IMAGE_TAG}" docker/docker
  - docker push "${DOCKER_REGISTRY}/docker:${NIGHTLY_IMAGE_TAG}"
  services: *id002
  stage: build_phase0
build-container-postgres:
  before_script: *id001
  dependencies: []
  image: ${DOCKER_REGISTRY}/docker:${NIGHTLY_IMAGE_TAG}
  script:
  - docker build -t "${DOCKER_REGISTRY}/postgres:${IMAGE_TAG}" docker/postgres
  - docker push "${DOCKER_REGISTRY}/postgres:${IMAGE_TAG}"
  services: *id002
  stage: build_phase1
build-container-slate:
  before_script: *id001
  image: ${DOCKER_REGISTRY}/docker:${NIGHTLY_IMAGE_TAG}
  only:
  - schedules
  script:
  - docker build -t "${DOCKER_REGISTRY}/slate:${NIGHTLY_IMAGE_TAG}" docker/slate
  - docker push "${DOCKER_REGISTRY}/slate:${NIGHTLY_IMAGE_TAG}"
  services: *id002
  stage: nightly_build_phase1
build-container-webserver:
  before_script: *id001
  dependencies:
  - build-webserver
  - build-frontend
  - build-documentation
  image: ${DOCKER_REGISTRY}/docker:${NIGHTLY_IMAGE_TAG}
  script:
  - cp services/webserver/out/webserver docker/centos/runner/executable
  - cp -r services/frontend/dist docker/centos/runner/assets
  - cp -r docker/slate/build docker/centos/runner/assets/slate
  - docker build -t "${DOCKER_REGISTRY}/webserver:${IMAGE_TAG}" --build-arg EXECUTABLE=executable
    --build-arg ASSETS=assets docker/centos/runner
  - docker push "${DOCKER_REGISTRY}/webserver:${IMAGE_TAG}"
  services: *id002
  stage: build_phase2
build-core:
  artifacts: *id004
  before_script: *id003
  dependencies: []
  image: ${DOCKER_REGISTRY}/golang:${NIGHTLY_IMAGE_TAG}
  script: *id005
  stage: build_phase1
  variables:
    ARTIFACT_NAME: core
    PROJECT_PATH: services/core
build-documentation:
  artifacts:
    paths:
    - docker/slate/build
  before_script: *id001
  dependencies: []
  image: ${DOCKER_REGISTRY}/docker:${NIGHTLY_IMAGE_TAG}
  script:
  - docker-compose -f docker/slate/docker-compose.yml run app build
  services: *id002
  stage: build_phase1
build-frontend:
  artifacts: *id006
  dependencies: []
  image: node:latest
  script: *id007
  stage: build_phase1
  variables:
    PROJECT_PATH: services/frontend
build-shell:
  before_script: *id001
  dependencies: []
  image: ${DOCKER_REGISTRY}/docker:${NIGHTLY_IMAGE_TAG}
  script:
  - docker build -t "${DOCKER_REGISTRY}/shell:${IMAGE_TAG}" docker/shell
  - docker push "${DOCKER_REGISTRY}/shell:${IMAGE_TAG}"
  services: *id002
  stage: build_phase1
build-webserver:
  artifacts: *id004
  before_script: *id003
  dependencies: []
  image: ${DOCKER_REGISTRY}/golang:${NIGHTLY_IMAGE_TAG}
  script: *id005
  stage: build_phase1
  variables:
    ARTIFACT_NAME: webserver
    PROJECT_PATH: services/webserver
deploy_prod:
  dependencies: []
  environment:
    name: production
    url: https://1git.io
  image: ${DOCKER_REGISTRY}/kubectl
  only:
  - master
  script:
  - mkdir infrastructure/k8sconfigs_processed
  - "for file in infrastructure/k8sconfigs/*; do\n  envsubst < \"${file}\" > \"infrastructure/k8sconfigs_processed/$(basename\
    \ \"${file}\")\"\ndone\n"
  - kubectl -n staging apply -f infrastructure/k8sconfigs_processed
  stage: deploy
global-linting:
  before_script: *id003
  dependencies: []
  image: $DOCKER_REGISTRY/golang-linter:${NIGHTLY_IMAGE_TAG}
  script:
  - gometalinter.v2 ./... --vendor
  stage: build_phase1
retag-container-builder:
  before_script: *id001
  dependencies: []
  image: ${DOCKER_REGISTRY}/docker:${NIGHTLY_IMAGE_TAG}
  only:
  - schedules
  script: *id008
  services: *id002
  stage: retag_phase1
  variables:
    IMAGE_NAME: golang
retag-container-cypress:
  before_script: *id001
  dependencies: []
  image: ${DOCKER_REGISTRY}/docker:${NIGHTLY_IMAGE_TAG}
  only:
  - schedules
  script: *id008
  services: *id002
  stage: retag_phase1
  variables:
    IMAGE_NAME: cypress
retag-container-docker:
  before_script: *id001
  dependencies: []
  image: ${DOCKER_REGISTRY}/docker:${NIGHTLY_IMAGE_TAG}
  only:
  - schedules
  script: *id008
  services: *id002
  stage: retag_phase1
  variables:
    IMAGE_NAME: docker
retag-container-kubectl:
  before_script: *id001
  dependencies: []
  image: ${DOCKER_REGISTRY}/docker:${NIGHTLY_IMAGE_TAG}
  only:
  - schedules
  script: *id008
  services: *id002
  stage: retag_phase1
  variables:
    IMAGE_NAME: kubectl
retag-container-linter:
  before_script: *id001
  dependencies: []
  image: ${DOCKER_REGISTRY}/docker:${NIGHTLY_IMAGE_TAG}
  only:
  - schedules
  script: *id008
  services: *id002
  stage: retag_phase1
  variables:
    IMAGE_NAME: golang-linter
retag-container-postgres:
  before_script: *id001
  dependencies: []
  image: ${DOCKER_REGISTRY}/docker:${NIGHTLY_IMAGE_TAG}
  only: *id009
  script: *id008
  services: *id002
  stage: retag_phase1
  variables:
    IMAGE_NAME: shell
retag-container-webserver:
  before_script: *id001
  dependencies: []
  image: ${DOCKER_REGISTRY}/docker:${NIGHTLY_IMAGE_TAG}
  only: *id009
  script: *id008
  services: *id002
  stage: retag_phase1
  variables:
    IMAGE_NAME: webserver
stages:
- build_phase0
- nightly_build_phase1
- build_phase1
- build_phase2
- test_phase1
- retag_phase1
- deploy
test-e2e-cypress:
  artifacts:
    expire_in: 1 week
    paths:
    - tests/cypress/screenshots
    - tests/cypress/videos
    when: always
  before_script: *id001
  dependencies: []
  image: ${DOCKER_REGISTRY}/docker:${NIGHTLY_IMAGE_TAG}
  script:
  - docker-compose -f tests/docker-compose.yml up -d
  - docker-compose -f tests/docker-compose.yml run cypress service run --config baseUrl=http://webserver:8080
  services: *id002
  stage: test_phase1
test-shell:
  before_script: *id001
  dependencies: []
  image: ${DOCKER_REGISTRY}/docker:${NIGHTLY_IMAGE_TAG}
  script:
  - docker pull "${DOCKER_REGISTRY}/shell:${IMAGE_TAG}"
  - docker-compose -f tests/shell/docker-compose.yml up --abort-on-container-exit
  services: *id002
  stage: test_phase1
variables:
  DOCKER_REGISTRY: ${CI_REGISTRY}/1git/1git
  IMAGE_TAG: ${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_IID}
  NIGHTLY_IMAGE_TAG: latest
