before_script:
- python -V
- pip3 install --upgrade pip
- pip3 install virtualenv
- virtualenv venv
- source venv/bin/activate
cache:
  paths:
  - .cache/pip
  - venv/
image: python:latest
stages:
- test
test:
  script:
  - pip3 install -r requirements.txt
  - python3 -m nltk.downloader all
  - py.test -v --doctest-modules solutions
  stage: test
variables:
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache
