create_zip:
  artifacts:
    paths:
    - todo*.zip
  image: registry.gitlab.com/todo.txt-gnome-shell-extension/todo-txt-gnome-shell-extension/packaging:latest
  script:
  - ./tools/make_dev.sh
  stage: package
lint:
  image: node
  script:
  - npm install
  - make check
  stage: verify
stages:
- verify
- package
test:
  image: registry.gitlab.com/todo.txt-gnome-shell-extension/todo-txt-gnome-shell-extension/unit-testing:latest
  script:
  - RUNNER=xvfb-run make test
  stage: verify
variables:
  GIT_SUBMODULE_STRATEGY: normal
