.template_doxygen_HTML:
  image: alpine
  script: &id001
  - apk --no-cache add python3 doxygen git
  - pip3 install doxypypy
  - git log --graph > docs/git_graph_changelog.txt
  - git log --date=short --pretty='format:**[%cd][%h]** (%cn) %n> %s%n' > docs/git_changelog.md
  - cd docs
  - chmod 755 py_filter
  - mkdir _build
  - doxygen doxy_config
  stage: docs
.template_mod_doxy_file:
  artifacts: &id002
    expire_in: 3 hrs
    paths:
    - ./README.md
    - ./docs/doxy_config
  before_script: &id003
  - apk --no-cache add sed
  - cd docs/
  image: alpine
  stage: test
.template_pylint:
  allow_failure: true
  artifacts: &id004
    expire_in: 1 mos
    name: Pylint_Results_${CI_COMMIT_SHA}
    paths:
    - ./docs/syntax_test.md
    when: always
  image: alpine
  script: &id005
  - apk --no-cache add python3 grep
  - pip3 install pylint~=1.9.0
  - find . -iname "*.py" | xargs pylint | tee docs/syntax_test.md || if [ $? -ne 0
    ]; then echo "Fault(s) found"; else echo "Pass"; fi
  - if grep -q 'E:\|F:' docs/syntax_test.md; then exit 66; else echo "No fatal or
    error messages found"; fi
  stage: test
doxygen_manual:
  artifacts:
    expire_in: 1 mos
    name: Headless_Manual_${CI_COMMIT_TAG}_${CI_COMMIT_SHA}
    paths:
    - ./docs/_build/
  image: alpine
  script: *id001
  stage: docs
doxygen_pdf:
  allow_failure: true
  artifacts:
    expire_in: 3 mos
    name: Headless_PDF_Manual_${CI_COMMIT_TAG}_${CI_COMMIT_SHA}
    paths:
    - Headless_PDF_Manual_${CI_COMMIT_TAG}.pdf
  image: ubuntu
  only:
  - tags
  - cicd_testing
  script:
  - apt-get -y update
  - DEBIAN_FRONTEND=noninteractive apt-get -y install texlive make
  - DEBIAN_FRONTEND=noninteractive apt-get -y install texlive-latex-recommended texlive-pictures
    texlive-latex-extra
  - cd docs/_build/latex
  - make pdf
  - cp refman.pdf "../../../Headless_PDF_Manual_${CI_COMMIT_TAG}.pdf"
  stage: deploy
hashing_doxygen_manual:
  artifacts: *id002
  before_script: *id003
  except:
  - tags
  image: alpine
  script:
  - sed -i -e "s/PROJECT_NUMBER         = 4773687/PROJECT_NUMBER         = $CI_COMMIT_SHA/"
    doxy_config
  stage: test
pages:
  artifacts:
    paths:
    - public
  image: alpine
  only:
  - tags
  - cicd_testing
  script:
  - mv ./docs/_build/html/ ./public/
  stage: deploy
  variables:
    GIT_STRATEGY: none
pylint:
  allow_failure: true
  artifacts: *id004
  image: alpine
  script: *id005
  stage: test
stages:
- test
- docs
- deploy
tagging_doxygen_manual:
  artifacts: *id002
  before_script: *id003
  image: alpine
  only:
  - tags
  script:
  - echo "THIS IS A TAGGED RELEASE"
  - sed -i -e "s/PROJECT_NUMBER         = 4773687/PROJECT_NUMBER         = $CI_COMMIT_TAG/"
    doxy_config
  - cd ../
  - sed -i -e "s:/master/download?:/$CI_COMMIT_TAG/download?:" README.md
  - echo "THIS IS A TAGGED RELEASE"
  stage: test
