force-create:
  image: ruby:3.3.7
  rules:
  - if: $CI_COMMIT_BRANCH == "master"
    when: manual
  script:
  - "if [ -z \"$TEAM_NAME\" ]; then\n  echo \"TEAM_NAME variable is required. Re-run\
    \ with this variable set.\"\n  exit 1\nfi\n"
  - gem install bundler:2.4.12
  - bundle
  - bundle exec ruby retrospective.rb create --force --read-token="$GITLAB_BOT_API_TOKEN"
    --write-token="$GITLAB_WRITE_API_TOKEN" --team="$TEAM_NAME"
  stage: perform
force-update:
  image: ruby:3.3.7
  rules:
  - if: $CI_COMMIT_BRANCH == "master"
    when: manual
  script:
  - "if [ -z \"$TEAM_NAME\" ]; then\n  echo \"TEAM_NAME variable is required. Re-run\
    \ with this variable set.\"\n  exit 1\nfi\n"
  - gem install bundler:2.4.12
  - bundle
  - bundle exec ruby retrospective.rb update --force --read-token="$GITLAB_BOT_API_TOKEN"
    --write-token="$GITLAB_WRITE_API_TOKEN" --team="$TEAM_NAME"
  stage: perform
perform:
  image: ruby:3.3.7
  rules:
  - if: $CI_COMMIT_BRANCH == "master"
  script:
  - export DRY_RUN_ARG=$(if [ $DRY_RUN = "true" ]; then echo --dry-run; fi)
  - export FORCE_ARG=$(if [ $FORCE = "true" ]; then echo --force; fi)
  - export CMD_ARG=${CMD-create}
  - gem install bundler:2.4.12
  - bundle
  - bundle exec ruby retrospective.rb $CMD_ARG $FORCE_ARG $DRY_RUN_ARG --read-token="$GITLAB_BOT_API_TOKEN"
    --write-token="$GITLAB_WRITE_API_TOKEN" --all-teams
  stage: perform
stages:
- test
- perform
test:
  image: ruby:3.3.7
  rules:
  - if: $CI_PIPELINE_SOURCE != "schedule"
  script:
  - gem install bundler:2.4.12
  - bundle
  - bundle exec rspec --format=documentation
  stage: test
test_create:
  image: ruby:3.3.7
  rules:
  - if: $CI_PIPELINE_SOURCE != "schedule"
  script:
  - gem install bundler:2.4.12
  - bundle
  - bundle exec ruby retrospective.rb create --dry-run --force --read-token="$GITLAB_BOT_API_TOKEN"
    --write-token="$GITLAB_WRITE_API_TOKEN" --all-teams
  stage: test
test_update:
  image: ruby:3.3.7
  rules:
  - if: $CI_PIPELINE_SOURCE != "schedule"
  script:
  - gem install bundler:2.4.12
  - bundle
  - bundle exec ruby retrospective.rb update --dry-run --force --read-token="$GITLAB_BOT_API_TOKEN"
    --write-token="$GITLAB_WRITE_API_TOKEN" --all-teams
  stage: test
verify_projects:
  image: ruby:3.3.7
  rules:
  - if: $CI_PIPELINE_SOURCE != "schedule"
  script:
  - gem install bundler:2.4.12
  - bundle
  - bundle exec bin/verify_projects --bot-token=$GITLAB_BOT_API_TOKEN
  stage: test
