before_script:
- export GRADLE_USER_HOME=`pwd`/.gradle
build:
  artifacts:
    expire_in: 1 day
    paths:
    - build/libs/
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
    - build
    - .gradle
    policy: push
  script:
  - ./gradlew --build-cache assemble
  stage: build
cache:
  paths:
  - .gradle/wrapper
  - .gradle/caches
checkFormatting:
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
    - build
    - .gradle
    policy: pull
  script:
  - ./gradlew spotlessCheck
  stage: checkFormatting
image: mjalas/javafx
release:
  except:
  - tags
  image: registry.gitlab.com/juhani/go-semrel-gitlab:v0.13.1
  only:
  - releases
  script:
  - release changelog
  - release commit-and-tag build.gradle CHANGELOG.md
  stage: release
stages:
- versionBumpGradle
- build
- checkFormatting
- release
variables:
  GRADLE_OPTS: -Dorg.gradle.daemon=false
version:
  artifacts:
    paths:
    - build.gradle
  except:
  - tags
  image: registry.gitlab.com/juhani/go-semrel-gitlab:v0.13.1
  only:
  - releases
  script:
  - release next-version --allow-current > .next-version
  - sed -i -e "s/version '[0-9].[0-9].[0-9]'/version '$(sed 's:/:\\/:g' .next-version)'/g"
    build.gradle
  stage: versionBumpGradle
