before_script:
- pip install twine
deploy_production:
  only:
  - tags
  script:
  - python setup.py sdist
  - twine upload dist/*
  stage: deploy
  variables:
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
    TWINE_USERNAME: $PRODUCTION_USERNAME
deploy_staging:
  except:
  - tags
  script:
  - VERSION_APPEND=${CI_JOB_ID} python setup.py sdist
  - twine upload --repository-url $REPOSITORY_URL dist/*
  stage: deploy
  variables:
    TWINE_PASSWORD: $STAGING_PASSWORD
    TWINE_USERNAME: $STAGING_USERNAME
image: python:3.6-alpine
stages:
- test
- deploy
test:
  script:
  - python3 setup.py sdist
  - pip install dist/*
  - apk add git
  - python3 setup.py test
  stage: test
