build:
  artifacts:
    expire_in: 1 day
    paths:
    - ./
  script: node ./update-ws.js
  stage: build
image: node:8.9.4
mirrors-repo:
  artifacts:
    expire_in: 1 week
    paths:
    - mirrors.tar.gz
  dependencies:
  - build
  script:
  - tar -czvf mirrors.tar.gz websites.json mirrors/*
  stage: package
stages:
- build
- package
