before_script:
- apt-get update -yq
- curl -sL https://deb.nodesource.com/setup_6.x | bash -
- apt-get install -y nodejs
- apt-get install git
- apt-get install -y zip gzip tar
- npm install -g bower grunt-cli
- npm install
- bower install --allow-root --no-interactive
grunt_build:
  artifacts:
    paths:
    - ./*.zip
  script:
  - grunt
  stage: build
marketplace_deploy:
  only:
  - master
  script:
  - grunt
  - curl -F "file=@./saasdm-phoenix.zip" http://marketplace.webpich.com/api/marketplace/spa/token-$MARKETPLACE_TOKEN
  stage: deploy
stages:
- build
- test
- deploy
