.build:
  before_script:
  - go get
  - go build
  image: golang:1.25
.id_tokens:
  id_tokens:
    VAULT_ID_TOKEN:
      aud: https://vault.gitlab.net
report:
  extends:
  - .build
  - .id_tokens
  rules:
  - if: $CI_API_V4_URL == "https://ops.gitlab.net/api/v4" && $CI_COMMIT_BRANCH ==
      $CI_DEFAULT_BRANCH
  script:
  - cp oncall-settings-example.yaml ~/.oncall-settings.yaml
  - ./oncall-robot-assistant $ADD_ONCALL $DEBUG
  secrets:
    GITLAB_API_TOKEN:
      file: false
      token: $VAULT_ID_TOKEN
      vault: access_tokens/gitlab-com/gitlab-com/gl-infra/_group_access_tokens/oncall-robot-assistant/token@ci
  stage: report
  variables:
    ADD_ONCALL: add-oncall
    DEBUG: --debug
stages:
- test
- report
test:
  extends:
  - .build
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
  - go test ./... -v -cover
  stage: test
