before_script:
- pip install poetry
- poetry install --with dev
build:
  artifacts:
    paths:
    - dist/
  image: python:3.11
  script:
  - poetry build
  stage: package
cache:
  paths:
  - /root/.cache
coverage:
  allow_failure: true
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml
  coverage: /(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/
  image: python:3.11
  script:
  - poetry run pytest --cov --cov-report html:htmlcov --cov-report term --cov-report
    xml:coverage.xml --junitxml=report.xml
  stage: test
ruff:
  allow_failure: true
  image: python:3.11
  script:
  - poetry run tox -e ruff
  stage: style
stages:
- style
- test
- package
tests:
  image: python:$IMAGE
  parallel:
    matrix:
    - COMMAND:
      - py38
      IMAGE:
      - '3.8'
    - COMMAND:
      - py39
      IMAGE:
      - '3.9'
    - COMMAND:
      - py310
      IMAGE:
      - '3.10'
    - COMMAND:
      - py311
      IMAGE:
      - '3.11'
    - COMMAND:
      - py312
      IMAGE:
      - '3.12'
    - COMMAND:
      - py313
      IMAGE:
      - '3.13'
  script:
  - poetry run tox -e $COMMAND
  stage: test
