before_script:
- apt-get update -qy
- apt-get install -y rubygems ruby-dev
- npm install
cache:
  paths:
  - node_modules/
client_build:
  script:
  - npm run build
  stage: build
image: node:latest
jest:
  script:
  - npm t
  stage: test
lint:
  script:
  - npm run lint
  stage: test
production:
  only:
  - tags
  script:
  - gem install dpl
  - dpl --provider=heroku --app=thebastedo --api-key=$HEROKU_KEY
  stage: deploy
stages:
- build
- test
- deploy
staging:
  only:
  - master
  script:
  - gem install dpl
  - dpl --provider=heroku --app=staging-thebastedo --api-key=$HEROKU_KEY
  stage: deploy
