edgecast:
  dependencies:
  - generate
  environment:
    name: production
    url: http://ec.demo.digitalr00ts.com/ci-jekyll/
  image: alpine:latest
  only:
  - master
  script:
  - apk add --no-cache rsync sshpass curl openssh
  - rsync --delete -rtie "sshpass -e ssh -p22 -oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no
    -oLogLevel=ERROR" _site/ci-jekyll ${VDMS_USER}@rsync.${VDMS_STORE}.${VDMS_NUMBER}.systemcdn.net:/com.digitalr00ts.demo.ec/
  - 'curl -sSki -X PUT -H "Authorization: TOK:$VDMS_TOKEN" -H "Content-Type: application/json"
    -H "Accept: application/json" -d "{ \"MediaPath\":\"http:\/\/ec.demo.digitalr00ts.com\/ci-jekyll\/\",
    \"MediaType\":8}" https://api.edgecast.com/v2/mcc/customers/$VDMS_NUMBER/edge/purge'
  - 'curl -sSki -X PUT -H "Authorization: TOK:$VDMS_TOKEN" -H "Content-Type: application/json"
    -H "Accept: application/json" -d "{ \"MediaPath\":\"http:\/\/ec.demo.digitalr00ts.com\/ci-jekyll\/\",
    \"MediaType\":3}" https://api.edgecast.com/v2/mcc/customers/$VDMS_NUMBER/edge/purge'
  stage: deploy
  when: manual
generate:
  artifacts:
    expire_in: 1 week
    paths:
    - _site/
    when: on_success
  image: digitalr00tsdemo/ruby-jekyll
  script:
  - jekyll doctor
  - jekyll build --verbose --baseurl '/ci-jekyll' --destination _site/ci-jekyll
  stage: build
html_verify:
  dependencies:
  - generate
  image: digitalr00tsdemo/ruby-jekyll
  script:
  - htmlproofer _site --check-html --allow-hash-href --empty-alt-ignore --disable-external
  stage: test
pages:
  artifacts:
    paths:
    - public
  dependencies:
  - generate
  environment:
    name: staging
    url: http://${CI_PROJECT_NAMESPACE}.gitlab.io/${CI_PROJECT_NAME}/
  image: alpine:latest
  only:
  - master
  script:
  - cp -av _site/ci-jekyll/ public
  stage: delivery
spell_check:
  dependencies:
  - generate
  image: alpine:latest
  script:
  - apk add --no-cache hunspell hunspell-en coreutils
  - for file in $(find _site/ -name \*.html | awk '/_site\/(posts|tags|categories|collections|sitemap)\/index.html/'
    ); do hunspell -u3 -d en_US -p custom.dic -H $file | tee -a spellcheck.log; done;
    test ! -s spellcheck.log
  stage: test
stages:
- build
- test
- delivery
- deploy
