jupyter-build:
  artifacts:
    paths:
    - _build/
  image: python:slim
  script:
  - pip install -U jupyter-book
  - jupyter-book build .
  stage: build
pages:
  artifacts:
    paths:
    - public
  image: busybox:latest
  only:
  - book
  script:
  - mv _build/html public
  stage: deploy
stages:
- build
- deploy
