image: python:2-alpine
stages:
- test
- build
tests:
  script: pip install pytest==3.0.5 && py.test simple_lib/tests/ -v
  stage: test
wheel:
  artifacts:
    expire_in: 1 week
    paths:
    - dist/
  script: python setup.py bdist_wheel
  stage: build
