before_script:
- echo "Before script execution"
cache:
  paths:
  - __pycache__
  - .pytest_cache
conda_package:
  environment:
    name: staging-conda
    url: https://anaconda.org/PLAnT/plant
  image: continuumio/miniconda3:latest
  only:
  - stable
  script:
  - cd conda
  - /opt/conda/bin/conda config --set anaconda_upload yes
  - /opt/conda/bin/conda config --show channels
  - /opt/conda/bin/conda config --prepend channels conda-forge
  - /opt/conda/bin/conda config --remove channels defaults
  - /opt/conda/bin/conda config --append channels nodefaults
  - /opt/conda/bin/conda config --set channel_priority strict
  - /opt/conda/bin/conda config --show channels
  - conda install conda-build anaconda-client -c conda-forge
  - /opt/conda/bin/conda build --token $ANACONDA_TOKEN --output-folder . .
  stage: deploy
create_website_pages:
  artifacts:
    paths:
    - website/
  image: registry.gitlab.com/plant/plant/no_plant:latest
  only:
  - stable
  script:
  - export PREV_DIR=$(pwd)
  - cd ..
  - export PYTHONPATH=$(pwd)
  - cd $PREV_DIR/website/scripts/
  - bash dump_posts
  - bash dump_notebooks
  stage: create_doc
docker_image:
  environment:
    name: staging-docker
    url: https://gitlab.com/plant/plant
  image: docker:git
  only:
  - stable
  script:
  - docker login -u $BOT_USER -p $BOT_PASS registry.gitlab.com
  - docker build --build-arg DOCKER_TOKEN_USER=${DOCKER_TOKEN_USER} --build-arg DOCKER_TOKEN_PASS=${DOCKER_TOKEN_PASS}
    -t registry.gitlab.com/plant/plant .
  - docker push registry.gitlab.com/plant/plant
  - docker logout registry.gitlab.com
  services:
  - docker:dind
  stage: deploy-docker
stages:
- create_doc
- deploy
- deploy-docker
