.prepare_nightly:
  cache:
  - key:
      files:
      - Cargo.lock
    paths:
    - target
  script:
  - echo 'Running nightly preparation...'
  - rustup install nightly
  - rustup default nightly
  - rustup default > .toolchain
.prepare_stable:
  cache:
  - key:
      files:
      - Cargo.lock
    paths:
    - target
  script:
  - echo 'Running stable preparation...'
  - rustup update
  - rustup default > .toolchain
build_nightly:
  extends: .prepare_nightly
  needs:
  - test_nightly
  script:
  - echo 'Building nightly release...'
  - cargo build --release
  stage: build
build_stable:
  artifacts:
    name: kyanite
    paths:
    - target/release/kyanite
  extends: .prepare_stable
  needs:
  - test_stable
  script:
  - echo 'Building stable release...'
  - cargo build --release
  stage: build
crates_io:
  needs:
  - build_stable
  only:
  - tags@lu-ci/kyanite
  script:
  - echo 'Publishing to crates.io...'
  - cargo publish --token "$CRATES_IO_API_TOKEN"
  stage: publish
image: rust:latest
stages:
- test
- build
- publish
test_nightly:
  extends: .prepare_nightly
  script:
  - echo 'Running nightly checks...'
  - cargo check
  - echo 'Running nightly tests...'
  - cargo test
  - echo 'Running nightly clippy...'
  - rustup component add clippy-preview
  - cargo clippy
  stage: test
test_stable:
  extends: .prepare_stable
  script:
  - echo 'Running stable checks...'
  - cargo check
  - echo 'Running stable tests...'
  - cargo test
  - echo 'Running stable clippy...'
  - rustup component add clippy-preview
  - cargo clippy
  stage: test
