build:
  artifacts:
    expire_in: 1 hour
    paths:
    - public
  script:
  - echo Build my page
  stage: build
  tags:
  - nginx
  - review-apps
  - deploy
production:
  environment:
    name: production
    url: http://production.$APPS_DOMAIN
  only:
  - master
  script:
  - rsync -av --delete public /srv/nginx/pages/production
  stage: production
  tags:
  - nginx
  - review-apps
  - deploy
  when: manual
review:
  environment:
    name: review/$CI_COMMIT_REF_NAME
    on_stop: stop_review
    url: http://$CI_COMMIT_REF_SLUG.$APPS_DOMAIN
  except:
  - master
  only:
  - branches
  script:
  - rsync -av --delete public /srv/nginx/pages/$CI_COMMIT_REF_SLUG
  stage: review
  tags:
  - nginx
  - review-apps
  - deploy
stages:
- build
- review
- staging
- production
staging:
  environment:
    name: staging
    url: http://staging.$APPS_DOMAIN
  only:
  - master
  script:
  - rsync -av --delete public /srv/nginx/pages/staging
  stage: staging
  tags:
  - nginx
  - review-apps
  - deploy
stop_review:
  environment:
    action: stop
    name: review/$CI_COMMIT_REF_NAME
  script:
  - rm -rf public /srv/nginx/pages/$CI_COMMIT_REF_SLUG
  stage: review
  tags:
  - nginx
  - review-apps
  - deploy
  variables:
    GIT_STRATEGY: none
  when: manual
