image: library/node:9.11.1
install:
  artifacts:
    paths:
    - node_modules
  script: npm i
  stage: setup
lint:
  script: npm run lint
  stage: build
pages:
  artifacts:
    paths:
    - public
  only:
  - master
  script:
  - cp -r dist public
  stage: deploy
stages:
- setup
- build
- deploy
webPackBuild:
  artifacts:
    paths:
    - dist
  script:
  - npm run build
  stage: build
