build:
  artifacts:
    paths:
    - dist/
  image: node:14
  only:
  - master
  script:
  - npm install
  - npm run jison
  - npm run lint
  - npm run build
  stage: build
deploy:
  environment: production
  image: kroniak/ssh-client
  only:
  - master
  script:
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$PRIVATE_KEY")
  - scp -r dist/* $SERVER_USER@$SERVER_HOST:$APP_PATH
  stage: deploy
stages:
- build
- deploy
