delete-cluster:
  before_script:
  - set -o pipefail
  - export GCLOUD_CLUSTER=${CI_PROJECT_NAME//./-}
  - echo $GCLOUD_SERVICE_KEY | base64 -d > ${HOME}/gcloud-service-key.json
  - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
  - gcloud container clusters get-credentials $GCLOUD_CLUSTER --zone $GCLOUD_ZONE
    --project $GCLOUD_PROJECT
  image: registry.gitlab.com/demo-clusters/gcloud-kubectl-helm
  script:
  - gcloud container clusters delete $GCLOUD_CLUSTER
  stage: cleanup
  when: manual
helm-delete:
  before_script:
  - set -o pipefail
  - export HELM_RELEASE_NAME=${CI_PROJECT_NAME%%.*}
  - export GCLOUD_CLUSTER=${CI_PROJECT_NAME//./-}
  - echo $GCLOUD_SERVICE_KEY | base64 -d > ${HOME}/gcloud-service-key.json
  - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
  - gcloud container clusters get-credentials $GCLOUD_CLUSTER --zone $GCLOUD_ZONE
    --project $GCLOUD_PROJECT
  - helm init --upgrade
  - kubectl rollout status -n kube-system -w "deployment/tiller-deploy"
  image: registry.gitlab.com/demo-clusters/gcloud-kubectl-helm
  script:
  - helm delete $HELM_RELEASE_NAME
  stage: cleanup
  when: manual
helm-upgrade:
  before_script:
  - set -o pipefail
  - export HELM_RELEASE_NAME=${CI_PROJECT_NAME%%.*}
  - export GCLOUD_CLUSTER=${CI_PROJECT_NAME//./-}
  - echo $GCLOUD_SERVICE_KEY | base64 -d > ${HOME}/gcloud-service-key.json
  - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
  - gcloud container clusters get-credentials $GCLOUD_CLUSTER --zone $GCLOUD_ZONE
    --project $GCLOUD_PROJECT || (gcloud components install alpha && gcloud alpha
    container clusters create $GCLOUD_CLUSTER --num-nodes=1 --enable-autoscaling --min-nodes=1
    --max-nodes=3 --machine-type=n1-highmem-4 --zone $GCLOUD_ZONE --project $GCLOUD_PROJECT
    && gcloud container clusters get-credentials $GCLOUD_CLUSTER --zone $GCLOUD_ZONE
    --project $GCLOUD_PROJECT)
  - helm init --upgrade --force-upgrade
  - kubectl rollout status -n kube-system -w "deployment/tiller-deploy"
  - helm repo add gitlab https://charts.gitlab.io
  image: registry.gitlab.com/demo-clusters/gcloud-kubectl-helm
  script:
  - helm upgrade -i $HELM_RELEASE_NAME -f values.yaml --set gitlabEELicense=$GITLAB_LICENSE
    --set baseDomain=$CI_PROJECT_NAME gitlab/kubernetes-gitlab-demo
  stage: deploy
stages:
- deploy
- cleanup
