.docker:
  image: docker:git
  script: &id001
  - ./docker/build "${CI_REGISTRY_IMAGE}:${IMAGE}" docker/${IMAGE}/Dockerfile
  services: &id002
  - docker:dind
  stage: docker
deploy:
  before_script:
  - ruby --version
  - gem --version
  - bundle --version
  - bundle config set path vendor
  - bundle install --retry=3 --jobs=$(nproc)
  cache:
    paths:
    - vendor
  environment:
    name: production
    url: https://inko-lang.org
  image: registry.gitlab.com/inko-lang/website:ruby
  only:
  - main@inko-lang/website
  script:
  - rake deploy
  stage: deploy
  variables:
    AWS_DEFAULT_REGION: eu-west-1
    BUCKET: inko-lang.org
    DISTRIBUTION_ID: E2461OP4YFCUOQ
docker:ruby:
  except:
  - schedules
  image: docker:git
  only:
    changes:
    - docker/ruby/Dockerfile
    - docker/build
    refs:
    - main
  script: *id001
  services: *id002
  stage: docker
  variables:
    IMAGE: ruby
lint:vale:
  before_script:
  - vale --version
  except:
  - schedules
  image: registry.gitlab.com/inko-lang/development-docker-images:vale
  only:
    changes:
    - source/**/*.html.md
  script:
  - vale --no-wrap --sort source/
  stage: lint
sponsors:
  before_script:
  - ruby --version
  - gem --version
  - bundle --version
  - bundle config set path vendor
  - bundle install --retry=3 --jobs=$(nproc)
  cache:
    paths:
    - vendor
  environment:
    name: production
    url: https://inko-lang.org
  image: registry.gitlab.com/inko-lang/website:ruby
  only:
    refs:
    - schedules
    variables:
    - $UPDATE_SPONSORS
  script:
  - ./scripts/sponsors.sh
  stage: automation
stages:
- docker
- lint
- automation
- deploy
