.test:
  script: &id001
  - go fmt ./...
  - go vet ./...
  - go test ./...
  stage: test
release:
  artifacts:
    paths:
    - publish/snippet_linux
    - publish/snippet_darwin
  image: golang:1.12
  only:
  - tags
  script:
  - mkdir publish
  - GOOS=linux go build -ldflags "-X main.version=`git describe`" -o publish/snippet_linux
  - sha256sum publish/snippet_linux
  - GOOS=darwin go build -ldflags "-X main.version=`git describe`" -o publish/snippet_darwin
  - sha256sum publish/snippet_darwin
  stage: release
stages:
- test
- release
test golang 1.11:
  image: golang:1.11
  script: *id001
  stage: test
test golang 1.12:
  image: golang:1.12
  script: *id001
  stage: test
variables:
  GO111MODULES: 'on'
