.build:
  image: registry.gitlab.com/i-am-root/drupal-builder:latest
  script: &id001
  - echo "Build for demo purpose"
  stage: build
.docker-package:
  script: &id002
  - echo ${VERSION}
  - tar --exclude="./deployment" -czf deployment/docker/app/package.tar.gz .
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  - docker build -t $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA} ./deployment/docker/app
  - docker push $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA}
  stage: package
  tags: &id003
  - dockerbuild
.k8s-deploy:
  environment: &id004
    name: develop
  image: alpine
  script: &id005
  - apk add --no-cache curl
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - mv ./kubectl /usr/local/bin/kubectl
  - kubectl config set-cluster nosebit --server="$KUBE_URL" --insecure-skip-tls-verify=true
  - kubectl config set-credentials admin --username="$KUBE_USER" --password="$KUBE_PASSWORD"
  - kubectl config set-context default --cluster=nosebit --user=admin
  - kubectl config use-context default
  - sed -i 's/master/'"${CI_COMMIT_REF_SLUG}"'/g' ./deployment/k8s/namespace.yml
  - sed -i 's/master/'"${CI_COMMIT_REF_SLUG}"'/g' ./deployment/k8s/pvc.yml
  - sed -i 's/master/'"${CI_COMMIT_REF_SLUG}"'/g' ./deployment/k8s/mysql.yml
  - sed -i 's/master/'"${CI_COMMIT_REF_SLUG}"'/g' ./deployment/k8s/drupal.yml
  - sed -i 's@'"${CI_REGISTRY_IMAGE}:latest"'@'"${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA}"'@g'
    ./deployment/k8s/drupal.yml
  - kubectl apply -f ./deployment/k8s/namespace.yml
  - kubectl apply -f ./deployment/k8s/pvc.yml
  - kubectl apply -f ./deployment/k8s/mysql.yml
  - kubectl apply -f ./deployment/k8s/drupal.yml
  stage: deploy
.unami-build:
  image: registry.gitlab.com/i-am-root/drupal-builder:latest
  only:
  - master
  - /^release.*$/
  - /^feature.*$/
  - /^hotfix.*$/
  script: *id001
  stage: build
docker-package-ephemeral:
  only:
  - master
  - /^release.*$/
  - /^feature.*$/
  - /^hotfix.*$/
  script: *id002
  stage: package
  tags: *id003
image: docker:git
k8s-deploy-ephemeral:
  environment: *id004
  image: alpine
  only:
  - master
  - /^release.*$/
  - /^feature.*$/
  - /^hotfix.*$/
  script: *id005
  stage: deploy
  when: manual
services:
- docker:dind
stages:
- build
- package
- deploy
