cmake_hello:
  script:
  - cd hello-world
  - mkdir build && cd build
  - cmake .. && make && find .
  - ./hello
  stage: build
image: registry.gitlab.com/volviq/cmake-testing:latest
stages:
- build
- test
