build:
  script:
  - cp .env.example .env
  - composer install
  - php artisan key:generate
  stage: build
deploy_117:
  environment:
    name: CCMRC117
    url: http://117.exvps.ca
  only:
  - master
  script:
  - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - ~/.composer/vendor/bin/envoy run deploy_117 --commit="$CI_COMMIT_SHA"
  stage: deploy
  when: manual
deploy_227:
  environment:
    name: CCMRC227
    url: http://227.exvps.ca
  only:
  - master
  script:
  - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - ~/.composer/vendor/bin/envoy run deploy_227 --commit="$CI_COMMIT_SHA"
  stage: deploy
  when: manual
deploy_697:
  environment:
    name: escadron697
    url: http://escadron697.ca
  only:
  - master
  script:
  - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - ~/.composer/vendor/bin/envoy run deploy_697 --commit="$CI_COMMIT_SHA"
  stage: deploy
  when: manual
deploy_736:
  environment:
    name: escadron736
    url: http://736.exvps.ca
  only:
  - master
  script:
  - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - ~/.composer/vendor/bin/envoy run deploy_736 --commit="$CI_COMMIT_SHA"
  stage: deploy
  when: manual
deploy_dev:
  environment:
    name: dev
    url: http://dev.exvps.ca
  only:
  - dev
  script:
  - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - ~/.composer/vendor/bin/envoy run deploy_dev --commit="$CI_COMMIT_SHA"
  stage: deploy
  when: manual
image: registry.gitlab.com/thegamecraft/c-cms:latest
services:
- mysql:5.7
stages:
- build
- test
- deploy
unit_test:
  script:
  - cp .env.example .env
  - composer install
  - php artisan key:generate
  - php artisan migrate
  - php artisan db:seed
  - vendor/bin/phpunit
  stage: test
variables:
  DB_HOST: mysql
  DB_USERNAME: root
  MYSQL_DATABASE: ddb
  MYSQL_ROOT_PASSWORD: password
