cache:
  paths:
  - .m2/repository
  - target
compile:
  script: mvn $MAVEN_CLI_OPTS clean compile
  stage: compile
image: maven:3.3.9-jdk-8
package:
  artifacts:
    paths:
    - target/*.jar
  script: mvn $MAVEN_CLI_OPTS package
  stage: package
stages:
- compile
- test
- package
test:
  script: mvn $MAVEN_CLI_OPTS test
  stage: test
variables:
  MAVEN_CLI_OPTS: --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true
    -DdeployAtEnd=true
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
    -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true
