copy-env:
  script:
  - export REMOTE_PATH="/home/gitlab-runner/go/src/gitlab.com/eunleem/gopack"
  - mkdir -p $REMOTE_PATH
  - rm -rf ./.git
  - cp -r ./ $REMOTE_PATH
  stage: copy
print-env:
  script:
  - whoami
  - pwd
  - echo $PATH
  - export CUR_PATH=$(pwd)
  stage: check
stages:
- check
- copy
