analyze:lint:
  dependencies:
  - install
  image: node:11
  only:
  - develop
  script:
  - yarn lint
  stage: analyze
build:
  allow_failure: false
  artifacts:
    expire_in: 1 day
    paths:
    - build
  dependencies:
  - pre-build
  image: node:11
  only:
  - develop
  - master
  script:
  - yarn
  - yarn build
  stage: build
cache:
  paths:
  - node_modules/
  - yarn.lock
dev:deploy:
  allow_failure: false
  dependencies:
  - build
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  only:
  - develop
  script:
  - aws s3 sync ./build/ s3://dev.admin.socrates-conference.de/admin --acl public-read
    --delete
  stage: deploy
install:
  artifacts:
    expire_in: 1 hour
    paths:
    - node_modules
    - coverage
    - .nyc_output
  image: node:11
  script:
  - yarn
  - mkdir coverage
  - mkdir .nyc_output
  stage: install
pre-build:
  artifacts:
    expire_in: 1 hour
    paths:
    - src/config.ts
  only:
  - develop
  - master
  script:
  - sed -i -e 's/%jwtsecret%/'"$JWT_SECRET_DEV"'/g' src/config.ts
  stage: pre-build
prod:deploy:
  allow_failure: false
  dependencies:
  - build
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  only:
  - master
  script:
  - aws s3 sync ./build/ s3://admin.socrates-conference.de/admin --acl public-read
    --delete
  stage: deploy
stages:
- install
- analyze
- test
- coverage
- pre-build
- build
- deploy
test:unit:
  artifacts:
    expire_in: 1 hour
    paths:
    - node_modules
    - coverage
    - .nyc_output
  dependencies:
  - install
  image: node:11
  script:
  - yarn test:coverage
  stage: test
