expected-compiles:
  script:
  - ci/test-expected.sh
  stage: test
image: mstrasuns/ubuntu-dlang:2.081
samples:
  artifacts:
    expire_in: 1 week
    paths:
    - cov/source-*.lst
  coverage: /is \d+\.\d+% covered/
  script:
  - ci/test-samples.sh
  stage: test
stages:
- test
unittest:
  script:
  - dub test
  stage: test
variables:
  GIT_SUBMODULE_STRATEGY: recursive
