image: node:18-alpine
include:
- template: Security/SAST.gitlab-ci.yml
- template: Jobs/Code-Quality.gitlab-ci.yml
pages:
  artifacts:
    paths:
    - public
  cache:
    paths:
    - node_modules/
  only:
  - master
  script:
  - npm i hexo-cli -g
  - test -e package.json && npm install
  - node server/index.js
  - hexo deploy
sast:
  stage: test
stages:
- test
