build:
  artifacts:
    paths:
    - Sbatman.Networking/bin/Release
    - Sbatman.Networking/bin/Debug
  image: microsoft/dotnet:latest
  script:
  - cd Sbatman.Networking
  - dotnet build -c release
  stage: build
nuget:
  artifacts:
    paths:
    - Sbatman.Networking/bin/Release
    - Sbatman.Networking/bin/Debug
  image: microsoft/dotnet:latest
  only:
  - master
  script:
  - cd Sbatman.Networking
  - dotnet pack -c release
  - cd bin/release/
  - dotnet nuget push *.nupkg -k $NUGETKEY -s https://api.nuget.org/v3/index.json
  stage: publish
stages:
- build
- publish
variables:
  DOCKER_DRIVER: overlay2
