.android-build:
  artifacts:
    expire_in: 1 week
    paths:
    - build-android/OpenTodoList*.apk
    - build-android/OpenTodoList*.aab
  image: $ANDROID_IMAGE
  script:
  - df -h
  - ci/android-cmake-build.sh
  - df -h
  stage: build
.fedora:
  image: fedora
  script: ./ci/fedora-build.sh
  services:
  - alias: nextcloud
    name: $NEXTCLOUD_IMAGE
  - alias: owncloud
    name: $OWNCLOUD_IMAGE
  stage: build
  variables:
    OPENTODOLIST_WEBDAV_TEST_SERVERS: $OPENTODOLIST_WEBDAV_TEST_SERVERS_TEMPLATE
.snap::upload:
  allow_failure: true
  image: $DOCKER_IMAGE
  needs:
  - snap::build
  script:
  - docker pull $SNAPCRAFT_IMAGE
  - docker run --rm -v $PWD:/project -e SNAPCRAFT_STORE_CREDENTIALS="$SNAPCRAFT_STORE_CREDENTIALS"
    $SNAPCRAFT_IMAGE upload opentodolist*.snap --release $SNAPCRAFT_CHANNEL
  services:
  - $DOCKER_DIND_IMAGE
  stage: deploy
android_arm64_v8a:
  extends: .android-build
  variables:
    ANDROID_ABIS: arm64-v8a
android_armv7:
  extends: .android-build
  variables:
    ANDROID_ABIS: armeabi-v7a
android_x64:
  extends: .android-build
  variables:
    ANDROID_ABIS: x86_64
android_x86:
  extends: .android-build
  variables:
    ANDROID_ABIS: x86
appimage:
  artifacts:
    expire_in: 1 week
    paths:
    - build-ubuntu/OpenTodoList-*-x86_64.AppImage*
  image: $UBUNTU_IMAGE
  script:
  - ci/ubuntu-build.sh
  services:
  - alias: nextcloud
    name: $NEXTCLOUD_IMAGE
  - alias: owncloud
    name: $OWNCLOUD_IMAGE
  stage: build
  variables:
    OPENTODOLIST_WEBDAV_TEST_SERVERS: $OPENTODOLIST_WEBDAV_TEST_SERVERS_TEMPLATE
appstore:
  image: macos-14-xcode-15
  needs:
  - ios
  script:
  - xcrun altool --upload-app --type ios --file ./build-ios-cmake/OpenTodoList.ipa/OpenTodoList.ipa
    -u "$APPSTORE_USER" -p "$APPSTORE_PASSWORD"
  stage: deploy
  tags:
  - saas-macos-medium-m1
  when: manual
appstore-macos:
  image: macos-14-xcode-15
  needs:
  - macos
  script:
  - xcrun altool --upload-package build-macos/dist-store/OpenTodoList-signed.pkg -u
    martin@rpdev.net  -p "$OPENTODOLIST_STORE_KEY" --type macos --apple-id 1490013766
    --bundle-id net.rpdev.OpenTodoList --bundle-version $(cat version.txt | cut -d
    '.' -f1).$(cat version.txt | cut -d '.' -f2).$CI_PIPELINE_IID --bundle-short-version-string
    $(cat version.txt)
  stage: deploy
  tags:
  - saas-macos-medium-m1
  when: manual
archlinux-pkgbuild:
  allow_failure: true
  artifacts:
    expire_in: 1 week
    paths:
    - build-arch/opentodolist-*.pkg.tar.zst
    - build-arch/.SRCINFO
    when: always
  image: archlinux
  script:
  - ci/archlinux-pkgbuild.sh
  stage: build
aur_release:
  image: fedora
  needs:
  - aur_release_check
  - archlinux-pkgbuild
  script:
  - ci/update-aur.sh
  stage: deploy
  variables:
    RELEASE_TO_AUR: 1
  when: manual
aur_release_check:
  image: fedora
  needs:
  - archlinux-pkgbuild
  script:
  - ci/update-aur.sh
  stage: build
cache:
  key: $CI_JOB_NAME
  paths:
  - $CCACHE_DIR
clang-format:
  image: fedora
  script:
  - ci/clang-format.sh
  stage: build
cppcheck:
  image: fedora
  script:
  - ci/cppcheck.sh
  stage: build
cpplint:
  image: fedora
  script:
  - ci/cpplint.sh
  stage: build
download_translations:
  image: $UBUNTU_IMAGE
  rules:
  - if: $OPENTODOLIST_DOWNLOAD_TRANSLATIONS == '1'
  - allow_failure: true
    if: $CI_COMMIT_BRANCH == 'development'
    when: manual
  script: ./ci/download_translations.sh
  stage: prepare
export-sources:
  artifacts:
    expire_in: 1 week
    paths:
    - OpenTodoList-Source-*.zip
    - OpenTodoList-Source-*.tar.gz
  image: fedora
  script:
  - ci/export-sources.sh
  stage: build
fedora-cmake:
  extends: .fedora
fedora-cmake-system-libs:
  extends: .fedora
  variables:
    SYSTEM_LIBS: '1'
flatpak:
  artifacts:
    expire_in: 1 week
    paths:
    - fp-repo
  cache:
    key: $CI_JOB_NAME
    paths:
    - .flatpak-builder/ccache/
  image: $FLATPAK_IMAGE
  script:
  - ci/flatpak-build.sh
  stage: build
github:
  image: fedora
  rules:
  - if: $CI_COMMIT_TAG
    when: manual
  script:
  - yum install -y --nogpgcheck python3 python3-requests
  - mkdir uploads
  - cp build-ubuntu/OpenTodoList-*-x86_64.AppImage uploads
  - cp deploy-win64/OpenTodoList-*-Windows-64bit.exe uploads
  - cp deploy-win64/OpenTodoList-*-Windows-64bit.zip uploads
  - cp build-android/*.apk uploads
  - cp build-macos/app/OpenTodoList.dmg uploads
  - cp OpenTodoList-Source-*.zip uploads
  - cp OpenTodoList-Source-*.tar.gz uploads
  - cp *.snap uploads || /bin/true
  - ./ci/github-upload.py mhoeher opentodolist $CI_COMMIT_REF_NAME $GITHUB_ACCESS_TOKEN
    ./uploads/*
  stage: deploy
include:
- template: Workflows/Branch-Pipelines.gitlab-ci.yml
ios:
  artifacts:
    expire_in: 1 week
    paths:
    - ./build-ios-cmake/OpenTodoList.ipa/OpenTodoList.ipa
  script:
  - ci/ios-cmake-build.sh
  stage: build
  tags:
  - macos
  when: manual
macos:
  artifacts:
    expire_in: 1 week
    paths:
    - build-macos/app/OpenTodoList.dmg
    - build-macos/dist-store/OpenTodoList-signed.pkg
  script:
  - ci/macos-build.sh
  stage: build
  tags:
  - macos
  when: manual
playstore:
  image: fedora
  needs:
  - android_armv7
  - android_arm64_v8a
  - android_x86
  - android_x64
  script:
  - ci/upload-to-play-store.sh
  stage: deploy
  when: manual
snap::build:
  allow_failure: true
  artifacts:
    expire_in: 1 week
    paths:
    - opentodolist*.snap
  image: $DOCKER_IMAGE
  needs:
  - appimage
  script:
  - docker pull $SNAPCRAFT_IMAGE
  - docker run --rm -v $PWD:/project $SNAPCRAFT_IMAGE snap
  services:
  - $DOCKER_DIND_IMAGE
  stage: build
snap::edge:
  extends: .snap::upload
  variables:
    SNAPCRAFT_CHANNEL: edge
stages:
- prepare
- build
- deploy
upload_translations:
  image: $UBUNTU_IMAGE
  rules:
  - allow_failure: true
    if: $CI_COMMIT_BRANCH == 'development'
  script: ./ci/upload_translations.sh
  stage: deploy
variables:
  ANDROID_IMAGE: registry.gitlab.com/rpdev/docker/qt6-android:$QT_VERSION
  ANDROID_MIN_SDK_INT: 23
  CCACHE_DIR: $CI_PROJECT_DIR/ccache
  CTEST_OUTPUT_ON_FAILURE: 1
  DOCKER_DIND_IMAGE: docker:dind
  DOCKER_IMAGE: docker
  ErrorActionPreference: Stop
  FLATPAK_IMAGE: registry.gitlab.com/rpdev/docker/flatpak-builder-kde-qt6:6.8
  GIT_SUBMODULE_STRATEGY: recursive
  NEXTCLOUD_IMAGE: nextcloud
  OPENTODOLIST_WEBDAV_TEST_SERVERS_TEMPLATE: nextcloud://admin:admin@nextcloud/;owncloud://admin:admin@owncloud/;generic://admin:admin@nextcloud/remote.php/webdav/;generic://admin:admin@owncloud/remote.php/webdav/
  OWNCLOUD_IMAGE: owncloud
  QT_VERSION: 6.8.1
  SNAPCRAFT_IMAGE: ghcr.io/canonical/snapcraft:7_core22
  UBUNTU_IMAGE: registry.gitlab.com/rpdev/docker/qt6-ubuntu:$QT_VERSION
windows-mingw-w64:
  artifacts:
    expire_in: 1 week
    paths:
    - deploy-win64/OpenTodoList-*-Windows-64bit.exe
    - deploy-win64/OpenTodoList-*-Windows-64bit.zip
  script:
  - Start-Process -FilePath powershell -ArgumentList .\\ci\\win-build.ps1 -Wait -NoNewWindow
  stage: build
  tags:
  - saas-windows-medium-amd64
windows-mingw-w64-filecheck:
  image: fedora
  needs:
  - windows-mingw-w64
  script:
  - test -f deploy-win64/OpenTodoList-*-Windows-64bit.exe
  - test -f deploy-win64/OpenTodoList-*-Windows-64bit.zip
  stage: build
workflow:
  rules:
  - if: $CI_COMMIT_MESSAGE =~ /Update [^ ]+ \(POEditor.com\)/i
    when: never
  - if: $CI_COMMIT_MESSAGE =~ /Downloaded Translations from POEditor/i
    when: never
  - if: $CI_COMMIT_BRANCH
    when: always
  - if: $CI_COMMIT_TAG
    when: always
  - if: $CI_MERGE_REQUEST_ID
    when: never
  - when: always
