build_job:
  cache:
    key: default
    paths:
    - project/.sbt
    policy: pull
  except:
  - master
  script:
  - if $(git grep -qE "TODO|FIXME" *) ; then echo "Please remove TODO or FIXME." ;
    exit 1 ; fi
  - sbt ";+check ;+cpl ;+lint ;+test"
  - cd scalafix ; sbt tests/test
  stage: build
deploy_job:
  cache:
    key: default
    paths:
    - project/.sbt
  except:
  - tags
  only:
  - master
  script:
  - sbt ";+update;+publish"
  - cd scalafix ; sbt update
  stage: deploy
image: fommil/docker-openjdk-sbt:latest
stages:
- build
- deploy
variables:
  COURSIER_CACHE: ${CI_PROJECT_DIR}/project/.sbt/coursier
  SBT_TASK_LIMIT: '4'
