build_job:
  artifacts:
    expire_in: 20 minutes
    paths:
    - bin/
  before_script:
  - apt-get update
  - apt-get install -y make
  - apt-get install -y build-essential
  - apt-get install -y automake
  script:
  - pwd; cd ./src;
  - make seed
  stage: build
image: ubuntu:20.04
stages:
- build
- test
test_cases:
  artifacts:
    paths:
    - test_cases/bromodomains/BRD4/log
    - test_cases/bromodomains/BRD4/outputs
    - test_cases/bromodomains/CREBBP/log
    - test_cases/bromodomains/CREBBP/outputs
    - test_cases/kinase/epha3/log
    - test_cases/kinase/epha3/outputs
  script:
  - cd test_cases/bromodomains/BRD4
  - ../../../bin/seed_4 seed.inp >& log
  - cd ../../..
  - cd test_cases/bromodomains/CREBBP
  - ../../../bin/seed_4 seed.inp >& log
  - cd ../../..
  - cd test_cases/kinase/epha3
  - ../../../bin/seed_4 seed.inp >& log
  - cd ../../..
  stage: test
