codequality:
  before_script:
  - wget -nv https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz
  - tar xvJf shellcheck-stable.linux.x86_64.tar.xz
  - cp shellcheck-stable/shellcheck /usr/local/bin
  image: alpine:latest
  script:
  - shellcheck bacme
  - shellcheck test/test.sh
  stage: test
pack-release:
  artifacts:
    paths:
    - bacme-$CI_COMMIT_TAG.tar.gz
  image: alpine:latest
  only:
  - tags
  script:
  - tar cvf bacme-$CI_COMMIT_TAG.tar bacme openssl.conf README.md CHANGELOG.md EXAMPLES.md
    LICENSE.txt
  - gzip bacme-$CI_COMMIT_TAG.tar
  stage: package
pack-snapshot:
  artifacts:
    expire_in: 30 days
    paths:
    - bacme-snapshot.tar.gz
  except:
  - tags
  image: alpine:latest
  script:
  - tar cvf bacme-snapshot.tar bacme openssl.conf README.md CHANGELOG.md EXAMPLES.md
    LICENSE.txt
  - gzip bacme-snapshot.tar
  stage: package
stages:
- test
- package
tests:
  before_script:
  - zypper install -y bash openssl curl vim
  image: opensuse/leap:latest
  script:
  - cd test && ./test.sh
  stage: test
