.contributors:
  script:
  - ./.tools/contributors.sh
  - pwd
  stage: test
before_script:
- uname -a
image: debian:stable
imagemagiccheck:
  script:
  - ./.tools/imagemagiccheck.sh
  stage: test
licensecheck:
  allow_failure: true
  script:
  - ./.tools/licensecheck.sh
  stage: test
  tags:
  - lightweight
manaverse:
  artifacts:
    expire_in: 3 week
    paths:
    - shared
    when: always
  image: debian:unstable
  script:
  - ./.tools/manaplus.sh manaplus master manaverse.log
  stage: test
newlines:
  artifacts:
    expire_in: 3 week
    paths:
    - shared
    when: always
  script:
  - ./.tools/newlines.sh
  stage: test
  tags:
  - lightweight
old_manaplus:
  artifacts:
    expire_in: 3 week
    paths:
    - shared
    when: always
  image: debian:bullseye
  script:
  - ./.tools/manaplus.sh packetver24 s20180215 manaplus.log
  stage: test
pngcheck:
  script:
  - ./.tools/pngcheck.sh
  stage: test
stages:
- test
testxml:
  script:
  - ./.tools/testxml.sh
  - pwd
  stage: test
