cache:
  paths:
  - node_modules/
image: node:16
install_build:
  artifacts:
    paths:
    - node_modules/
  only:
    changes:
    - src/**/*
    - public/**/*
    refs:
    - main
  script:
  - yarn
  - yarn build
  stage: install
nixos:
  only:
    changes:
    - src/**/*
    - public/**/*
    refs:
    - main
  stage: deploy
  trigger: nix17/nixos-config
  variables:
    PACKAGE_NAME: silver_datawars2-frontend
    UPDATE_FLAKE: 'yes'
stages:
- install
- deploy
