before_script:
- pwd
- pip install -r requirements.txt
- python -m nltk.downloader all
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - /root/nltk_data/
dummydeploy:
  script:
  - echo "dummy deploy"
  stage: deploy
image: python:3.7.0-alpine
linting:
  script:
  - pycodestyle -v --benchmark sentiment.py
  stage: qa
smoketest:
  script:
  - python sentiment.py
  stage: deploy
stages:
- qa
- deploy
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375/
