build:
  artifacts:
    paths:
    - ./$CI_PROJECT_NAME.jar
  before_script:
  - source ./cicd-variables
  script:
  - find src/main/java -name "*.java" > sources.txt
  - javac -classpath "./lib/main/*" @sources.txt
  - rm sources.txt
  - 'echo -e Manifest-Version: 1.0 > MANIFEST.MF'
  - 'echo -e Created-By: DrWursterich > MANIFEST.MF'
  - 'if [[ $MAIN_CLASS != "" ]]; then echo -e Main-Class: $MAIN_CLASS >> MANIFEST.MF;
    fi'
  - "if [[ $INCLUDE_DEPENDENCIES == \"true\" ]] && [[ -d lib/main ]]; then\n  find\
    \ lib/main -name \"*.jar\" | while read file; do\n    if [ -e $file ]; then\n\
    \      unzip $file -d ./src/main/java/;\n      rm $file;\n      rm -rf ./src/main/java/META-INF;\n\
    \    fi;\n  done;\nfi\n"
  - jar -cvfm $CI_PROJECT_NAME.jar MANIFEST.MF -C src/main/java/ .
  stage: build
deploy:
  before_script:
  - source ./cicd-variables
  - apt update -y && apt install xml-twig-tools -y
  - apt-get install xsltproc -y
  only:
  - master
  script:
  - mkdir -p ~/.ssh
  - ssh-keyscan -t rsa gitlab.com > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
  - echo "$PRIVATE_SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 700 ~/.ssh/id_rsa
  - eval $(ssh-agent -s)
  - ssh-add ~/.ssh/id_rsa
  - git config --global user.name "$GITLAB_USER_LOGIN"
  - git config --global user.email "AutomatedDeployment+$GITLAB_USER_LOGIN@users.noreply.github.com"
  - "if [[ $DEPLOY == \"true\" ]]; then\n  mkdir ./$VERSION;\n  mv ./$CI_PROJECT_NAME.jar\
    \ ./$VERSION/$CI_PROJECT_NAME-$VERSION.jar;\n  git add ./$VERSION/$CI_PROJECT_NAME-$VERSION.jar;\n\
    \  git stash;\n  git checkout 'artifacts';\n  git stash pop;\nelse\n  rm ./$CI_PROJECT_NAME.jar;\n\
    \  git checkout 'artifacts';\nfi\n"
  - "if [[ $DEPLOY == \"true\" || $LOG == \"true\" ]]; then\n  RE='([^@]+)';\n  if\
    \ [[ $LOG == \"true\" && $CI_COMMIT_MESSAGE =~ $RE ]]; then\n    CHANGE=$(echo\
    \ ${BASH_REMATCH[1]} | sed -e 's/[\\n]/ /g');\n    xsltproc -novalid -stringparam\
    \ \"CHANGE\" \"${CHANGE}\" ./resources/unreleasedChanges.xsl settings.xml > newSettings.xml\
    \ && mv newSettings.xml settings.xml;\n  fi\n  if [[ $DEPLOY == \"true\" ]]; then\n\
    \    if [[ $SNAPSHOT != \"true\" ]]; then\n      xsltproc -novalid -stringparam\
    \ \"VERSION\" \"${VERSION}\" -stringparam \"DATE\" \"${DATE}\" ./resources/released.xsl\
    \ settings.xml > newSettings.xml && mv newSettings.xml settings.xml;\n    fi\n\
    \    xsltproc -novalid -stringparam \"MAJOR\" \"${MAJOR}\" -stringparam \"MINOR\"\
    \ \"${MINOR}\" -stringparam \"PATCH\" \"${PATCH}\" -stringparam \"SNAPSHOT\" \"\
    ${SNAPSHOT}\" ./resources/version.xsl settings.xml > newSettings.xml && mv newSettings.xml\
    \ settings.xml;\n    xsltproc -novalid -stringparam \"VERSION\" \"${VERSION}\"\
    \ -stringparam \"DATE\" \"${DATE}\" ./resources/changelog.xsl settings.xml > ./$VERSION/CHANGELOG.md\n\
    \    git reset;\n  fi\n  git add settings.xml;\n  git commit -m \"Updated Settings.xml\"\
    ;\n  if [[ $DEPLOY == \"true\" ]]; then\n    FILES=./*-SNAPSHOT;\n    for FILE\
    \ in $FILES; do\n      if [[ $FILE != ./$VERSION ]]; then\n        rm -rf $FILE;\n\
    \      fi\n    done\n    git add ./$VERSION/*;\n    git commit -m \"${VERSION}\
    \ automated deployment\";\n  fi\n  git push git@gitlab.com:$CI_PROJECT_PATH artifacts\n\
    fi\n"
  stage: deploy
image: java:8-jdk
initialize:
  artifacts:
    paths:
    - ./cicd-variables
  before_script:
  - apt update -y && apt install xml-twig-tools -y
  script:
  - git checkout 'artifacts'
  - MAIN_CLASS=$(xml_grep /settings/packaging/mainClass settings.xml --text_only)
  - INCLUDE_DEPENDENCIES=$(xml_grep /settings/packaging/includeDependencies settings.xml
    --text_only)
  - MAJOR=$(xml_grep /settings/latestVersion/major settings.xml --text_only)
  - MINOR=$(xml_grep /settings/latestVersion/minor settings.xml --text_only)
  - PATCH=$(xml_grep /settings/latestVersion/patch settings.xml --text_only)
  - SNAPSHOT=$(xml_grep /settings/latestVersion/snapshot settings.xml --text_only)
  - SKIP_TESTS=$(xml_grep /settings/tests/skip settings.xml --text_only)
  - TEST_SUIT=$(xml_grep /settings/tests/suit settings.xml --text_only)
  - LOG="true"
  - DEPLOY="false"
  - RE='@cicd:([a-zA-Z_, ]*$)'
  - "if [[ $CI_COMMIT_MESSAGE =~ $RE ]]; then\n  COMMANDS=${BASH_REMATCH[1]};\n  if\
    \ [[ $COMMANDS =~ execute_tests ]]; then\n    SKIP_TESTS=\"false\";\n  fi\n  if\
    \ [[ $COMMANDS =~ skip_tests ]]; then\n    SKIP_TESTS=\"true\";\n  fi\n  if [[\
    \ $COMMANDS =~ snapshot ]]; then\n    SNAPSHOT=\"true\";\n    DEPLOY=\"true\"\
    ;\n  fi\n  if [[ $COMMANDS =~ patch ]]; then\n    PATCH=$((PATCH+1));\n    SNAPSHOT=\"\
    false\";\n    DEPLOY=\"true\";\n  fi\n  if [[ $COMMANDS =~ minor ]]; then\n  \
    \  MINOR=$((MINOR+1));\n    PATCH=0;\n    SNAPSHOT=\"false\";\n    DEPLOY=\"true\"\
    ;\n  fi\n  if [[ $COMMANDS =~ major ]]; then\n    MAJOR=$((MAJOR+1));\n    MINOR=0;\n\
    \    PATCH=0;\n    SNAPSHOT=\"false\";\n    DEPLOY=\"true\";\n  fi\n  if [[ $COMMANDS\
    \ =~ no_log ]]; then\n    LOG=\"false\";\n  fi\nfi\n"
  - VERSION=${MAJOR}.${MINOR}.${PATCH}
  - "if [[ ${SNAPSHOT} == \"true\" ]]; then\n  VERSION=${VERSION}-SNAPSHOT;\nfi\n"
  - echo MAIN_CLASS=\"$MAIN_CLASS\" > ./cicd-variables
  - echo INCLUDE_DEPENDENCIES=\"$INCLUDE_DEPENDENCIES\" >> ./cicd-variables
  - echo MAJOR=\"$MAJOR\" >> ./cicd-variables
  - echo MINOR=\"$MINOR\" >> ./cicd-variables
  - echo PATCH=\"$PATCH\" >> ./cicd-variables
  - echo VERSION=\"$VERSION\" >> ./cicd-variables
  - echo SKIP_TESTS=\"$SKIP_TESTS\" >> ./cicd-variables
  - echo TEST_SUIT=\"$TEST_SUIT\" >> ./cicd-variables
  - echo LOG=\"$LOG\" >> ./cicd-variables
  - echo DEPLOY=\"$DEPLOY\" >> ./cicd-variables
  - echo DATE=\"$(date '+%Y-%m-%d')\" >> ./cicd-variables;
  stage: initialize
stages:
- initialize
- build
- test
- deploy
test:
  before_script:
  - source ./cicd-variables
  script:
  - "if [[ $SKIP_TESTS = \"true\" ]]; then\n  echo SKIPPING TESTS;\n  exit 0;\nfi\n"
  - "if [[ -d ./lib/main ]]; then\n  mv ./lib/main/* ./lib/;\nfi\n"
  - "if [[ -d ./lib/test ]]; then\n  mv ./lib/test/* ./lib/;\nfi\n"
  - find -name "*.java" > sources.txt
  - javac -classpath "./lib/*" @sources.txt
  - rm sources.txt
  - mv src/test/java/* src/main/java/
  - "if [[ -d lib ]]; then\n  find lib -name \"*.jar\" | while read file; do\n   \
    \ if [ -e $file ]; then \n      unzip $file -d ./src/main/java/; \n      rm $file;\
    \ \n      rm -rf ./src/main/java/META-INF; \n    fi; \n  done\nfi\n"
  - jar -cvf $CI_PROJECT_NAME-$VERSION-JUnit-Tests.jar -C src/main/java/ .
  - java -cp "./$CI_PROJECT_NAME-$VERSION-JUnit-Tests.jar" org.junit.runner.JUnitCore
    $TEST_SUIT
  stage: test
