before_script:
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew
build:
  artifacts:
    paths:
    - app/build/outputs/apk/app-debug.apk
  script:
  - ./gradlew assembleDebug
  stage: build
cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/
image: jangrewe/gitlab-ci-android
stages:
- build
