buid_composer:
  artifacts:
    name: public
    paths:
    - public
  image: composer:latest
  only:
  - master
  script:
  - composer install -d public/api
  stage: build_backend
build_npm:
  artifacts:
    expire_in: 5 sec
    paths:
    - public
  image: node:latest
  only:
  - master
  script:
  - npm install
  - npm run build
  stage: build_frontend
cache:
  paths:
  - node_modules/
stages:
- build_frontend
- build_backend
