build:
  artifacts:
    paths:
    - output
  only:
  - master
  script:
  - nikola build
  stage: build
build-test:
  except:
  - master
  script:
  - nikola build
  stage: build
image: paddyhack/nikola
sass-compile:
  artifacts:
    paths:
    - output
  script:
  - apk add --no-cache ruby ruby-rdoc ruby-irb ca-certificates nodejs
  - gem install sass
  - nikola plugin --install=sass
  - nikola build -s prepare_sass_sources
  - nikola build -s build_sass
  stage: compile
stages:
- setup
- compile
- build
theme-setup:
  artifacts:
    paths:
    - themes
  script:
  - apk add --no-cache nodejs
  - cd themes/bootstrap4/sass
  - npm install --unsafe-perm
  stage: setup
