image: node:6.10.3
init:
  script:
  - npm cache clean
  - rm -rf node-modules
  - npm install -g mocha
  - npm install -g istanbul
  - npm install
  stage: init
run_tests:
  script:
  - npm install -g mocha
  - npm install -g istanbul
  - npm install
  - npm test
  stage: tests
stages:
- ver
- init
- tests
version:
  script:
  - node --version
  - whoami
  stage: ver
