build_site:
  artifacts:
    paths:
    - public
  image:
    entrypoint:
    - ''
    name: ghcr.io/gohugoio/hugo:v0.147.9@sha256:4f8ddf38071c3c1c532b88712a2871d73a330be2cbc17e320f7c3a2dd0fb271a
  script:
  - git config --global --add safe.directory $CI_PROJECT_DIR
  - npm install
  - hugo
  stage: build
  variables:
    HUGO_CACHEDIR: ''
    HUGO_ENV: production
html5validator:
  image: cyb3rjak3/html5validator:pypi-v4.2.1@sha256:e67d3603b41bb5de36931cafe98589e9b6e9310ec576eae0c3cc0151dac9267e
  script:
  - tests/html_validate_test
  stage: test
hyperlinkcheck:
  image:
    entrypoint:
    - ''
    name: ghcr.io/untitaker/hyperlink:0.2.0@sha256:137b43bf966b5d3a811cb3c3298e63e02d363162729e2c3929997b546a088533
  script: hyperlink --sources content/en --check-anchors public/
  stage: test
pages:
  artifacts:
    paths:
    - public
  image:
    entrypoint:
    - ''
    name: ghcr.io/gohugoio/hugo:v0.147.9@sha256:4f8ddf38071c3c1c532b88712a2871d73a330be2cbc17e320f7c3a2dd0fb271a
  only:
  - main
  resource_group: production
  script:
  - git config --global --add safe.directory $CI_PROJECT_DIR
  - npm install
  - hugo
  - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|json\)$' -exec
    gzip --best -f -k {} \;
  stage: deploy
  variables:
    HUGO_CACHEDIR: ''
    HUGO_ENV: production
stages:
- build
- test
- deploy
