binary:debug:
  artifacts:
    paths:
    - advent
    - cheat
    - '*.o'
    - dungeon.c
    - dungeon.h
  script:
  - make debug
  stage: build
binary:release:
  artifacts:
    paths:
    - advent
    - cheat
    - '*.o'
    - dungeon.c
    - dungeon.h
  script:
  - make advent cheat
  stage: build
ci-build:
  image:
    entrypoint:
    - ''
    name: gcr.io/kaniko-project/executor:debug
  script:
  - mkdir -p /kaniko/.docker
  - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}"
    > /kaniko/.docker/config.json
  - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile.ci
    --destination $CI_REGISTRY_IMAGE:ci --cache=true
  stage: ci-build
default:
  image: $CI_REGISTRY_IMAGE:ci
dist:
  artifacts:
    paths:
    - '*.tar.gz'
  script:
  - export VERS=${CI_COMMIT_REF_NAME}
  - make dist -e
  stage: build
html:
  artifacts:
    paths:
    - '*.html'
  script:
  - make html
  stage: build
manpage:
  artifacts:
    paths:
    - advent.6
  script:
  - make advent.6
  stage: build
pages:
  artifacts:
    paths:
    - public
  dependencies:
  - test:debug
  only:
  - master
  script:
  - mkdir public
  - mv coverage public
  stage: deploy
stages:
- ci-build
- build
- test
- deploy
test:debug:
  artifacts:
    paths:
    - coverage
  dependencies:
  - binary:debug
  script:
  - make coverage
  stage: test
test:release:
  dependencies:
  - binary:release
  script:
  - cd tests
  - make
  - cd ..
  stage: test
