build:
  artifacts:
    expire_in: 1 week
    paths:
    - dist
  image: node:8.11.2-alpine
  script:
  - yarn install --progress=false
  - yarn build
  stage: build
build-example:
  artifacts:
    expire_in: 1 week
    paths:
    - example
  image: node:8.11.2-alpine
  script:
  - yarn install --progress=false
  - yarn build-example
  stage: test
pages:
  artifacts:
    paths:
    - public
  image: alpine
  only:
  - master
  script:
  - mkdir .public
  - cp -r example .public
  - mv .public public
  stage: deploy
stages:
- build
- test
- deploy
test:
  image: node:8.11.2-alpine
  script:
  - yarn install --progress=false
  - yarn test
  stage: test
