before_script:
- packer --version
build:
  environment: production
  only:
  - master
  script:
  - find . -maxdepth 1 -name '*.json' -print0 | xargs -t0n1 packer build
  stage: deploy
  when: manual
image:
  entrypoint:
  - /usr/bin/env
  - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  name: hashicorp/packer:1.0.4
stages:
- validate
- deploy
validate:
  script:
  - find . -maxdepth 1 -name '*.json' -print0 | xargs -t0n1 packer validate
  stage: validate
