build:
  artifacts:
    paths:
    - public/
  script:
  - npm run production
  stage: build
deploy_prod:
  dependencies:
  - build
  environment:
    name: production
    url: http://openplaygroundmap.de
  except:
  - branches
  only:
  - tags
  - triggers
  script:
  - apt-get update
  - apt-get install -yy lftp
  - lftp -e "mirror -eRv  $CI_PROJECT_DIR/public production; quit;" ftp://$FTP_CREDENTIALS
  stage: deploy
deploy_review:
  dependencies:
  - build
  environment:
    name: review/$CI_BUILD_REF_NAME
    on_stop: stop_review
    url: http://builds.openplaygroundmap.de/$CI_BUILD_REF_SLUG
  except:
  - master
  - tags
  script:
  - apt-get update
  - apt-get install -yy lftp
  - lftp -e "mirror -eRv  $CI_PROJECT_DIR/public builds/$CI_BUILD_REF_SLUG; quit;"
    ftp://$FTP_CREDENTIALS
  stage: deploy
deploy_staging:
  dependencies:
  - build
  environment:
    name: staging
    url: http://staging.openplaygroundmap.de/
  except:
  - tags
  only:
  - master
  script:
  - apt-get update
  - apt-get install -yy lftp
  - lftp -e "mirror -eRv  $CI_PROJECT_DIR/public staging; quit;" ftp://$FTP_CREDENTIALS
  stage: deploy
image: node:6
install:
  artifacts:
    paths:
    - node_modules/
  cache:
    key: $CI_BUILD_REF_NAME
    paths:
    - node_modules/
  script:
  - npm install --loglevel=warn
  stage: install
stages:
- install
- test
- build
- deploy
stop_review:
  environment:
    action: stop
    name: review/$CI_BUILD_REF_NAME
  except:
  - master
  - tags
  script:
  - apt-get update
  - apt-get install -yy lftp
  - lftp -e "rm -r builds/$CI_BUILD_REF_SLUG; quit;" ftp://$FTP_CREDENTIALS
  stage: deploy
  variables:
    GIT_STRATEGY: none
  when: manual
test:
  script:
  - npm test
  stage: test
