build job:
  only:
  - master
  script:
  - docker info
  - echo "$CI_BUILD_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  - DOCKER_BUILDKIT=1 docker build --pull -t $CI_REGISTRY_IMAGE:$TMPTAG -t $CI_REGISTRY_IMAGE:latest
    -t $DOCKER_REGISTRY_DOCKERHUB_REPO:$TMPTAG -t $DOCKER_REGISTRY_DOCKERHUB_REPO:latest
    .
  - docker images
  - docker push $CI_REGISTRY_IMAGE:$TMPTAG
  - docker push $CI_REGISTRY_IMAGE:latest
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    "$DOCKERHUB_REGISTRY"
  - docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:$TMPTAG
  - docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:latest
  - docker logout "$CI_REGISTRY"
  - docker logout "$DOCKERHUB_REGISTRY"
  stage: build-and-deploy
  variables:
    DOCKERHUB_REGISTRY: https://index.docker.io/v1/
    DOCKER_REGISTRY_DOCKERHUB_REPO: anacha/ng-testplat
    TMPTAG: 10.2.0-alpine
check-packages job:
  image: alpine:3.12
  script:
  - chmod +x checkpackages.sh
  - ./checkpackages.sh
  stage: check-packages
docker-hub:update-readme:
  cache: {}
  dependencies: []
  image: docker:latest
  only:
  - master
  script:
  - docker run --rm -v $(pwd)/Readme.md:/data/README.md -e DOCKERHUB_USERNAME="$DOCKERHUB_USERNAME"
    -e DOCKERHUB_PASSWORD="$DOCKERHUB_PASSWORD" -e DOCKERHUB_REPO_PREFIX="$DOCKERHUB_REPO_PREFIX"
    -e DOCKERHUB_REPO_NAME="$DOCKERHUB_REPO_NAME" sheogorath/readme-to-dockerhub
  services:
  - docker:dind
  stage: update-docker-hub-readme
  variables:
    DOCKERHUB_REPO_NAME: ng-testplat
    DOCKERHUB_REPO_PREFIX: anacha
    DOCKER_REGISTRY_DOCKERHUB_REPO: $DOCKERHUB_REPO_PREFIX/$DOCKERHUB_REPO_NAME
image: docker:git
services:
- docker:dind
stages:
- check-packages
- build-and-deploy
- git-push-to-mirror
- update-docker-hub-readme
variables:
  DOCKER_DRIVER: overlay2
