Open Merge Request:
  before_script: []
  image: tmaier/gitlab-auto-merge-request
  only:
  - /^feature\/*/
  script:
  - merge-request.sh
  stage: openMr
  variables:
    GIT_STRATEGY: none
stages:
- openMr
- otherStages
