.functions: "# Variables and functions\nfunction setup_docker() {\n  if ! docker info\
  \ &>/dev/null; then\n    if [ -z \"$DOCKER_HOST\" -a \"$KUBERNETES_PORT\" ]; then\n\
  \      export DOCKER_HOST='tcp://localhost:2375'\n    fi\n  fi\n}\n\nfunction sast()\
  \ {\n  case \"$CI_SERVER_VERSION\" in\n    *-ee)\n      # Extract \"MAJOR.MINOR\"\
  \ from CI_SERVER_VERSION and generate \"MAJOR-MINOR-stable\"\n      SAST_VERSION=$(echo\
  \ \"$CI_SERVER_VERSION\" | sed 's/^\\([0-9]*\\)\\.\\([0-9]*\\).*/\\1-\\2-stable/')\n\
  \n      docker run --env SAST_CONFIDENCE_LEVEL=\"${SAST_CONFIDENCE_LEVEL:-3}\" \\\
  \n                 --env SAST_DISABLE_REMOTE_CHECKS=\"${SAST_DISABLE_REMOTE_CHECKS:-false}\"\
  \ \\\n                 --volume \"$PWD:/code\" \\\n                 --volume /var/run/docker.sock:/var/run/docker.sock\
  \ \\\n                 \"registry.gitlab.com/gitlab-org/security-products/sast:$SAST_VERSION\"\
  \ /app/bin/run /code\n      ;;\n    *)\n      echo \"GitLab Enterprise Edition is\
  \ required\"\n      ;;\n  esac\n}\n"
codequality:
  artifacts:
    paths:
    - codeclimate.json
  image: docker:latest
  script:
  - docker pull codeclimate/codeclimate
  - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock
    --volume /tmp/cc:/tmp/cc codeclimate/codeclimate:0.69.0 init
  - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock
    --volume /tmp/cc:/tmp/cc codeclimate/codeclimate:0.69.0 analyze -f json > codeclimate.json
    || true
  services:
  - docker:dind
  stage: test
  tags:
  - dind
  variables:
    DOCKER_DRIVER: overlay2
eslint:
  script:
  - npm install
  - npm run lint
  stage: test
image: node:latest
pages:
  artifacts:
    paths:
    - public/
  only:
  - master
  script:
  - npm install
  - npm run build
  - mv dist public
  stage: deploy
sast:
  allow_failure: true
  artifacts:
    paths:
    - gl-sast-report.json
  before_script:
  - "# Variables and functions\nfunction setup_docker() {\n  if ! docker info &>/dev/null;\
    \ then\n    if [ -z \"$DOCKER_HOST\" -a \"$KUBERNETES_PORT\" ]; then\n      export\
    \ DOCKER_HOST='tcp://localhost:2375'\n    fi\n  fi\n}\n\nfunction sast() {\n \
    \ case \"$CI_SERVER_VERSION\" in\n    *-ee)\n      # Extract \"MAJOR.MINOR\" from\
    \ CI_SERVER_VERSION and generate \"MAJOR-MINOR-stable\"\n      SAST_VERSION=$(echo\
    \ \"$CI_SERVER_VERSION\" | sed 's/^\\([0-9]*\\)\\.\\([0-9]*\\).*/\\1-\\2-stable/')\n\
    \n      docker run --env SAST_CONFIDENCE_LEVEL=\"${SAST_CONFIDENCE_LEVEL:-3}\"\
    \ \\\n                 --env SAST_DISABLE_REMOTE_CHECKS=\"${SAST_DISABLE_REMOTE_CHECKS:-false}\"\
    \ \\\n                 --volume \"$PWD:/code\" \\\n                 --volume /var/run/docker.sock:/var/run/docker.sock\
    \ \\\n                 \"registry.gitlab.com/gitlab-org/security-products/sast:$SAST_VERSION\"\
    \ /app/bin/run /code\n      ;;\n    *)\n      echo \"GitLab Enterprise Edition\
    \ is required\"\n      ;;\n  esac\n}\n"
  image: docker:latest
  script:
  - setup_docker
  - sast
  services:
  - docker:dind
  stage: test
  tags:
  - dind
  variables:
    DOCKER_DRIVER: overlay2
stages:
- test
- deploy
