.ha:
  before_script: &id001
  - python -m homeassistant --version
  - mv fake_secrets.yaml secrets.yaml
  - rm packages/network_map.yaml
  script: &id002
  - "python -m homeassistant \\\n  --config $CI_PROJECT_DIR \\\n  --script check_config\
    \ \\\n  --info all\n"
  stage: homeassistant
  tags: &id003
  - hass
  variables: &id004
    PYTHONPATH: /usr/src/app:$PYTHONPATH
.preflight:
  stage: preflight
  tags: &id005
  - hass
deploy:
  after_script:
  - rm id_rsa
  before_script:
  - apk --no-cache add openssh-client
  - echo "$DEPLOYMENT_SSH_KEY" > id_rsa
  - chmod 600 id_rsa
  environment:
    name: home-assistant
  image:
    entrypoint:
    - ''
    name: alpine:latest
  needs:
  - ha-deployed
  only:
    refs:
    - master
  script:
  - ssh -i id_rsa -o "StrictHostKeyChecking=no" $DEPLOYMENT_SSH_LOGIN "cd /mnt/docker-data/home-assistant
    && git fetch && git checkout $CI_COMMIT_SHA && git submodule sync --recursive
    && git submodule update --init --recursive"
  stage: deploy
  tags:
  - hass
docker-deploy:
  after_script:
  - rm id_rsa
  before_script:
  - apk --no-cache add openssh-client
  - echo "$DEPLOYMENT_SSH_KEY" > id_rsa
  - chmod 600 id_rsa
  environment:
    name: home-assistant
  image:
    entrypoint:
    - ''
    name: alpine:latest
  needs:
  - deploy
  only:
    changes:
    - docker-compose.yml
    - update.sh
    refs:
    - master
  script:
  - ssh -i id_rsa -o "StrictHostKeyChecking=no" $DEPLOYMENT_SSH_LOGIN "cd /mnt/docker-data/home-assistant
    && ./update.sh"
  stage: docker-deploy
  tags:
  - hass
ha-deployed:
  allow_failure: false
  before_script: *id001
  image:
    entrypoint:
    - ''
    name: homeassistant/home-assistant:2022.10
  needs: []
  script: *id002
  stage: homeassistant
  tags: *id003
  variables: *id004
ha-dev:
  allow_failure: true
  before_script: *id001
  image:
    entrypoint:
    - ''
    name: homeassistant/home-assistant:dev
  needs: []
  script: *id002
  stage: homeassistant
  tags: *id003
  variables: *id004
ha-latest:
  allow_failure: true
  before_script: *id001
  image:
    entrypoint:
    - ''
    name: homeassistant/home-assistant:latest
  needs: []
  script: *id002
  stage: homeassistant
  tags: *id003
  variables: *id004
ha-rc:
  allow_failure: true
  before_script: *id001
  image:
    entrypoint:
    - ''
    name: homeassistant/home-assistant:rc
  needs: []
  script: *id002
  stage: homeassistant
  tags: *id003
  variables: *id004
jsonlint:
  before_script:
  - jsonlint --version || true
  image: sahsu/docker-jsonlint
  script:
  - "for file in $(find . -type f -name \"*.json\" -path \"mysensors.json\" -prune);\
    \ do\n  if ! jsonlint -q $file; then\n    export FAILED=1\n  else\n    echo \"\
    $file OK\"\n  fi\ndone\nif [ \"${FAILED}\" = \"1\" ]; then\n  exit 1\nfi\n"
  stage: preflight
  tags: *id005
restart-hass:
  before_script:
  - apk --no-cache add curl
  environment:
    name: home-assistant
  except:
    changes:
    - docker-compose.yml
    - update.sh
  image:
    entrypoint:
    - ''
    name: alpine:latest
  needs:
  - deploy
  only:
    refs:
    - master
  script:
  - 'curl -X POST -H "Authorization: Bearer $DEPLOYMENT_HASS_TOKEN" -H "Content-Type:
    application/json" $DEPLOYMENT_HASS_URL/api/services/homeassistant/restart'
  stage: postflight
  tags:
  - hass
shellcheck:
  before_script:
  - ln -s $CI_PROJECT_DIR /config
  - mv shell_commands/fake_secrets.sh shell_commands/secrets.sh
  - shellcheck --version
  - apk --no-cache add grep
  image:
    entrypoint:
    - ''
    name: koalaman/shellcheck-alpine:stable
  script:
  - "for file in $(grep -IRl \"#\\!\\(/usr/bin/env \\|/bin/\\)\" --exclude-dir \"\
    .git\" .); do\n  if ! shellcheck -x $file; then\n    export FAILED=1\n  else\n\
    \    echo \"$file OK\"\n  fi\ndone\nif [ \"${FAILED}\" = \"1\" ]; then\n  exit\
    \ 1\nfi\n"
  stage: preflight
  tags: *id005
stages:
- preflight
- homeassistant
- deploy
- docker-deploy
- postflight
variables:
  GIT_SUBMODULE_STRATEGY: recursive
yamllint:
  allow_failure: true
  before_script:
  - yamllint --version
  - mv fake_secrets.yaml secrets.yaml
  - rm known_devices.yaml appdaemon.yaml apps/apps.yaml
  image: sdesbure/yamllint
  script:
  - yamllint .
  stage: preflight
  tags: *id005
