docs:
  artifacts:
    expire_in: 1 week
    paths:
    - build/docs/doxygen/html
    when: always
  before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get -q update
  - apt-get -qy install software-properties-common
  - "apt-get -qy install \\\n    libboost-dev \\\n    libboost-date-time-dev \\\n\
    \    libboost-filesystem-dev \\\n    libboost-program-options-dev \\\n    libboost-system-dev\
    \ \\\n    libboost-thread-dev \\\n    libboost-regex-dev \\\n    libboost-test-dev\
    \ \\\n    swig \\\n    cmake \\\n    doxygen \\\n    gcc \\\n    gnuradio-dev\
    \ \\\n    libconfig++-dev \\\n    libgmp-dev \\\n    liborc-0.4-0 \\\n    liborc-0.4-dev\
    \ \\\n    liborc-0.4-dev-bin \\\n    libsndfile1-dev \\\n    git\n"
  image: ${GITLAB_CI_IMAGE_UBUNTU}
  script:
  - mkdir -p build
  - cd build
  - rm -rf *
  - cmake ..
  - make doxygen_target
  stage: build
pages:
  artifacts:
    paths:
    - public
  image: ${GITLAB_CI_IMAGE_ALPINE}
  only:
    refs:
    - tags
  script:
  - mv build/docs/doxygen/html/ public/
  stage: deploy
stages:
- static
- build
- test
- deploy
style:
  before_script:
  - apt-get -q update
  - apt-get -qy install astyle
  image: ${GITLAB_CI_IMAGE_UBUNTU}
  script:
  - 'astyle --dry-run --options=.astylerc --formatted lib/*.cc lib/*.h include/gnuradio/leo/*.h  |
    sed ''s/^Formatted/ERROR: Unformatted/;T;q1'''
  stage: static
ubuntu:
  before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get -q update
  - apt-get -qy install software-properties-common
  - "apt-get -qy install \\\n    libboost-dev \\\n    libboost-date-time-dev \\\n\
    \    libboost-filesystem-dev \\\n    libboost-program-options-dev \\\n    libboost-system-dev\
    \ \\\n    libboost-thread-dev \\\n    libboost-regex-dev \\\n    libboost-test-dev\
    \ \\\n    swig \\\n    cmake \\\n    gcc \\\n    python3-gi\\\n    gnuradio-dev\
    \ \\\n    libconfig++-dev \\\n    libgmp-dev \\\n    liborc-0.4-0 \\\n    liborc-0.4-dev\
    \ \\\n    liborc-0.4-dev-bin \\\n    libsndfile1-dev \\\n    git\n"
  image: ${GITLAB_CI_IMAGE_UBUNTU}
  script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr ..
  - make
  - make install
  - ldconfig
  - python3 -c "import gnuradio.leo"
  stage: test
  variables:
    DEBIAN_FRONTEND: noninteractive
variables:
  GITLAB_CI_IMAGE_ALPINE: alpine:3.15.3
  GITLAB_CI_IMAGE_UBUNTU: ubuntu:jammy
