before_script:
- apt-get update -qq
- apt-get install -qq clang-tools-6.0 curl docutils-common gdb lcov libarchive-dev
  libtalloc-dev strace swig uthash-dev xsltproc
check:
  allow_failure: true
  script:
  - make -C src proot care
  - timeout --signal=SIGKILL 5m make -C test
  stage: check
dist:
  after_script:
  - mkdir -p dist
  - cp src/proot dist/
  - cd dist
  - sha256sum ./proot > proot.sha256sum
  - md5sum ./proot > proot.md5sum
  artifacts:
    paths:
    - dist
  script:
  - LDFLAGS="${LDFLAGS} -static" make -C src proot GIT=false
  stage: dist
gcov:
  artifacts:
    paths:
    - gcov-latest
  script:
  - /bin/sh ./util/coverage.sh
  stage: coverage
image: gcc:7.4.0
pages:
  artifacts:
    paths:
    - public
  dependencies:
  - dist
  - gcov
  - scan-build
  script:
  - /bin/sh ./util/dist.sh
  stage: deploy
scan-build:
  after_script:
  - cp -R /tmp/scan-build-* scan-build-latest
  artifacts:
    paths:
    - scan-build-latest
  script:
  - scan-build-6.0 make -C src proot
  stage: static-analysis
site:
  allow_failure: true
  only:
  - master
  script:
  - /bin/sh ./util/site.sh
  stage: deploy
stages:
- check
- dist
- coverage
- static-analysis
- deploy
