before_script:
- pip install --upgrade pip setuptools
- pip install tox
cache:
  key: $CI_PROJECT_ID
  paths:
  - $PIP_CACHE_DIR
pages:
  artifacts:
    paths:
    - public
  before_script:
  - pip install --upgrade pip setuptools
  - pip install tox
  environment: production
  image: python:3.4
  only:
  - master
  script:
  - tox -e build-docs
  - mv docs/_build/html/ public/
  stage: deploy
pep8:
  image: python:3.4
  script:
  - tox -e pep8
  stage: lint
stages:
- lint
- unit_test
- combine_coverage_unit
- integration_test
- combine_coverage_integration
- deploy
test_py27_integration:
  before_script:
  - pip install --upgrade pip setuptools
  - pip install tox codecov
  image: python:2.7
  script:
  - tox -e py27 -- -m integration
  - codecov -F integrationtests
  stage: integration_test
test_py27_unit:
  before_script:
  - pip install --upgrade pip setuptools
  - pip install tox codecov
  image: python:2.7
  script:
  - tox -e py27 -- -m unit
  - codecov -F unittests
  stage: unit_test
test_py34_integration:
  before_script:
  - pip install --upgrade pip setuptools
  - pip install tox codecov
  image: python:3.4
  script:
  - tox -e py34 -- -m integration
  - codecov -F integrationtests
  stage: integration_test
test_py34_unit:
  before_script:
  - pip install --upgrade pip setuptools
  - pip install tox codecov
  image: python:3.4
  script:
  - tox -e py34 -- -m unit
  - codecov -F unittests
  stage: unit_test
upload_pypi2:
  before_script:
  - pip install twine
  image: python:2.7
  only:
  - tags
  script:
  - python setup.py sdist
  - python setup.py bdist_wheel --universal
  - twine register dist/soko-$(python setup.py --version dummy).tar.gz
  - twine register dist/soko-$(python setup.py --version dummy)-py2.py3-none-any.whl
  - twine upload dist/*
  stage: deploy
variables:
  PIP_CACHE_DIR: $CI_PROJECT_DIR/pip-cache
  TWINE_REPOSITORY: testpypi
  TWINE_REPOSITORY_URL: https://testpypi.python.org/pypi
