deploy:
  before_script:
  - echo ${GCLOUD_ACCOUNT} | base64 --decode | gcloud auth activate-service-account
    --key-file=-
  image: google/cloud-sdk:366.0.0
  script:
  - gcloud app deploy --no-promote
  stage: deploy
  when: manual
format-test:
  artifacts:
    expire_in: 3 days
    paths:
    - cover.html
  script:
  - export CGO_ENABLED=0
  - go fmt
  - go vet
  - go test -cover -coverprofile cover.out ./...
  - go tool cover -html=cover.out -o cover.html
  stage: test
image: golang:1.14.15-alpine3.12
pages:
  artifacts:
    paths:
    - public
  dependencies:
  - format-test
  only:
  - master
  script:
  - mkdir -p public/coverage
  - mv cover.html public/coverage/index.html
  stage: deploy
stages:
- test
- deploy
