before_script:
- ls -la
- pwd
- mkdir -p /go/src/gitlab.com/sorenmat/certgen
- cp -r * /go/src/gitlab.com/sorenmat/certgen
- cd /go/src/gitlab.com/sorenmat/certgen
- export CUR_WD=`pwd`
build-and-test:
  artifacts:
    paths:
    - certgen
  image: golang:1.8
  script:
  - cd $CUR_WD
  - make setup
  - make ci
  stage: build
build-docker:
  dependencies:
  - build-and-test
  image: golang:1.8
  script:
  - cd $CUR_WD
  - go get -v github.com/goreleaser/goreleaser
  stage: deploy
stages:
- build
- deploy
