.autorun:
  artifacts:
    expire_in: 4 weeks
    name: $CI_COMMIT_REF_NAME
    paths:
    - autorun.log
    when: always
  rules:
  - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
      == "develop"
    when: never
  - if: $CI_COMMIT_TAG
    when: never
  - if: $GENERATE_PAGE_ONLY
    when: never
  - if: $PUBLISH_ONLY
    when: never
  - if: $PUBLISH_MULTICORE
    when: never
  - if: $GENERATE_MANUAL_ONLY
    when: never
  - if: $CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME =~ /^develop/ || $CI_COMMIT_REF_NAME
      =~ /^feature/ || $CI_COMMIT_REF_NAME =~ /beta$/ || $CI_COMMIT_REF_NAME =~ /^merge/
    when: on_success
  stage: test
  tags:
  - prodcom
  - stabfem
.publish:
  artifacts:
    expire_in: 1 week
    paths:
    - ./*CASES/*/html/*
    - ./*CASES/*/.*.cached_*
    - ./*CASES/*/*/html/*
    - ./*CASES/*/*/.*.cached_*
  script:
  - ./.gitlab-ci-publish-script.sh
  stage: publish
  tags:
  - stabfem
  - prodcom
autorun-matlab-ff4:
  extends: .autorun
  script:
  - ./.gitlab-ci-autorun.sh -m --ffver 4
autorun-matlab-ff4-long:
  extends: .autorun
  rules:
  - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
      == "develop"
    when: on_success
  - if: $CI_COMMIT_TAG
    when: on_success
  script:
  - ./.gitlab-ci-autorun.sh -m --ffver 4 --list long
autorun-octave-ff4:
  extends: .autorun
  script:
  - ./.gitlab-ci-autorun.sh --ffver 4
autorun-octave-ff4-long:
  extends: .autorun
  rules:
  - if: $CI_COMMIT_MESSAGE =~ /\[\[OCTAVE\]\]/
    when: on_success
  - if: $CI_COMMIT_TAG
    when: on_success
  script:
  - ./.gitlab-ci-autorun.sh --ffver 4 --list long
makepdf:
  artifacts:
    expire_in: never
    name: $CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
    paths:
    - ./99_Documentation/MANUAL/main.pdf
    when: on_success
  rules:
  - if: $PUBLISH_MULTICORE
    when: never
  - if: $CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "develop"
    when: on_success
  - if: $CI_COMMIT_MESSAGE =~ /\[\[MANUAL\]\]/
    when: on_success
  - if: $GENERATE_MANUAL_ONLY
    when: always
  script:
  - cd ./99_Documentation/MANUAL/
  - pdflatex main.tex
  - pdflatex main.tex
  stage: manual
  tags:
  - stabfem
pages:
  artifacts:
    paths:
    - public
  rules:
  - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    when: never
  - if: $CI_COMMIT_MESSAGE =~ /\[\[PUBLISH\]\]/
    when: on_success
  - if: $GENERATE_PAGE
    when: always
  - if: $GENERATE_PAGE_ONLY
    when: always
  - if: $PUBLISH_ONLY
    when: always
  - if: $PUBLISH_MULTICORE
    when: always
  script:
  - ./.gitlab-ci-page-script.sh
  - ./.gitlab-ci-autoindex-script.sh
  stage: pages
  tags:
  - stabfem
  - prodcom
publish-master:
  cache:
    key: publish-master-cache
    paths:
    - ./*CASES/*/html/*
    - ./*CASES/*/.*.cached_*
    - ./*CASES/*/*/html/*
    - ./*CASES/*/*/.*.cached_*
    policy: pull-push
  extends: .publish
  rules:
  - if: $GENERATE_PAGE_ONLY
    when: never
  - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    when: never
  - if: $CI_COMMIT_REF_NAME == "master"
    when: never
publish-multiproc_1:
  cache:
    key: publish-other-cache
    paths:
    - ./*CASES/*/html/*
    - ./*CASES/*/.*.cached_*
    - ./*CASES/*/*/html/*
    - ./*CASES/*/*/.*.cached_*
    policy: pull-push
  extends: .publish
  rules:
  - if: $GENERATE_PAGE_ONLY
    when: never
  - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    when: never
  - if: $PUBLISH_MULTICORE
    when: always
  script:
  - echo " launching publish by batches of 10"
  - NSTART=1
  - NEND=10
  - ./.gitlab-ci-publish-script.sh
publish-multiproc_2:
  cache:
    key: publish-other-cache
    paths:
    - ./*CASES/*/html/*
    - ./*CASES/*/.*.cached_*
    - ./*CASES/*/*/html/*
    - ./*CASES/*/*/.*.cached_*
    policy: pull-push
  extends: .publish
  rules:
  - if: $GENERATE_PAGE_ONLY
    when: never
  - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    when: never
  - if: $PUBLISH_MULTICORE
    when: always
  script:
  - echo " launching publish by batches of 10"
  - NSTART=91
  - NEND=100
  - ./.gitlab-ci-publish-script.sh
publish-other:
  cache:
    key: publish-other-cache
    paths:
    - ./*CASES/*/html/*
    - ./*CASES/*/.*.cached_*
    - ./*CASES/*/*/html/*
    - ./*CASES/*/*/.*.cached_*
    policy: pull-push
  extends: .publish
  rules:
  - if: $GENERATE_PAGE_ONLY
    when: never
  - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    when: never
  - if: $PUBLISH_MULTICORE
    when: never
  - if: $CI_COMMIT_MESSAGE =~ /\[\[PUBLISH\]\]/
    when: on_success
  - if: $GENERATE_PAGE
    when: always
  - if: $PUBLISH_ONLY
    when: always
publish-restore-cache-other:
  cache:
    key: publish-other-cache
    paths:
    - ./*CASES/*/html/*
    - ./*CASES/*/.*.cached_*
    - ./*CASES/*/*/html/*
    - ./*CASES/*/*/.*.cached_*
    policy: pull
  extends: .publish
  rules:
  - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    when: never
  - if: $GENERATE_PAGE_ONLY
    when: always
  - if: $PUBLISH_ONLY
    when: always
  script:
  - echo "Restoring cache and transmiting it to page job."
stages:
- test
- manual
- publish
- pages
variables:
  GENERATE_MANUAL_ONLY:
    description: to be used to generate manual only, skipping all other steps
    value: ''
  GENERATE_PAGE_ONLY:
    description: to be used to regenerate pages, skipping autorun and publish
    value: ''
  NEND:
    description: Ending point when publishing a subset of cases
    value: ''
  NSTART:
    description: Starting point when publishing a subset of cases
    value: ''
  PUBLISH_MULTICORE:
    description: to be used to publish all cases IN A PARALLEL WAY, and regenerate
      pages, skipping autorun
    value: ''
  PUBLISH_ONLY:
    description: to be used to publish and regenerate pages, skipping autorun
    value: ''
