before_script:
- mkdir -p "${GOPATH}/src/${REPO_NAME}"
- mv "${CI_PROJECT_DIR}"/* "${GOPATH}/src/${REPO_NAME}"
build:
  script:
  - go build "${REPO_NAME}"
  stage: build
image: golang:1.14
stages:
- test
- build
test:
  script:
  - go test -v "${REPO_NAME}/..."
  stage: test
variables:
  REPO_NAME: gitlab.com/gitlab-org/prometheus-storage-migrator
