image: docker:latest
job1:
  only:
  - master
  script:
  - docker-compose up -d && sleep 10
  - docker ps;
  - testResults="echo $(curl -i /tests/basic/index.cfm?opt_run=true&reporter=json&target=tests.basic.basic)";
  - echo "$testResults";
  - if ! grep -i "http/1.1 200" <<< $testResults; then exit 1; fi
  stage: test
services:
- docker
stages:
- test
