pages:
  artifacts:
    expire_in: 1 week
    paths:
    - public
  image: alpine
  only:
  - master@chusiang/gup
  - tags@chusiang/gup
  script:
  - apk add --update --no-cache make
  - make deploy_to_pages
  stage: deploy
stages:
- deploy
