build-image:
  script:
  - docker login "$CI_REGISTRY" --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD"
  - docker pull "$CI_REGISTRY_IMAGE:base"
  - cd /builds/elRepo.io/Tier1/; docker build -t "$CI_REGISTRY_IMAGE:latest" -f latest.Dockerfile
    .
  - docker push "$CI_REGISTRY_IMAGE:latest"
  stage: build
image: docker:stable
services:
- docker:stable-dind
stages:
- build
- test
test-forum-propagation:
  script:
  - apk add --no-cache bash
  - bash -e ./forumsTestPropagation.sh || bash -e -x ./forumsTestPropagation.sh
  stage: test
test-jsonapi:
  script:
  - docker login "$CI_REGISTRY" --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD"
  - docker pull "$CI_REGISTRY_IMAGE:latest"
  - docker run --name tier1 --detach --tty "$CI_REGISTRY_IMAGE:latest" retroshare-service
    --jsonApiPort 9092
  - docker exec tier1 curl --verbose http://127.0.0.1:9092/jsonApiServer/version
  - docker exec tier1 curl --verbose http://127.0.0.1:9092/rsMsgs/getChatLobbyList
  - docker exec tier1 curl --verbose http://127.0.0.1:9092/rsLoginHelper/getLocations
  - docker exec tier1 curl --verbose --data '{ "location":{ "mLocationName":"Test
    1", "mPpgName":"Test2", "makeHidden":false, "makeAutoTor":false }, "password":"Test
    3", "caller_data":"Test 5"}' http://127.0.0.1:9092/rsLoginHelper/createLocation
  - docker exec tier1 curl --verbose http://127.0.0.1:9092/rsLoginHelper/getLocations
  - docker exec tier1 curl --verbose http://127.0.0.1:9092/rsLoginHelper/isLoggedIn
  - docker exec tier1 curl --verbose http://127.0.0.1:9092/rsMsgs/getChatLobbyList
  - docker container stop tier1
  stage: test
