build:
  artifacts:
    expire_in: 1 week
    paths:
    - dist/
  script:
  - npm run build
  stage: build
cache:
  paths:
  - node_modules/
image: node:alpine
setup:
  script:
  - yarn install
  stage: setup
stages:
- setup
- build
- test
test:
  dependencies:
  - build
  script:
  - npm run test
  stage: test
