cache:
  key: ${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}
  paths:
  - ~/.composer
code-style:
  dependencies:
  - prepare_cache
  needs:
  - prepare_cache
  script:
  - vendor/bin/ecs
  stage: check
image: registry.gitlab.com/tjvb/phpimages:php83
infection:
  artifacts:
    paths:
    - build/infection/
    reports:
      codequality: build/infection/code-climate-gitlab.json
    when: always
  dependencies:
  - prepare_cache
  image: registry.gitlab.com/tjvb/phpimages:php83
  needs:
  - prepare_cache
  script:
  - composer install
  - vendor/bin/phpunit --migrate-configuration
  - vendor/bin/infection
  stage: test
lint:
  dependencies: []
  script:
  - find src/ -type f -name '*.php' -exec php -l {} \; | (! grep -v "No syntax errors
    detected" )
  stage: check
mlc:
  dependencies: []
  image: registry.gitlab.com/tjvb/tools-images/mlc
  needs: []
  script:
  - mlc doc
  stage: check
phpmd:
  dependencies:
  - prepare_cache
  needs:
  - prepare_cache
  script:
  - composer phpmd
  stage: check
phpstan:
  artifacts:
    paths:
    - phpstan.json
    reports:
      codequality: phpstan.json
    when: always
  dependencies:
  - prepare_cache
  needs:
  - prepare_cache
  script:
  - php -d memory_limit=500M vendor/bin/phpstan analyse --error-format=gitlab | tee
    phpstan.json
  - cat phpstan.json
  stage: check
prepare_cache:
  artifacts:
    expire_in: 2 hour
    name: vendor
    paths:
    - vendor/*
  cache:
    key: ${CI_PROJECT_NAME}
    paths:
    - vendor/
    policy: pull-push
  script:
  - composer validate
  - composer install
  stage: prepare
stages:
- prepare
- check
- test
- report
test:
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: phpunitresult/cobertura-coverage.xml
      junit: phpunitresult/junit.xml
  coverage: /^\s*Lines:\s*\d+.\d+\%/
  dependencies:
  - prepare_cache
  image: registry.gitlab.com/tjvb/phpimages:php$PHP
  needs:
  - prepare_cache
  parallel:
    matrix:
    - LARAVEL: 9
      PHP:
      - 80
      - 81
      - 82
      - 83
      TESTBENCH: 7
    - LARAVEL: 10
      PHP:
      - 81
      - 82
      - 83
      TESTBENCH: 8
    - LARAVEL: 11
      PHP:
      - 82
      - 83
      - 84
      TESTBENCH: 9
    - LARAVEL: 12
      PHP:
      - 82
      - 83
      - 84
      TESTBENCH: 10
  script:
  - echo "Laravel $LARAVEL"
  - composer require --dev "orchestra/testbench=^$TESTBENCH"
  - vendor/bin/phpunit --migrate-configuration || true
  - XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-text --colors=never --coverage-cobertura=phpunitresult/cobertura-coverage.xml
    --log-junit=phpunitresult/junit.xml
  - sed -i 's~ filename="~ filename="src/~' phpunitresult/cobertura-coverage.xml
  stage: test
test_lowest:
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: phpunitresult/cobertura-coverage.xml
      junit: phpunitresult/junit.xml
  coverage: /^\s*Lines:\s*\d+.\d+\%/
  dependencies:
  - prepare_cache
  image: registry.gitlab.com/tjvb/phpimages:php80
  needs:
  - prepare_cache
  parallel: null
  script:
  - composer update --prefer-lowest
  - vendor/bin/phpunit --coverage-text --colors=never --coverage-cobertura=phpunitresult/cobertura-coverage.xml
    --log-junit=phpunitresult/junit.xml
  - sed -i 's~ filename="~ filename="src/~' phpunitresult/cobertura-coverage.xml
  stage: test
vale:
  dependencies: []
  image:
    entrypoint:
    - ''
    name: registry.gitlab.com/tjvb/tools-images/vale
  needs: []
  script:
  - /bin/vale --config=tools/vale/.vale.ini README.md CONTRIBUTING.md
  stage: check
