before_script:
- go get github.com/pkg/browser
- go get gitlab.com/golang-commonmark/markdown
build:
  script:
  - go build ./...
  stage: build
image: golang:1.11
stages:
- build
- test
test:
  script:
  - test -z "$(gofmt -l . | tee /dev/stderr)"
  - go test ./...
  stage: test
