before_script:
- which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
- eval $(ssh-agent -s)
- echo "$DEPLOY_KEY" | tr -d '\r' | ssh-add - > /dev/null
- mkdir -p ~/.ssh
- chmod 700 ~/.ssh
- echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
- chmod 644 ~/.ssh/known_hosts
- apt-get update -yqq
- apt-get install git -yqq
- apt-get install zip unzip -yqq
- apt-get install libxml2-dev -yqq
- docker-php-ext-install soap
- docker-php-ext-install sockets
- curl --silent --show-error https://getcomposer.org/installer | php
build-latest-tags:
  artifacts:
    name: mirrOS-modules-$CI_COMMIT_SHA
    paths:
    - build/*.zip
    - failed-modules
  script:
  - git submodule foreach '../package-module.sh $name'
  stage: build
deploy-zip-files:
  environment:
    name: update-server
    url: https://api.glancr.de
  except:
  - /^\[meta\]$/
  only:
  - master
  script:
  - rsync -t build/*.zip $USER@api.glancr.de:$ROOT/moduleZips/
  stage: deploy
image: php:7.0-cli
stages:
- build
- deploy
variables:
  GIT_SUBMODULE_STRATEGY: normal
