build_spag:
  artifacts:
    name: ${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}
    paths:
    - build/*.rpm
  script:
  - mkdir build/
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make all
  - ./unittest
  - make package
  stage: build
image: registry.gitlab.com/nestal/spaghetti
stages:
- build
