before_script:
- mkdir -p ${PIP_CACHE}
- python -m venv ${VENV_DIR}
- source ${VENV_DIR}/bin/activate
buildwheels:
  artifacts:
    expire_in: 1 hour
    name: packaged-wheels
    paths:
    - ${WHEELHOUSE}
  script:
  - apt-get update
  - apt-get install -y apt-transport-https wget
  - wget -qO - https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add
    -
  - echo 'deb https://deb.nodesource.com/node_12.x xenial main' > /etc/apt/sources.list.d/nodejs.list
  - apt-get update
  - apt-get install -y nodejs
  - apt-get install -y libldap2-dev libsasl2-dev
  - pip3 ${PIP_TRUSTED_HOSTS} --cache-dir=${PIP_CACHE} install -r requirements/build.txt
  - pip3 wheel --wheel-dir=${WHEELHOUSE} .
  stage: package
cache:
  key: $CI_MERGE_REQUEST_ID
  paths:
  - ${PIP_CACHE}
  - ${APP}/frontend/node_modules
  - ${VENV_DIR}
djangotests:
  script:
  - apt-get update
  - apt-get install -y libldap2-dev libsasl2-dev
  - mkdir -p /etc/${APP}
  - cp conf/${APP}.ini.gitlab-ci /etc/${APP}/${APP}.ini
  - mkdir -p /vagrant/reportkey
  - /usr/bin/openssl genrsa -out /vagrant/reportkey/private.pem
  - /usr/bin/openssl rsa -in /vagrant/reportkey/private.pem -outform PEM -pubout -out
    /vagrant/reportkey/public.pem
  - /usr/bin/printf "\n\n\n\n\n\n\n" | openssl req -new -x509 -key /vagrant/reportkey/private.pem
    -out /vagrant/reportkey/public.cer
  - pip3 install ${PIP_TRUSTED_HOSTS} -r ./requirements/dev.txt
  - python3 ./setup.py develop
  - ${APP} test
  services:
  - redis:latest
  - postgres:9.5
  stage: test
  variables:
    DATABASE_URL: postgresql://postgres:postgres@postgres:5432/mataara_test
image: python:3.5
javascript_lint:
  before_script:
  - cd ${APP}/frontend
  - npm install
  image: node:12
  script:
  - npm run lint
  stage: test
javascript_test:
  before_script:
  - ln -fs /usr/share/zoneinfo/Pacific/Auckland /etc/localtime
  - dpkg-reconfigure -f noninteractive tzdata
  - cd ${APP}/frontend
  - npm install
  image: node:12
  script:
  - npm test
  stage: test
python_lint:
  allow_failure: true
  script:
  - pip3 ${PIP_TRUSTED_HOSTS} --cache-dir=${PIP_CACHE} install flake8
  - flake8
  stage: test
security_checks:
  script:
  - pip3 ${PIP_TRUSTED_HOSTS} --cache-dir=${PIP_CACHE} install bandit==1.6.2
  - bandit -r ${APP} -x ${APP}/*/migrations,${APP}/frontend
  stage: test
stages:
- test
- package
- unit_tests
variables:
  APP: archimedes
  PIP_CACHE: pip_cache
  PIP_TRUSTED_HOSTS: --trusted-host files.pythonhosted.org --trusted-host pypi.org
    --trusted-host pypi.python.org
  POSTGRES_DB: mataara_test
  POSTGRES_PASSWORD: postgres
  POSTGRES_USER: postgres
  VENV_DIR: venv
  WHEELHOUSE: wheels
