build-production:
  only:
  - master
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker pull $IMAGE_BRANCH || true
  - docker build --build-arg REACT_APP_API_URL=$REACT_APP_API_URL --build-arg REACT_APP_IDENTITY_URL=$REACT_APP_IDENTITY_URL
    --cache-from $IMAGE_BRANCH -t $IMAGE_TAG -t $IMAGE_BRANCH .
  - docker push $IMAGE_TAG
  - docker push $IMAGE_BRANCH
  stage: build
  tags:
  - docker
  variables:
    REACT_APP_API_URL: https://api.otrack.info
    REACT_APP_HYPERTRACK_KEY: pk_test_12730a0f97d7a2d3f5767a7721a5137f7bf2533f
    REACT_APP_IDENTITY_URL: https://identity.otrack.info
build-staging:
  only:
  - develop
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker pull $IMAGE_BRANCH || true
  - docker build --build-arg REACT_APP_API_URL=$REACT_APP_API_URL --build-arg REACT_APP_IDENTITY_URL=$REACT_APP_IDENTITY_URL
    --cache-from $IMAGE_BRANCH -t $IMAGE_TAG -t $IMAGE_BRANCH .
  - docker push $IMAGE_TAG
  - docker push $IMAGE_BRANCH
  stage: build
  tags:
  - docker
  variables:
    REACT_APP_API_URL: https://api-staging.otrack.info
    REACT_APP_HYPERTRACK_KEY: pk_test_12730a0f97d7a2d3f5767a7721a5137f7bf2533f
    REACT_APP_IDENTITY_URL: https://identity-staging.otrack.info
deploy-production:
  environment:
    name: production
    url: https://otrack.info
  image: google/cloud-sdk
  only:
  - master
  script:
  - echo "$PRODUCTION_GOOGLE_KEY" > key.json
  - gcloud auth activate-service-account --key-file=key.json
  - gcloud container clusters get-credentials $PRODUCTION_CLUSTER
  - kubectl set image deployments/restaurants otrack-restaurants=$IMAGE_TAG
  stage: deploy
  tags:
  - docker
deploy-staging:
  environment:
    name: staging
    url: https://staging.otrack.info
  image: google/cloud-sdk
  only:
  - develop
  script:
  - echo "$STAGING_GOOGLE_KEY" > key.json
  - gcloud auth activate-service-account --key-file=key.json
  - gcloud container clusters get-credentials $STAGING_CLUSTER
  - kubectl set image deployments/restaurants-s otrack-restaurants=$IMAGE_TAG
  stage: deploy
  tags:
  - docker
image: docker:latest
react-test:
  image: node:8
  script:
  - cd react-app
  - yarn install
  - yarn test
  stage: test
  tags:
  - docker
services:
- docker:dind
stages:
- test
- build
- deploy
variables:
  DOCKER_DRIVER: overlay2
  IMAGE_BRANCH: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_BUILD_REF
