before_script:
- mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
- ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
- cd $GOPATH/src/$REPO_NAME
- go get -v -d ./...
cache:
  paths:
  - /go/src/github.com
  - /go/src/gopkg.in
compile:
  artifacts:
    paths:
    - godoit
  script:
  - go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/godoit $REPO_NAME/cmd/godoit
  stage: build
format:
  script:
  - test -z $(go fmt $(go list ./... | grep -v /vendor/))
  - go vet $(go list ./... | grep -v /vendor/)
  - go test -v -race -coverprofile=cover.out $(go list ./... | grep -v /vendor/) &&
    go tool cover -func=cover.out
  stage: test
image: golang:latest
stages:
- test
- build
variables:
  REPO_NAME: gitlab.com/phinicota/godoit
