.docker:
  dependencies: &id002
  - build
  image: docker
  services: &id003
  - docker:dind
  stage: docker
  variables: &id004
    DOCKER_HOST: tcp://docker:2375
.scripts:
  before_script: &id001
  - ln -s /builds/$CI_PROJECT_PATH /go/src/replay-api
  - cd /go/src/replay-api
build:
  artifacts:
    expire_in: 1 week
    paths:
    - build/replay-api
  before_script: *id001
  script:
  - make release
  stage: build
docker:replay-api:
  dependencies: *id002
  image: docker
  script:
  - docker build -t "${CI_REGISTRY_IMAGE}/replay-api:latest" -f docker/Dockerfile
    .
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  - docker push "${CI_REGISTRY_IMAGE}/replay-api:latest"
  services: *id003
  stage: docker
  variables: *id004
docker:replay-api:tags:
  dependencies: *id002
  image: docker
  only:
  - tags
  script:
  - docker build -t "${CI_REGISTRY_IMAGE}/replay-api:${CI_COMMIT_TAG}" -f docker/Dockerfile
    .
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  - docker push "${CI_REGISTRY_IMAGE}/replay-api:${CI_COMMIT_TAG}"
  services: *id003
  stage: docker
  variables: *id004
image: golang:1.13.4
lint:
  before_script: *id001
  script:
  - make lint
  stage: lint
stages:
- lint
- test
- build
- docker
test:
  artifacts:
    reports:
      junit: report.xml
  before_script: *id001
  script:
  - go get -u github.com/jstemmer/go-junit-report
  - make test 2>&1 | go-junit-report > report.xml
  stage: test
