.build:
  interruptible: true
  script:
  - docker buildx create --use
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - '[[ $IS_RELEASE -eq 1 ]] && docker buildx build --platform linux/arm64,linux/amd64
    --cache-from ${IMAGE_REGISTRY}:latest --build-arg VERSION=${VERSION} --build-arg
    PHP_IMAGE_VERSION=${PHP_IMAGE_VERSION} --build-arg MAJOR_VERSION_NODE=$(echo ${VERSION_NODE}
    | cut -d''.'' -f1) -t ${IMAGE_NAME}:${VERSION} -t ${IMAGE_NAME}:latest --push
    ${IMAGE_FILE}'
  - '[[ $IS_RELEASE -eq 0 ]] && docker buildx build --platform linux/arm64,linux/amd64
    --cache-from ${IMAGE_REGISTRY}:latest --build-arg VERSION=${VERSION} --build-arg
    PHP_IMAGE_VERSION=${PHP_IMAGE_VERSION} --build-arg MAJOR_VERSION_NODE=$(echo ${VERSION_NODE}
    | cut -d''.'' -f1) -t ${IMAGE_NAME}:${BUILD_VERSION} --push ${IMAGE_FILE}'
  - echo ${IMAGE_NAME}:${BUILD_VERSION}
  stage: building image
before_script:
- docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
ci/nginx:
  extends:
  - .build
  variables:
    VERSION: $VERSION_NGINX
ci/php:
  extends:
  - .build
  variables:
    VERSION: $VERSION_PHP
ci/renovate:
  extends:
  - .build
  variables:
    VERSION: $VERSION_RENOVATE
docs:
  extends:
  - .build
  needs:
  - php
  variables:
    PHP_IMAGE_VERSION: $VERSION_PHP
    VERSION: $VERSION_NODE
image: docker:dind
maildev:
  extends:
  - .build
  variables:
    VERSION: $VERSION_MAILDEV
mariadb:
  extends:
  - .build
  variables:
    VERSION: $VERSION_MARIADB
nginx:
  extends:
  - .build
  variables:
    VERSION: $VERSION_NGINX
node:
  extends:
  - .build
  variables:
    VERSION: $VERSION_NODE
php:
  extends:
  - .build
  variables:
    VERSION: $VERSION_PHP
phpmyadmin:
  extends:
  - .build
  variables:
    VERSION: $VERSION_PHPMYADMIN
playwright:
  extends:
  - .build
  needs:
  - node
  - php
  tags:
  - saas-linux-medium-amd64
  variables:
    PHP_IMAGE_VERSION: $VERSION_PHP
    PLAYWRIGHT_VERSION: $VERSION_PLAYWRIGHT
    VERSION: $VERSION_NODE
playwright-dev:
  extends:
  - .build
  variables:
    VERSION: $VERSION_PLAYWRIGHT
redis:
  extends:
  - .build
  variables:
    VERSION: $VERSION_REDIS
selenium:
  extends:
  - .build
  variables:
    VERSION: $VERSION_SELENIUM
services:
- docker:dind
stages:
- building image
variables:
  IMAGE_FILE: dockerfiles/${CI_JOB_NAME}
  IMAGE_NAME: ${CI_REGISTRY_IMAGE}/${CI_JOB_NAME}
  VERSION_MAILDEV: 2.2.1
  VERSION_MARIADB: 11.4.9
  VERSION_NGINX: 1.28.0
  VERSION_NODE: 20.19.5
  VERSION_PHP: 8.3.27
  VERSION_PHPMYADMIN: 5.2.1
  VERSION_PLAYWRIGHT: 1.49.1
  VERSION_REDIS: 7.0.15
  VERSION_RENOVATE: 40.0.4
  VERSION_SELENIUM: 3.141.59-20200409
workflow:
  name: Change the build versions
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    variables:
      BUILD_VERSION: $CI_MERGE_REQUEST_IID
      IS_RELEASE: 0
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    variables:
      BUILD_VERSION: $CI_COMMIT_SHORT_SHA
      IS_RELEASE: 1
