before_script:
- apk add --no-cache make
- make login-ci
build:
  script:
  - make build
  - make push-ci
  stage: build
image: docker
push:
  environment: docker-hub
  only:
  - master
  script:
  - make login-ci-hub
  - make pull-ci
  - make push
  stage: push
  when: manual
services:
- docker:dind
stages:
- build
- push
