audit:
  cache:
    key: ${CI_JOB_NAME}
    paths:
    - target
    - .cargo
    policy: pull
  image: rust:latest
  script:
  - apt-get update
  - apt-get -y --no-install-recommends install libsystemd-dev
  - cargo install cargo-audit
  - cargo audit --ignore RUSTSEC-2020-0071 --ignore RUSTSEC-2020-0159
  stage: build
build:
  cache:
    key: ${CI_JOB_NAME}
    paths:
    - target
    - .cargo
    policy: pull
  image: rust:latest
  script:
  - apt-get update
  - apt-get -y --no-install-recommends install libsystemd-dev
  - cargo build
  stage: build
build-release:
  artifacts:
    paths:
    - target/path/cinit
  cache:
    key: ${CI_JOB_NAME}
    paths:
    - target
    - .cargo
  image: docker:latest
  only:
  - tags
  script:
  - export BUILD_FLAGS="--release"
  - scripts/local/build
  stage: build-release
clippy:
  cache:
    key: ${CI_JOB_NAME}
    paths:
    - target
    - .cargo
  image: rust:latest
  script:
  - apt-get update
  - apt-get -y --no-install-recommends install libsystemd-dev
  - rustup component add clippy
  - cargo clippy --release -j 8 -- -D clippy::all
  stage: build
format:
  cache:
    key: ${CI_JOB_NAME}
    paths:
    - target
    - .cargo
    policy: pull
  image: rust:latest
  script:
  - apt-get update
  - apt-get -y --no-install-recommends install libsystemd-dev
  - rustup component add rustfmt
  - cargo fmt --all -- --check
  stage: build
services:
- docker:dind
stages:
- build
- build-release
system-test:
  artifacts:
    paths:
    - target/path/cinit
  cache:
    key: ${CI_JOB_NAME}
    paths:
    - target
    - .cargo
  image: docker:latest
  script:
  - scripts/local/build
  stage: build
test:
  cache:
    key: ${CI_JOB_NAME}
    paths:
    - target
    - .cargo
  image: rust:latest
  script:
  - apt-get update
  - apt-get -y --no-install-recommends install libsystemd-dev
  - ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime
  - cargo test
  stage: build
