before_script:
- python -V
- pip install pipenv
- pipenv install --dev
cache:
  paths:
  - $CI_PROJECT_DIR/.pipcache
  - $CI_PROJECT_DIR/.pipenvcache
  - $CI_PROJECT_DIR/.venv
  untracked: true
image: python:3.6.5
linting:
  except:
  - master
  script:
  - pipenv run pylint cli tests
  - pipenv run pycodestyle cli tests
  - pipenv run pydocstyle cli tests
  stage: Linting
package and release:
  artifacts:
    paths:
    - dist
  only:
  - master
  script:
  - pipenv run python setup.py bdist_wheel
  stage: Package & Release
pages:
  artifacts:
    paths:
    - public
  dependencies:
  - unit testing and coverage
  except:
  - master
  script:
  - mkdir -p public/coverage
  - cp -fr htmlcov/* public/coverage/
  stage: Coverage Reporting
stages:
- Unit tests & Coverage
- Coverage Reporting
- Linting
- Package & Release
unit testing and coverage:
  artifacts:
    expire_in: 1 day
    paths:
    - htmlcov
  coverage: /TOTAL.+ ([0-9]{1,3}%)/
  except:
  - master
  script:
  - pipenv run py.test --cov=cli -vv tests -s --cov-report html --cov-report term
  stage: Unit tests & Coverage
variables:
  GIT_STRATEGY: fetch
  PIPENV_CACHE_DIR: $CI_PROJECT_DIR/.pipenvcache
  PIPENV_VENV_IN_PROJECT: 'true'
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.pipcache
