code quality:
  script:
  - npm ci
  - npm run lint
  stage: test
coverage report:
  artifacts:
    paths:
    - public
  dependencies:
  - test & coverage
  environment:
    name: coverage report
    url: https://demsking.gitlab.io/image-downloader
  only:
  - master
  script:
  - mv coverage/lcov-report/ public/
  stage: publish
image: node:current-alpine
npm outdated:
  allow_failure: true
  script:
  - npm ci
  - npm outdated
  stage: test
package:
  artifacts:
    paths:
    - ./*.tgz
  script:
  - npm pack
  stage: publish
publish:
  environment:
    name: npm
    url: https://www.npmjs.com/package/image-downloader
  only:
  - tags
  - triggers
  script:
  - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
  - npm publish
  stage: publish
security scan:
  allow_failure: false
  script:
  - npm audit --production
  stage: test
stages:
- test
- publish
test & coverage:
  artifacts:
    paths:
    - coverage/
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  script:
  - npm it
  stage: test
test on nodejs lts:
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  image: node:lts-alpine
  script:
  - npm it
  stage: test
