download_deps_npm:
  artifacts:
    paths:
    - node_modules/
  script:
  - npm install
  stage: download-deps
  tags:
  - npm
hemsida:
  artifacts:
    name: hemsida
    paths:
    - public
  dependencies:
  - download_deps_npm
  script:
  - $(npm bin)/hexo generate
  stage: build
  tags:
  - npm
pages:
  artifacts:
    paths:
    - public
  dependencies:
  - hemsida
  only:
  - master
  script:
  - echo "Publicerar hemsida"
  stage: deploy
  tags:
  - npm
stages:
- download-deps
- build
- deploy
