cache:
  paths:
  - .cargo/
image: rust:latest
run-build:
  artifacts:
    paths:
    - target/debian/*.deb
  cache:
    paths:
    - .cargo/
    - target/
  image: rust:latest
  script:
  - echo $CARGO_HOME
  - cargo install diesel_cli
  - cargo install cargo-deb
  - diesel migration run
  - rustc --version && cargo --version
  - time cargo deb --verbose -- --jobs 1
  stage: build
  variables:
    DATABASE_URL: postgres://runner@postgres/diesel_example_db_1
services:
- postgres:latest
stages:
- build
variables:
  POSTGRES_DB: diesel_example_db_1
  POSTGRES_PASSWORD: ''
  POSTGRES_USER: runner
