build:
  artifacts:
    paths:
    - publish/
    - public/
    - tests/Jita.Tests/TestResults/
    reports:
      coverage_report:
        coverage_format: cobertura
        path: tests/Jita.Tests/TestResults/*/coverage.cobertura.xml
      junit: tests/Jita.Tests/TestResults/TestResults.xml
    when: always
  cache:
    key: $CI_PROJECT_ID
    paths:
    - .nuget
  coverage: /Line Coverage ([0-9.]+)%/
  script:
  - dotnet tool restore
  - dotnet fantomas --check src tests
  - dotnet build --packages .nuget/packages
  - apt-get update && apt-get install libxml2
  - dotnet test --no-build --collect:"XPlat Code Coverage" --logger:junit
  - sed -En '2s/.*line-rate="([01])\.([0-9]{2})([0-9]{0,2})[0-9]*".*/Line Coverage
    \1\2.\3%/p' tests/Jita.Tests/TestResults/*/coverage.cobertura.xml
  - dotnet reportgenerator -reports:"tests/Jita.Tests/TestResults/*/coverage.cobertura.xml"
    -targetdir:public/coverage
  - dotnet fsdocs build --strict --output public/docs
  - dotnet pack --no-restore -c Release -o publish
  stage: build
image: mcr.microsoft.com/dotnet/sdk:8.0
nuget:
  cache:
    key: $CI_PROJECT_ID
    paths:
    - .nuget
    policy: pull
  dependencies:
  - build
  only:
  - master
  script: echo publish/*nupkg | xargs -n1 dotnet nuget push --api-key $NUGET_API_KEY
    --source https://nuget.org
  stage: deploy
pages:
  artifacts:
    paths:
    - public
  dependencies:
  - build
  only:
  - master
  script: 'true'
  stage: deploy
stages:
- build
- deploy
