build:
  artifacts:
    paths:
    - _site
  script:
  - bundle install
  - bundle exec jekyll build
  stage: build
cache:
  key:
    files:
    - Gemfile.lock
  paths:
  - vendor/
check:
  allow_failure: true
  script:
  - bundle install
  - bundle exec htmlproofer _site
  stage: test
deploy:
  cache: []
  environment:
    name: production
    url: https://dashboard.render.com/static/srv-$RENDER_SERVICE_ID
  image: curlimages/curl
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
  - echo "Deploying to render.com ($RENDER_SERVICE_ID)..."
  - curl --fail "https://api.render.com/deploy/srv-$RENDER_SERVICE_ID?key=$RENDER_DEPLOY_HOOK_KEY&ref=$CI_COMMIT_SHA"
  stage: deploy
image: ruby:3
stages:
- build
- test
- deploy
variables:
  BUNDLE_PATH: vendor
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8
  NOKOGIRI_USE_SYSTEM_LIBRARIES: 'true'
workflow:
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
