build_binary:
  artifacts:
    expire_in: 1 week
    paths:
    - penguin-htdocs.deb
  image: registry.gitlab.com/chusiang/continuous-delivery-workshop/ubuntu:16.04
  script:
  - chmod 755 penguin-htdocs/DEBIAN
  - dpkg -b penguin-htdocs
  stage: build
  tags:
  - docker
deploy_to_dev:
  environment:
    name: staging
    url: http://stg.cdws.drx.tw:32180
  image: registry.gitlab.com/chusiang/continuous-delivery-workshop/ansible:2.5.3
  only:
  - master@drx-tw/cdws-2.0-team-b
  - develop@drx-tw/cdws-2.0-team-b
  - tags@drx-tw/cdws-2.0-team-b
  script:
  - ls
  - cd ansible-playbooks/
  - echo "${VAULT_KEY}" > secret.txt
  - ansible-playbook deploy.yml
  - rm -f secret.txt
  stage: deploy
  tags:
  - docker
release_to_prd:
  environment:
    name: production
    url: http://cdws.drx.tw:32280
  image: registry.gitlab.com/chusiang/continuous-delivery-workshop/ansible:2.5.3
  only:
  - master@drx-tw/cdws-2.0-team-b
  - tags@drx-tw/cdws-2.0-team-b
  script:
  - cd ansible-playbooks/
  - echo "${VAULT_KEY}" > secret.txt
  - ansible-playbook -i production deploy.yml
  - rm -f secret.txt
  stage: release
  tags:
  - docker
stages:
- try
- build
- deploy
- test
- release
test_dev:
  environment:
    name: staging
    url: http://stg.cdws.drx.tw:32180
  image: registry.gitlab.com/chusiang/continuous-delivery-workshop/ansible:2.5.3
  only:
  - master@drx-tw/cdws-2.0-team-b
  - develop@drx-tw/cdws-2.0-team-b
  - tags@drx-tw/cdws-2.0-team-b
  script:
  - cd ansible-playbooks/
  - echo "${VAULT_KEY}" > secret.txt
  - ansible-playbook test.yml
  - rm -f secret.txt
  stage: test
  tags:
  - docker
try_hchsfox:
  image: ubuntu:16.04
  script:
  - echo "hello word hchsfox1"
  stage: try
  tags:
  - docker
try_kc:
  image: ubuntu:16.04
  script:
  - echo "Hello, KC!!"
  stage: try
  tags:
  - docker
try_kc_2:
  image: ubuntu:16.04
  script:
  - echo "Hello, KC!!"
  stage: try
  tags:
  - docker
try_my_lab:
  image: registry.gitlab.com/chusiang/continuous-delivery-workshop/ubuntu:16.04
  script:
  - echo "Hello Blues"
  - pwd
  stage: try
  tags:
  - docker
try_rock:
  image: ubuntu:16.04
  script:
  - echo "Hello World"
  stage: try
  tags:
  - docker
