.custom_functions: "export VERSION=$(echo $CI_COMMIT_SHA | cut -c8-25)\nexport SECRET_NAME=tls-$CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG\n\
  export REPLICAS=3\nexport TRACK=stable\n\nfunction config_kubernetes() {\n  kubectl\
  \ config set-cluster $KUBE_NAME --server=\"$KUBE_URL\" --insecure-skip-tls-verify=true\n\
  \  kubectl config set-credentials cluster-admin --username=\"$KUBE_USER\" --password=\"\
  $KUBE_PASSWORD\"\n  kubectl config set-context default --cluster=$KUBE_NAME --user=cluster-admin\n\
  \  kubectl config use-context default\n}\n\nfunction create_ssl_secret() {\n  ##\
  \ Check if we are using SSL\n  if [[ \"$USE_SSL\" != \"True\" ]]; then\n    return\n\
  \  fi\n  \n  ## Check if secret name already exists\n  if [[ $SECRET_NAME == $(kubectl\
  \ get secret $SECRET_NAME -o jsonpath=\"{.metadata.name}\") ]]; then \n    kubectl\
  \ delete secret $SECRET_NAME\n  fi\n\n  kubectl create secret generic $SECRET_NAME\
  \ --from-file=tls.key=ssl_certs/privkey.pem --from-file=tls.crt=ssl_certs/fullchain.pem\n\
  }\n  \nfunction create_deployment_files() {\n  ## Deployment file substitutions\n\
  \  sed 's/_APP_NAME_/'\"$CI_PROJECT_NAME\"'/g; s/_VERSION_/'\"$VERSION\"'/g; s/_CI_ENVIRONMENT_SLUG_/'\"\
  $CI_ENVIRONMENT_SLUG\"'/g; s/_PROJECT_NAME_/'\"$GCP_PROJECT_ID\"'/g; s/_REPLICAS_/'\"\
  $REPLICAS\"'/g; s/_TRACK_/'\"$TRACK\"'/g;' kubernetes.tpl.deployment.yaml > deployment.yaml;\n\
  \  \n  ## Ingress file substitutions\n  if [[ \"$USE_SSL\" != \"True\" ]]; then\n\
  \    sed 's/_APP_NAME_/'\"$CI_PROJECT_NAME\"'/g; s/_CI_ENVIRONMENT_SLUG_/'\"$CI_ENVIRONMENT_SLUG\"\
  '/g; s/_MY_DOMAIN_/'\"$MY_DOMAIN\"'/g;' kubernetes.tpl.ingress.yaml > ingress.yaml;\n\
  \  else\n    sed 's/_APP_NAME_/'\"$CI_PROJECT_NAME\"'/g; s/_CI_ENVIRONMENT_SLUG_/'\"\
  $CI_ENVIRONMENT_SLUG\"'/g; s/_MY_DOMAIN_/'\"$MY_DOMAIN\"'/g;' kubernetes.tpl.ingress-ssl.yaml\
  \ > ingress.yaml;\n  fi\n  \n  ## Service file substitutions\n  sed 's/_APP_NAME_/'\"\
  $CI_PROJECT_NAME\"'/g; s/_CI_ENVIRONMENT_SLUG_/'\"$CI_ENVIRONMENT_SLUG\"'/g;' kubernetes.tpl.service.yaml\
  \ > service.yaml;\n}\n\nfunction apply_and_rollout() {\n  cat deployment.yaml\n\
  \  cat service.yaml\n  cat ingress.yaml\n  kubectl apply -f deployment.yaml\n  kubectl\
  \ apply -f service.yaml\n  kubectl apply -f ingress.yaml\n  kubectl rollout status\
  \ -f deployment.yaml\n  kubectl get all,ing -l app=$CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG\n\
  }\n"
before_script:
- "export VERSION=$(echo $CI_COMMIT_SHA | cut -c8-25)\nexport SECRET_NAME=tls-$CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG\n\
  export REPLICAS=3\nexport TRACK=stable\n\nfunction config_kubernetes() {\n  kubectl\
  \ config set-cluster $KUBE_NAME --server=\"$KUBE_URL\" --insecure-skip-tls-verify=true\n\
  \  kubectl config set-credentials cluster-admin --username=\"$KUBE_USER\" --password=\"\
  $KUBE_PASSWORD\"\n  kubectl config set-context default --cluster=$KUBE_NAME --user=cluster-admin\n\
  \  kubectl config use-context default\n}\n\nfunction create_ssl_secret() {\n  ##\
  \ Check if we are using SSL\n  if [[ \"$USE_SSL\" != \"True\" ]]; then\n    return\n\
  \  fi\n  \n  ## Check if secret name already exists\n  if [[ $SECRET_NAME == $(kubectl\
  \ get secret $SECRET_NAME -o jsonpath=\"{.metadata.name}\") ]]; then \n    kubectl\
  \ delete secret $SECRET_NAME\n  fi\n\n  kubectl create secret generic $SECRET_NAME\
  \ --from-file=tls.key=ssl_certs/privkey.pem --from-file=tls.crt=ssl_certs/fullchain.pem\n\
  }\n  \nfunction create_deployment_files() {\n  ## Deployment file substitutions\n\
  \  sed 's/_APP_NAME_/'\"$CI_PROJECT_NAME\"'/g; s/_VERSION_/'\"$VERSION\"'/g; s/_CI_ENVIRONMENT_SLUG_/'\"\
  $CI_ENVIRONMENT_SLUG\"'/g; s/_PROJECT_NAME_/'\"$GCP_PROJECT_ID\"'/g; s/_REPLICAS_/'\"\
  $REPLICAS\"'/g; s/_TRACK_/'\"$TRACK\"'/g;' kubernetes.tpl.deployment.yaml > deployment.yaml;\n\
  \  \n  ## Ingress file substitutions\n  if [[ \"$USE_SSL\" != \"True\" ]]; then\n\
  \    sed 's/_APP_NAME_/'\"$CI_PROJECT_NAME\"'/g; s/_CI_ENVIRONMENT_SLUG_/'\"$CI_ENVIRONMENT_SLUG\"\
  '/g; s/_MY_DOMAIN_/'\"$MY_DOMAIN\"'/g;' kubernetes.tpl.ingress.yaml > ingress.yaml;\n\
  \  else\n    sed 's/_APP_NAME_/'\"$CI_PROJECT_NAME\"'/g; s/_CI_ENVIRONMENT_SLUG_/'\"\
  $CI_ENVIRONMENT_SLUG\"'/g; s/_MY_DOMAIN_/'\"$MY_DOMAIN\"'/g;' kubernetes.tpl.ingress-ssl.yaml\
  \ > ingress.yaml;\n  fi\n  \n  ## Service file substitutions\n  sed 's/_APP_NAME_/'\"\
  $CI_PROJECT_NAME\"'/g; s/_CI_ENVIRONMENT_SLUG_/'\"$CI_ENVIRONMENT_SLUG\"'/g;' kubernetes.tpl.service.yaml\
  \ > service.yaml;\n}\n\nfunction apply_and_rollout() {\n  cat deployment.yaml\n\
  \  cat service.yaml\n  cat ingress.yaml\n  kubectl apply -f deployment.yaml\n  kubectl\
  \ apply -f service.yaml\n  kubectl apply -f ingress.yaml\n  kubectl rollout status\
  \ -f deployment.yaml\n  kubectl get all,ing -l app=$CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG\n\
  }\n"
build:
  image: google/cloud-sdk
  script:
  - echo "$GCP_SERVICE_KEY" > gcloud-service-key.json
  - gcloud auth activate-service-account --key-file gcloud-service-key.json
  - gcloud config set project $GCP_PROJECT_ID
  - gcloud builds submit . --config=cloudbuild.yaml --substitutions _IMAGE_NAME=$CI_PROJECT_NAME,_VERSION=$(echo
    $CI_COMMIT_SHA | cut -c8-25)
  services:
  - docker:dind
  stage: build
deploy_review:
  environment:
    name: review/$CI_COMMIT_REF_NAME
    on_stop: stop_review
    url: https://$CI_ENVIRONMENT_SLUG.$CI_PROJECT_NAME.$MY_DOMAIN
  except:
  - master
  image: google/cloud-sdk
  only:
  - branches
  script:
  - echo "Deploy a review app $CI_ENVIRONMENT_SLUG - $CI_COMMIT_REF_NAME"
  - config_kubernetes
  - create_ssl_secret
  - create_deployment_files
  - apply_and_rollout
  stage: deploy
deploy_stage:
  environment:
    name: prod
    url: https://$CI_ENVIRONMENT_SLUG.$CI_PROJECT_NAME.$MY_DOMAIN
  image: google/cloud-sdk
  only:
  - tags
  script:
  - echo "Deploy to production server"
  - config_kubernetes
  - create_ssl_secret
  - create_deployment_files
  - apply_and_rollout
  stage: deploy
image: docker:latest
stages:
- test
- build
- deploy
stop_review:
  environment:
    action: stop
    name: review/$CI_COMMIT_REF_NAME
  script:
  - echo "Remove review app"
  - kubectl version
  - kubectl delete ing -l app=$CI_ENVIRONMENT_SLUG
  - kubectl delete all -l app=$CI_ENVIRONMENT_SLUG
  stage: deploy
  variables:
    GIT_STRATEGY: none
  when: manual
test:
  script: echo "Running tests"
  stage: test
