build:
  artifacts:
    expire_in: 30 minutes
    paths:
    - dist
  image: node:10.13.0
  script:
  - rm package-lock.json
  - npm install
  - npm run build-prod
  stage: build
deploy:
  image: python:latest
  only:
  - master
  script:
  - pip install awscli
  - aws s3 cp ./dist/BrawlDB-Frontend/ s3://brawldb-beta/ --recursive --include "*"
  - aws cloudfront create-invalidation --distribution-id E17VAWVQQ0YUPI --paths /*
  stage: deploy
  when: manual
stages:
- build
- deploy
