before_script:
- apk add --no-cache bash
- docker version
build-napi:
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  - source build.env
  - ./ci_build_image.sh
  stage: build
build-tester-images:
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  - source build.env
  - cd tests
  - docker compose build
  - docker compose push
  stage: build
  when: manual
image: docker:27.5.1
pages:
  artifacts:
    expire_in: 30 days
    paths:
    - public
  only:
  - master
  script:
  - mv tests/coverage/ public/
  stage: pages
services:
- docker:dind
stages:
- build
- test
- pages
unittest:
  artifacts:
    paths:
    - tests/coverage/
  script:
  - apk add --no-cache jq
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  - source build.env
  - cd tests
  - ./run_unit_tests.sh
  stage: test
