.daily-rules:
  rules:
  - if: $CI_COMMIT_REF_NAME=="master" && $CI_PIPELINE_SOURCE=="schedule" && $SCHEDULE_TYPE=="daily"
.docker-template:
  before_script: &id001
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  image: docker
  script: &id002
  - docker build --pull -t "$CI_REGISTRY_IMAGE/$IMAGE_NAME" -f $IMAGE_FAMILY_NAME/$IMAGE_NAME
    .
  - docker push "$CI_REGISTRY_IMAGE/$IMAGE_NAME"
  services: &id003
  - docker:dind
  tags: &id004
  - saas-linux-medium-amd64
r-3.1-0:
  before_script: *id001
  image: docker
  rules:
  - changes:
    - r-old/r-3.1.0
    if: $CI_COMMIT_REF_NAME=="master" && $CI_PIPELINE_SOURCE=="push"
  script: *id002
  services: *id003
  stage: level1
  tags: *id004
  variables:
    IMAGE_FAMILY_NAME: r-old
    IMAGE_NAME: r-3.1.0
r-3.2-0:
  before_script: *id001
  image: docker
  rules:
  - changes:
    - r-old/r-3.2.0
    if: $CI_COMMIT_REF_NAME=="master" && $CI_PIPELINE_SOURCE=="push"
  script: *id002
  services: *id003
  stage: level1
  tags: *id004
  variables:
    IMAGE_FAMILY_NAME: r-old
    IMAGE_NAME: r-3.2.0
r-3.3-0:
  before_script: *id001
  image: docker
  rules:
  - changes:
    - r-old/r-3.3.0
    if: $CI_COMMIT_REF_NAME=="master" && $CI_PIPELINE_SOURCE=="push"
  script: *id002
  services: *id003
  stage: level1
  tags: *id004
  variables:
    IMAGE_FAMILY_NAME: r-old
    IMAGE_NAME: r-3.3.0
r-base:
  before_script: *id001
  image: docker
  rules:
  - changes:
    - r-base/r-base-minimal
    - r-base/r-base-gcc
    - r-base/r-base
    if: $CI_COMMIT_REF_NAME=="master" && $CI_PIPELINE_SOURCE=="push"
  script: *id002
  services: *id003
  stage: level3
  tags: *id004
  variables:
    IMAGE_FAMILY_NAME: r-base
    IMAGE_NAME: r-base
r-base-alpine:
  before_script: *id001
  image: docker
  rules:
  - changes:
    - r-base/r-base-alpine
    if: $CI_COMMIT_REF_NAME=="master" && $CI_PIPELINE_SOURCE=="push"
  script: *id002
  services: *id003
  stage: level1
  tags: *id004
  variables:
    IMAGE_FAMILY_NAME: r-base
    IMAGE_NAME: r-base-alpine
r-base-gcc:
  before_script: *id001
  image: docker
  rules:
  - changes:
    - r-base/r-base-minimal
    - r-base/r-base-gcc
    if: $CI_COMMIT_REF_NAME=="master" && $CI_PIPELINE_SOURCE=="push"
  script: *id002
  services: *id003
  stage: level2
  tags: *id004
  variables:
    IMAGE_FAMILY_NAME: r-base
    IMAGE_NAME: r-base-gcc
r-base-minimal:
  before_script: *id001
  image: docker
  rules:
  - changes:
    - r-base/r-base-minimal
    if: $CI_COMMIT_REF_NAME=="master" && $CI_PIPELINE_SOURCE=="push"
  script: *id002
  services: *id003
  stage: level1
  tags: *id004
  variables:
    IMAGE_FAMILY_NAME: r-base
    IMAGE_NAME: r-base-minimal
r-data.table:
  before_script: *id001
  image: docker
  rules:
  - changes:
    - r-base/r-base-minimal
    - r-base/r-base-gcc
    - r-base/r-base
    - r-data.table/r-data.table
    if: $CI_COMMIT_REF_NAME=="master" && $CI_PIPELINE_SOURCE=="push"
  script: *id002
  services: *id003
  stage: level4
  tags: *id004
  variables:
    IMAGE_FAMILY_NAME: r-data.table
    IMAGE_NAME: r-data.table
r-devel:
  before_script: *id001
  image: docker
  rules:
  - changes:
    - r-devel/r-devel-minimal
    - r-devel/r-devel
    if: $CI_COMMIT_REF_NAME=="master" && $CI_PIPELINE_SOURCE=="push"
  script: *id002
  services: *id003
  stage: level2
  tags: *id004
  variables:
    IMAGE_FAMILY_NAME: r-devel
    IMAGE_NAME: r-devel
r-devel-clang:
  before_script: *id001
  image: docker
  rules:
  - changes:
    - r-devel/r-devel-clang
    if: $CI_COMMIT_REF_NAME=="master" && $CI_PIPELINE_SOURCE=="push"
  script: *id002
  services: *id003
  stage: level1
  tags: *id004
  variables:
    IMAGE_FAMILY_NAME: r-devel
    IMAGE_NAME: r-devel-clang
r-devel-gcc:
  before_script: *id001
  image: docker
  rules:
  - changes:
    - r-devel/r-devel-gcc
    if: $CI_COMMIT_REF_NAME=="master" && $CI_PIPELINE_SOURCE=="push"
  script: *id002
  services: *id003
  stage: level1
  tags: *id004
  variables:
    IMAGE_FAMILY_NAME: r-devel
    IMAGE_NAME: r-devel-gcc
r-devel-gcc-strict:
  before_script: *id001
  image: docker
  rules:
  - changes:
    - r-devel/r-devel-gcc-strict
    if: $CI_COMMIT_REF_NAME=="master" && $CI_PIPELINE_SOURCE=="push"
  script: *id002
  services: *id003
  stage: level1
  tags: *id004
  variables:
    IMAGE_FAMILY_NAME: r-devel
    IMAGE_NAME: r-devel-gcc-strict
r-devel-minimal:
  before_script: *id001
  image: docker
  rules:
  - changes:
    - r-devel/r-devel-minimal
    if: $CI_COMMIT_REF_NAME=="master" && $CI_PIPELINE_SOURCE=="push"
  script: *id002
  services: *id003
  stage: level1
  tags: *id004
  variables:
    IMAGE_FAMILY_NAME: r-devel
    IMAGE_NAME: r-devel-minimal
r-pkgdown:
  before_script: *id001
  image: docker
  rules:
  - changes:
    - r-base/r-base-minimal
    - r-base/r-base-gcc
    - r-base/r-base
    - r-pkgdown/r-pkgdown
    if: $CI_COMMIT_REF_NAME=="master" && $CI_PIPELINE_SOURCE=="push"
  script: *id002
  services: *id003
  stage: level4
  tags: *id004
  variables:
    IMAGE_FAMILY_NAME: r-pkgdown
    IMAGE_NAME: r-pkgdown
stages:
- level1
- level2
- level3
- level4
