before_script:
- pip3 install -r requirements.txt
build:
  script:
  - which nosetests
  - python3 setup.py install --user
  stage: build
deploy:
  only:
  - master
  script:
  - bash push_pypi.sh
  stage: deploy
image: rubdos/python3-clang
stages:
- build
- test
- deploy
static-analysis:
  script:
  - coala-ci
  stage: test
unit-tests:
  script:
  - nosetests
  stage: test
