backend_tests:
  artifacts:
    expire_in: 1 month
    paths:
    - backend/coverage
  image: ruby:2.7.0
  script:
  - apt-get update -qq && apt-get install -y -qq postgresql postgresql-contrib libpq-dev
    cmake gpsbabel
  - ruby -v
  - which ruby
  - cd /builds/pikatrack/pikatrack/backend
  - bundle install
  - cp config/database.yml.example config/database.yml
  - cp config/secrets.yml.example config/secrets.yml
  - RAILS_ENV=test bundle exec rails db:schema:load
  - RAILS_ENV=test bundle exec rspec
  stage: test
build_image:
  image: docker:git
  only:
  - tags
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker build -t $IMAGE_TAG .
  - docker push $IMAGE_TAG
  services:
  - docker:dind
  stage: build
frontend_tests:
  script:
  - apt-get install curl
  - curl -sL https://deb.nodesource.com/setup_13.x | bash -
  - apt-get install nodejs
  - cd frontend
  - npm install
  - npm run lint
  stage: test
services:
- postgres:latest
- mdillon/postgis:latest
stages:
- test
- build
variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  POSTGRES_DB: pikatrack_test
  POSTGRES_PASSWORD: ''
  POSTGRES_USER: pikatrack
