before_script:
- npm -v
- node -v
- pwd
- ls -l
gulp_build:
  script:
  - gulp build
  stage: gulp
gulp_e2e:
  script:
  - gulp protractor
  stage: gulp
gulp_test:
  script:
  - gulp test
  stage: gulp
image: pijzl/docker-node-karma-protractor-chrome
install:
  artifacts:
    expire_in: 1 week
    paths:
    - node_modules/
    - bower_components/
  script:
  - npm install
  - bower install  --allow-root
  stage: dependences
stages:
- dependences
- gulp
