.build-template:
  artifacts: &id001
    expire_in: 1 week
    name: $CI_JOB_NAME
    paths:
    - _install_ci
    - config/Makefile
    - test-suite/misc/universes/all_stdlib.v
  script: &id002
  - set -e
  - echo 'start:coq.config'
  - ./configure -prefix "$(pwd)/_install_ci" ${EXTRA_CONF}
  - echo 'end:coq.config'
  - echo 'start:coq.build'
  - make -j ${NJOBS} byte
  - make -j ${NJOBS}
  - make test-suite/misc/universes/all_stdlib.v
  - echo 'end:coq:build'
  - echo 'start:coq.install'
  - make install
  - make install-byte
  - cp bin/fake_ide _install_ci/bin/
  - echo 'end:coq.install'
  - set +e
  stage: build
.ci-template:
  dependencies: &id003
  - build
  script: &id004
  - set -e
  - echo 'start:coq.test'
  - make -f Makefile.ci -j ${NJOBS} ${TEST_TARGET}
  - echo 'end:coq.test'
  - set +e
  stage: test
  variables: &id005
    EXTRA_PACKAGES: $TIMING_PACKAGES
    TEST_TARGET: $CI_JOB_NAME
.test-suite-template:
  artifacts: &id006
    name: $CI_JOB_NAME.logs
    paths:
    - test-suite/logs
    when: on_failure
  script: &id007
  - cd test-suite
  - make clean
  - BIN=$(readlink -f ../_install_ci/bin)/
  - LIB=$(readlink -f ../_install_ci/lib/coq)/
  - make -j ${NJOBS} BIN="$BIN" LIB="$LIB" all
  stage: test
.validate-template:
  script: &id008
  - cd _install_ci
  - find lib/coq/ -name '*.vo' -print0 > vofiles
  - for regexp in 's/.vo//' 's:lib/coq/plugins:Coq:' 's:lib/coq/theories:Coq:' 's:/:.:g';
    do sed -z -i "$regexp" vofiles; done
  - xargs -0 --arg-file=vofiles bin/coqchk -boot -silent -o -m -coqlib lib/coq/
  stage: test
.warnings-template:
  dependencies: &id009 []
  script: &id010
  - set -e
  - echo 'start:coq.config'
  - ./configure -local ${EXTRA_CONF}
  - echo 'end:coq.config'
  - echo 'start:coq.build'
  - make -j ${NJOBS} coqocaml
  - echo 'end:coq:build'
  - set +e
  stage: test
  variables: &id011
    EXTRA_CONF: -native-compiler yes -coqide byte -byte-only
    EXTRA_OPAM: $COQIDE_OPAM
    EXTRA_PACKAGES: $COQIDE_PACKAGES
before_script:
- ls
- printenv
- if [ -n "${EXTRA_PACKAGES}" ]; then sudo apt-get update -qq && sudo apt-get install
  -y -qq ${EXTRA_PACKAGES}; fi
- if [ -n "${PIP_PACKAGES}" ]; then sudo pip3 install ${PIP_PACKAGES}; fi
- if [ ! "(" -d .opamcache ")" ]; then mv ~/.opam .opamcache; else mv ~/.opam ~/.opam-old;
  fi
- ln -s $(readlink -f .opamcache) ~/.opam
- opam repository set-url default https://opam.ocaml.org
- opam update
- opam switch ${COMPILER}
- eval $(opam config env)
- opam config list
- opam install -j ${NJOBS} -y camlp5.${CAMLP5_VER} ocamlfind num ${EXTRA_OPAM}
- rm -rf ~/.opam/log/
- opam list
build:
  artifacts: *id001
  script: *id002
  stage: build
  variables:
    EXTRA_CONF: -native-compiler yes -coqide opt -with-doc yes
    EXTRA_OPAM: $COQIDE_OPAM $COQDOC_OPAM
    EXTRA_PACKAGES: $COQIDE_PACKAGES $COQDOC_PACKAGES
    PIP_PACKAGES: $SPHINX_PACKAGES
build:32bit:
  artifacts: *id001
  script: *id002
  stage: build
  variables:
    COMPILER: $COMPILER_32BIT
    EXTRA_CONF: -native-compiler yes
    EXTRA_PACKAGES: gcc-multilib
build:bleeding-edge:
  artifacts: *id001
  script: *id002
  stage: build
  variables:
    CAMLP5_VER: $CAMLP5_VER_BLEEDING_EDGE
    COMPILER: $COMPILER_BLEEDING_EDGE
    EXTRA_CONF: -native-compiler yes -coqide opt
    EXTRA_OPAM: $COQIDE_OPAM_BE
    EXTRA_PACKAGES: $COQIDE_PACKAGES
cache:
  paths:
  - .opamcache
ci-bignums:
  dependencies: *id003
  script: *id004
  stage: test
  variables: *id005
ci-color:
  dependencies: *id003
  script: *id004
  stage: test
  variables:
    EXTRA_PACKAGES: $TIMING_PACKAGES
    TEST_TARGET: $CI_JOB_NAME
ci-compcert:
  dependencies: *id003
  script: *id004
  stage: test
  variables: *id005
ci-coq-dpdgraph:
  dependencies: *id003
  script: *id004
  stage: test
  variables:
    EXTRA_OPAM: ocamlgraph
    EXTRA_PACKAGES: $TIMING_PACKAGES autoconf
    TEST_TARGET: $CI_JOB_NAME
ci-coquelicot:
  dependencies: *id003
  script: *id004
  stage: test
  variables:
    EXTRA_PACKAGES: $TIMING_PACKAGES autoconf
    TEST_TARGET: $CI_JOB_NAME
ci-elpi:
  dependencies: *id003
  script: *id004
  stage: test
  variables:
    EXTRA_OPAM: ppx_tools_versioned ppx_deriving ocaml-migrate-parsetree
    EXTRA_PACKAGES: $TIMING_PACKAGES
    TEST_TARGET: $CI_JOB_NAME
ci-equations:
  dependencies: *id003
  script: *id004
  stage: test
  variables: *id005
ci-fiat-parsers:
  dependencies: *id003
  script: *id004
  stage: test
  variables:
    EXTRA_PACKAGES: $TIMING_PACKAGES
    TEST_TARGET: $CI_JOB_NAME
ci-flocq:
  dependencies: *id003
  script: *id004
  stage: test
  variables:
    EXTRA_PACKAGES: $TIMING_PACKAGES autoconf
    TEST_TARGET: $CI_JOB_NAME
ci-formal-topology:
  dependencies: *id003
  script: *id004
  stage: test
  variables: *id005
ci-geocoq:
  allow_failure: true
  dependencies: *id003
  script: *id004
  stage: test
  variables: *id005
ci-hott:
  dependencies: *id003
  script: *id004
  stage: test
  variables:
    EXTRA_PACKAGES: $TIMING_PACKAGES autoconf
    TEST_TARGET: $CI_JOB_NAME
ci-iris-lambda-rust:
  dependencies: *id003
  script: *id004
  stage: test
  variables: *id005
ci-ltac2:
  dependencies: *id003
  script: *id004
  stage: test
  variables: *id005
ci-math-classes:
  dependencies: *id003
  script: *id004
  stage: test
  variables: *id005
ci-math-comp:
  dependencies: *id003
  script: *id004
  stage: test
  variables: *id005
ci-sf:
  dependencies: *id003
  script: *id004
  stage: test
  variables:
    EXTRA_PACKAGES: $TIMING_PACKAGES wget
    TEST_TARGET: $CI_JOB_NAME
ci-unimath:
  dependencies: *id003
  script: *id004
  stage: test
  variables: *id005
ci-vst:
  dependencies: *id003
  script: *id004
  stage: test
  variables: *id005
image: ocaml/opam:ubuntu
stages:
- build
- test
test-suite:
  artifacts: *id006
  dependencies:
  - build
  script: *id007
  stage: test
  variables:
    EXTRA_PACKAGES: $TIMING_PACKAGES
test-suite:32bit:
  artifacts: *id006
  dependencies:
  - build:32bit
  script: *id007
  stage: test
  variables:
    COMPILER: $COMPILER_32BIT
    EXTRA_PACKAGES: gcc-multilib $TIMING_PACKAGES
test-suite:bleeding-edge:
  artifacts: *id006
  dependencies:
  - build:bleeding-edge
  script: *id007
  stage: test
  variables:
    CAMLP5_VER: $CAMLP5_VER_BLEEDING_EDGE
    COMPILER: $COMPILER_BLEEDING_EDGE
    EXTRA_PACKAGES: $TIMING_PACKAGES
validate:
  dependencies:
  - build
  script: *id008
  stage: test
validate:32bit:
  dependencies:
  - build:32bit
  script: *id008
  stage: test
  variables:
    COMPILER: $COMPILER_32BIT
    EXTRA_PACKAGES: gcc-multilib
variables:
  CAMLP5_VER: '6.14'
  CAMLP5_VER_BLEEDING_EDGE: '7.03'
  COMPILER: system
  COMPILER_32BIT: 4.02.3+32bit
  COMPILER_BLEEDING_EDGE: 4.06.0
  COQDOC_OPAM: hevea
  COQDOC_PACKAGES: texlive-latex-base texlive-latex-recommended texlive-latex-extra
    texlive-math-extra texlive-fonts-recommended texlive-fonts-extra latex-xcolor
    ghostscript transfig imagemagick tipa python3-pip
  COQIDE_OPAM: lablgtk-extras
  COQIDE_OPAM_BE: lablgtk.2.18.6 lablgtk-extras.1.6
  COQIDE_PACKAGES: libgtk2.0-dev libgtksourceview2.0-dev
  NJOBS: '2'
  SPHINX_PACKAGES: bs4 sphinx sphinx_rtd_theme pexpect antlr4-python3-runtime sphinxcontrib-bibtex
  TIMING_PACKAGES: time python
warnings:
  dependencies: *id009
  script: *id010
  stage: test
  variables: *id011
warnings:bleeding-edge:
  dependencies: *id009
  script: *id010
  stage: test
  variables:
    CAMLP5_VER: $CAMLP5_VER_BLEEDING_EDGE
    COMPILER: $COMPILER_BLEEDING_EDGE
    EXTRA_CONF: -native-compiler yes -coqide byte -byte-only
    EXTRA_OPAM: $COQIDE_OPAM_BE
    EXTRA_PACKAGES: $COQIDE_PACKAGES
