before_script:
- dotnet restore
build:
  script:
  - cd $build_path
  - dotnet build
  stage: build
  variables:
    build_path: $project
image: fsharp:netcore
stages:
- build
- test
test:
  script:
  - cd $test_path
  - dotnet add package coverlet.msbuild
  - dotnet test /p:CollectCoverage=true
  stage: test
  variables:
    test_path: $tests
variables:
  project: Source
  tests: Tests
