.bst_artifact_push_settings_template: "mkdir -p /etc/ssl/CAS\nif [ -n \"$GITLAB_CAS_PUSH_CERT\"\
  \ ] && [ -n \"$GITLAB_CAS_PUSH_KEY\" ]; then\n    echo \"$GITLAB_CAS_PUSH_CERT\"\
  \ > /etc/ssl/CAS/server.crt\n    echo \"$GITLAB_CAS_PUSH_KEY\" > /etc/ssl/CAS/server.key\n\
  \n    echo \"projects:\" >> ~/.config/buildstream.conf\n    echo \"  libreml:\"\
  \ >> ~/.config/buildstream.conf\n    echo \"    artifacts:\" >> ~/.config/buildstream.conf\n\
  \    echo \"      url: https://${LIBREML_CACHE_SERVER_ADDRESS}\" >> ~/.config/buildstream.conf\n\
  \    echo \"      client-key: ${LIBREML_CACHE_SERVER_KEY}\" >> ~/.config/buildstream.conf\n\
  \    echo \"      client-cert: ${LIBREML_CACHE_SERVER_CERT}\" >> ~/.config/buildstream.conf\n\
  \    echo \"      push: true\" >> ~/.config/buildstream.conf\nfi\n"
.build_bst_artifact_template:
  artifacts: &id001
    paths:
    - ${BST_LOGS}
    - ${OUTPUT_DIR}
    when: always
  rules: &id002
  - if: $CI_COMMIT_BRANCH == 'master'
  - if: $CI_MERGE_REQUEST_ID
  script: &id003
  - "mkdir -p /etc/ssl/CAS\nif [ -n \"$GITLAB_CAS_PUSH_CERT\" ] && [ -n \"$GITLAB_CAS_PUSH_KEY\"\
    \ ]; then\n    echo \"$GITLAB_CAS_PUSH_CERT\" > /etc/ssl/CAS/server.crt\n    echo\
    \ \"$GITLAB_CAS_PUSH_KEY\" > /etc/ssl/CAS/server.key\n\n    echo \"projects:\"\
    \ >> ~/.config/buildstream.conf\n    echo \"  libreml:\" >> ~/.config/buildstream.conf\n\
    \    echo \"    artifacts:\" >> ~/.config/buildstream.conf\n    echo \"      url:\
    \ https://${LIBREML_CACHE_SERVER_ADDRESS}\" >> ~/.config/buildstream.conf\n  \
    \  echo \"      client-key: ${LIBREML_CACHE_SERVER_KEY}\" >> ~/.config/buildstream.conf\n\
    \    echo \"      client-cert: ${LIBREML_CACHE_SERVER_CERT}\" >> ~/.config/buildstream.conf\n\
    \    echo \"      push: true\" >> ~/.config/buildstream.conf\nfi\n"
  - ${BST} -o target_arch ${ARCH} -o blas_impl ${BLAS_IMPL} build ${BST_ARTIFACT}
  - test 1 -eq ${NO_CHECKOUT} || ${BST} -o target_arch ${ARCH} -o blas_impl ${BLAS_IMPL}
    checkout ${BST_ARTIFACT} ${OUTPUT_DIR}
  stage: build
.docker_deploy_template:
  before_script: &id004 []
  image: docker:stable
  rules: &id005
  - if: $CI_COMMIT_BRANCH == 'master'
  - if: $CI_COMMIT_TAG
  script: &id006
  - export DOCKER_HOST=tcp://docker:2375/
  - export DOCKER_IMAGE=${CI_REGISTRY_IMAGE}/${ARCH}:${CI_COMMIT_REF_SLUG}
  - docker load -i ${OUTPUT_DIR}/libreml.tar ${DOCKER_IMAGE}
  - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
  - echo ${DOCKER_IMAGE}
  - docker push ${DOCKER_IMAGE}
  services: &id007
  - docker:dind
  stage: package
.track_artifact_deps_template:
  before_script: &id008
  - url_host=`git remote get-url origin | sed -e "s#https://gitlab-ci-token:.*@##g"`
  - git remote set-url origin "https://gitlab-ci-token:${LIBREML_GIT_KEY}@${url_host}"
  image: $X86_IMAGE
  rules: &id009
  - if: $CI_PIPELINE_SOURCE == "schedule"
  script: &id010
  - git config user.name "LibreML"
  - git config user.email "libreml@libreml.com"
  - git branch master origin/master
  - GITLAB_TOKEN=$LIBREML_API_KEY auto_updater --verbose --nobuild --overwrite --push
    --create_mr --gitlab_project="libreml/libreml" $BST_ARTIFACT
  stage: update
before_script:
- mkdir -p ~/.config
- "cat > ~/.config/buildstream.conf << EOF\n# Get a lot of output in case of errors\n\
  logging:\n  error-lines: 80\nEOF\n"
build_libreml_openblas_aarch64:
  artifacts: *id001
  image: $ARM64_IMAGE
  rules: *id002
  script: *id003
  stage: build
  tags:
  - arm
  variables:
    ARCH: aarch64
    BLAS_IMPL: openblas
    BST_ARTIFACT: libreml.bst
build_libreml_openblas_x86-64:
  artifacts: *id001
  image: $X86_IMAGE
  rules: *id002
  script: *id003
  stage: build
  tags:
  - high_load
  variables:
    ARCH: x86_64
    BLAS_IMPL: openblas
    BST_ARTIFACT: libreml.bst
docker_deploy_aarch64:
  before_script: *id004
  dependencies:
  - build_libreml_openblas_aarch64
  image: docker:stable
  rules: *id005
  script: *id006
  services: *id007
  stage: package
  variables:
    ARCH: aarch64
docker_deploy_x86-64:
  before_script: *id004
  dependencies:
  - build_libreml_openblas_x86-64
  image: docker:stable
  rules: *id005
  script: *id006
  services: *id007
  stage: package
  variables:
    ARCH: x86_64
docker_test:
  before_script: []
  dependencies:
  - build_libreml_openblas_x86-64
  image: docker:stable
  rules:
  - if: $CI_COMMIT_BRANCH == 'master'
  - if: $CI_MERGE_REQUEST_ID
  script:
  - export DOCKER_HOST=tcp://docker:2375/
  - docker load -i ${OUTPUT_DIR}/libreml.tar ${DOCKER_IMAGE}
  - docker run -w /examples -v $(pwd)/examples:/examples ${DOCKER_IMAGE} ./run_examples.sh
  services:
  - docker:dind
  stage: package
  variables:
    DOCKER_IMAGE: ${CI_REGISTRY_IMAGE}/libreml:${CI_COMMIT_REF_SLUG}
stages:
- update
- build
- testing
- push
- compose_libreml
- package
track_libreml_deps:
  before_script: *id008
  image: $X86_IMAGE
  rules: *id009
  script: *id010
  stage: update
  variables:
    BST_ARTIFACT: libreml.bst
variables:
  ARM64_IMAGE: registry.gitlab.com/freedesktop-sdk/infrastructure/freedesktop-sdk-docker-images/bst14/arm64:e60e2dccd1ac4e928d62472676762d8e3e4a1406
  BST: bst --colors
  BST_LOGS: ${CI_PROJECT_DIR}/cache/buildstream/logs
  GET_SOURCES_ATTEMPTS: 3
  LIBREML_CACHE_SERVER_ADDRESS: push.public.aws.celduin.co.uk
  OUTPUT_DIR: output
  X86_IMAGE: registry.gitlab.com/freedesktop-sdk/infrastructure/freedesktop-sdk-docker-images/bst14/amd64:e60e2dccd1ac4e928d62472676762d8e3e4a1406
  XDG_CACHE_HOME: ${CI_PROJECT_DIR}/cache
