before_script:
- mkdir -p _ccache
- export CCACHE_BASEDIR=${PWD}
- export CCACHE_DIR=${PWD}/_ccache
build:
  artifacts:
    expire_in: 1 week
    paths:
    - build/xfce4-sntray-plugin*.tar.xz
  image: archlinux:base
  script:
  - pacman -Syy --noconfirm glibc libwnck3 gtk3 vala cmake git base-devel clang ninja
    xfce4-panel mate-panel budgie-desktop gobject-introspection meson
  - git clone https://gitlab.com/vala-panel-project/cmake-vala.git
  - cd cmake-vala && cmake . -DCMAKE_INSTALL_PREFIX=/usr -GNinja && ninja install
    && cd .. && rm -rf cmake-vala
  - git clone https://gitlab.com/vala-panel-project/vala-panel.git
  - meson --prefix=/usr vp-build vala-panel && meson install -C vp-build && rm -rf
    vala-panel && rm -rf vp-build
  - mkdir build && cd build && cmake .. -DCMAKE_INSTALL_PREFIX=/usr -GNinja
  - ninja
  - ninja install
  - ninja dist
  stage: build
cache:
  paths:
  - _ccache/
release-main:
  image: alpine:edge
  only:
  - tags
  script:
  - apk add --no-cache python3 py3-pip
  - pip3 install gitlab_release
  - python3 -m gitlab_release ${PRIVATE_TOKEN} build/xfce4-sntray-plugin*.tar.xz
  stage: release
stages:
- build
- release
