build:build-docker:dark-sky:
  image: $DOCKER_BUILD_IMAGE
  only:
  - tags
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY
  - docker-compose build dark-sky
  - docker-compose push dark-sky
  stage: build
build:build-docker:elasticsearch:
  image: $DOCKER_BUILD_IMAGE
  only:
  - tags
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY
  - docker-compose build elasticsearch
  - docker-compose push elasticsearch
  stage: build
build:build-docker:geomar-wetter:
  image: $DOCKER_BUILD_IMAGE
  only:
  - tags
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY
  - docker-compose build geomar-wetter
  - docker-compose push geomar-wetter
  stage: build
build:build-docker:grafana:
  image: $DOCKER_BUILD_IMAGE
  only:
  - tags
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY
  - docker-compose build grafana
  - docker-compose push grafana
  stage: build
build:build-docker:kiel-opendata:
  image: $DOCKER_BUILD_IMAGE
  only:
  - tags
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY
  - docker-compose build kiel-opendata
  - docker-compose push kiel-opendata
  stage: build
build:build-docker:kiel-parkhaeuser:
  image: $DOCKER_BUILD_IMAGE
  only:
  - tags
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY
  - docker-compose build kiel-parkhaeuser
  - docker-compose push kiel-parkhaeuser
  stage: build
build:build-docker:kiel-photos:
  image: $DOCKER_BUILD_IMAGE
  only:
  - tags
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY
  - docker-compose build kiel-photos
  - docker-compose push kiel-photos
  stage: build
build:build-docker:luftdaten-info:
  image: $DOCKER_BUILD_IMAGE
  only:
  - tags
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY
  - docker-compose build luftdaten-info
  - docker-compose push luftdaten-info
  stage: build
build:build-docker:orion-grafana-proxy:
  image: $DOCKER_BUILD_IMAGE
  only:
  - tags
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY
  - docker-compose build orion-grafana-proxy
  - docker-compose push orion-grafana-proxy
  stage: build
build:build-docker:prometheus:
  image: $DOCKER_BUILD_IMAGE
  only:
  - tags
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY
  - docker-compose build prometheus
  - docker-compose push prometheus
  stage: build
build:build-docker:ratsprotokolle:
  image: $DOCKER_BUILD_IMAGE
  only:
  - tags
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY
  - docker-compose build ratsprotokolle
  - docker-compose push ratsprotokolle
  stage: build
build:build-docker:ship-data-ais-forwarder:
  image: $DOCKER_BUILD_IMAGE
  only:
  - tags
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY
  - docker-compose build ship-data-ais-forwarder
  - docker-compose push ship-data-ais-forwarder
  stage: build
build:build-docker:ship-data-provider:
  image: $DOCKER_BUILD_IMAGE
  only:
  - tags
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY
  - docker-compose build ship-data-provider
  - docker-compose push ship-data-provider
  stage: build
build:build-docker:swkielnetz-iot:
  image: $DOCKER_BUILD_IMAGE
  only:
  - tags
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY
  - docker-compose build swkielnetz-iot
  - docker-compose push swkielnetz-iot
  stage: build
deploy:integration:
  environment:
    name: integration
    url: https://integration.kiel-data-hub.de/
  image: kroniak/ssh-client:3.6
  only:
  - tags
  script:
  - source deploy.sh integration
  stage: deploy
  variables:
    DEPLOYMENT_SERVER: $INTEGRATION_SERVER
deploy:production:
  environment:
    name: production
    url: https://app.kiel-data-hub.de/
  image: kroniak/ssh-client:3.6
  only:
  - tags
  script:
  - source deploy.sh production
  stage: deploy
  variables:
    DEPLOYMENT_SERVER: $PRODUCTION_SERVER
  when: manual
services:
- docker:dind
stages:
- build
- deploy
variables:
  DOCKER_BUILD_IMAGE: tmaier/docker-compose:18.06
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  ELASTICSEARCH_PROVISIONING_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH/elasticsearch-provisioning:$CI_COMMIT_TAG
  REGISTRY: registry.gitlab.com
