before_script:
- mkdir -p ${GOPATH}/src/${GO_PROJECT}
- mkdir -p ${CI_PROJECT_DIR}/${ARTIFACTS_DIR}
- go get -u github.com/golang/dep/cmd/dep
- cp -r ${CI_PROJECT_DIR}/* ${GOPATH}/src/${GO_PROJECT}/
- cd ${GOPATH}/src/${GO_PROJECT}
- dep ensure
build:
  script:
  - go build -o ${CI_PROJECT_DIR}/${ARTIFACTS_DIR}/${BIN_NAME}
  stage: build
image: golang
stages:
- test
- build
testacc:
  script:
  - TF_ACC=true go test -v .
  stage: test
unit_tests:
  script:
  - go test -v -cover .
  stage: test
variables:
  ARTIFACTS_DIR: artifacts
  BIN_NAME: pterraform-provider-jira
  GO_PROJECT: gitlab.com/gappan/pterraform-provider-jira
