package:api:
  before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  image: docker:latest
  only:
  - master
  script:
  - cd api
  - docker build --tag $DOCKER_USERNAME/fore-scorer-api:${CI_COMMIT_SHA} .
  - docker push $DOCKER_USERNAME/fore-scorer-api:${CI_COMMIT_SHA}
  services:
  - docker:dind
  stage: package
package:app:
  before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  image: docker:latest
  only:
  - master
  script:
  - cd app
  - docker build --tag $DOCKER_USERNAME/fore-scorer-app:${CI_COMMIT_SHA} .
  - docker push $DOCKER_USERNAME/fore-scorer-app:${CI_COMMIT_SHA}
  services:
  - docker:dind
  stage: package
release:api:
  before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  image: docker:latest
  only:
  - master
  script:
  - docker pull $DOCKER_USERNAME/fore-scorer-api:${CI_COMMIT_SHA}
  - docker tag $DOCKER_USERNAME/fore-scorer-api:${CI_COMMIT_SHA} $DOCKER_USERNAME/fore-scorer-api:latest
  - docker push $DOCKER_USERNAME/fore-scorer-api:latest
  services:
  - docker:dind
  stage: release
release:app:
  before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  image: docker:latest
  only:
  - master
  script:
  - docker pull $DOCKER_USERNAME/fore-scorer-app:${CI_COMMIT_SHA}
  - docker tag $DOCKER_USERNAME/fore-scorer-app:${CI_COMMIT_SHA} $DOCKER_USERNAME/fore-scorer-app:latest
  - docker push $DOCKER_USERNAME/fore-scorer-app:latest
  services:
  - docker:dind
  stage: release
stages:
- build
- test
- package
- release
test:api:
  image: microsoft/dotnet:2.0.0-sdk
  script:
  - cd api/test && dotnet test
  stage: test
test:app:
  before_script:
  - cd app
  - npm ci
  image: node:alpine
  script:
  - npm run lint
  - npm run test:unit
  stage: test
test:app:e2e:
  artifacts:
    expire_in: 1 week
    name: $CI_JOB_NAME-$CI_COMMIT_REF_NAME
    paths:
    - app/tests/e2e/videos
    when: on_failure
  before_script:
  - cd app
  - npm ci
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
    - .cache/
  image: cypress/base:10
  script:
  - npm run test:e2e:ci
  stage: test
  variables:
    CYPRESS_CACHE_FOLDER: ${CI_PROJECT_DIR}/.cache/Cypress
variables:
  npm_config_cache: ${CI_PROJECT_DIR}/.cache/npm
