.build_docker_image:
  before_script: &id001
  - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin "$CI_REGISTRY"
  image: docker:24.0.5
  script: &id002
  - docker buildx build --platform linux/amd64 -t registry.gitlab.com/bagage/batimap/$CONTAINER:$CI_COMMIT_REF_SLUG
    -f ${BASE_DIR:-$CONTAINER}/$DOCKERFILE ${BASE_DIR:-$CONTAINER}
  - "if test $CI_COMMIT_REF_NAME = master; then\n  echo docker tag registry.gitlab.com/bagage/batimap/$CONTAINER:$CI_COMMIT_REF_SLUG\
    \ registry.gitlab.com/bagage/batimap/$CONTAINER:latest\n  docker tag registry.gitlab.com/bagage/batimap/$CONTAINER:$CI_COMMIT_REF_SLUG\
    \ registry.gitlab.com/bagage/batimap/$CONTAINER:latest\n  echo docker push registry.gitlab.com/bagage/batimap/$CONTAINER:latest\n\
    \  docker push registry.gitlab.com/bagage/batimap/$CONTAINER:latest\n  echo docker\
    \ push registry.gitlab.com/bagage/batimap/$CONTAINER:$CI_COMMIT_REF_SLUG\n  docker\
    \ push registry.gitlab.com/bagage/batimap/$CONTAINER:$CI_COMMIT_REF_SLUG\nfi\n"
  services: &id003
  - command:
    - --tls=false
    name: docker:24.0.5-dind
  stage: build
  variables:
    DOCKER_BUILDKIT: 1
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ''
.docker_vars:
  DOCKER_BUILDKIT: 1
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ''
build:back:
  before_script: *id001
  image: docker:24.0.5
  only:
    changes:
    - .gitlab-ci.yml
    - back/**/*
    refs:
    - merge_requests
    - master
  script: *id002
  services: *id003
  stage: build
  variables:
    CONTAINER: back
    DOCKERFILE: Dockerfile
    DOCKER_BUILDKIT: 1
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ''
build:ci_test_back:
  before_script: *id001
  image: docker:24.0.5
  only:
    changes:
    - .gitlab-ci.yml
    - back/**/*
    refs:
    - merge_requests
    - master
  script: *id002
  services: *id003
  stage: build
  variables:
    BASE_DIR: back
    CONTAINER: ci-test-back
    DOCKERFILE: Dockerfile.ci
    DOCKER_BUILDKIT: 1
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ''
build:ci_test_front:
  before_script: *id001
  image: docker:24.0.5
  only:
    changes:
    - .gitlab-ci.yml
    - front/**/*
    refs:
    - merge_requests
    - master
  script: *id002
  services: *id003
  stage: build
  variables:
    BASE_DIR: front
    CONTAINER: ci-test-front
    DOCKERFILE: Dockerfile.ci
    DOCKER_BUILDKIT: 1
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ''
build:front:
  before_script: *id001
  image: docker:24.0.5
  only:
    changes:
    - .gitlab-ci.yml
    - front/**/*
    refs:
    - merge_requests
    - master
  script: *id002
  services: *id003
  stage: build
  variables:
    CONTAINER: front
    DOCKERFILE: Dockerfile
    DOCKER_BUILDKIT: 1
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ''
build:imposm:
  before_script: *id001
  image: docker:24.0.5
  only:
    changes:
    - .gitlab-ci.yml
    - imposm/**/*
    refs:
    - merge_requests
    - master
  script: *id002
  services: *id003
  stage: build
  variables:
    CONTAINER: imposm
    DOCKERFILE: Dockerfile
    DOCKER_BUILDKIT: 1
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ''
build:imposm-watcher:
  before_script: *id001
  image: docker:24.0.5
  only:
    changes:
    - .gitlab-ci.yml
    - imposm-watcher/**/*
    refs:
    - merge_requests
    - master
  script: *id002
  services: *id003
  stage: build
  variables:
    CONTAINER: imposm-watcher
    DOCKERFILE: Dockerfile
    DOCKER_BUILDKIT: 1
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ''
build:postgis:
  before_script: *id001
  image: docker:24.0.5
  only:
    changes:
    - .gitlab-ci.yml
    - postgis/**/*
    refs:
    - merge_requests
    - master
  script: *id002
  services: *id003
  stage: build
  variables:
    CONTAINER: postgis
    DOCKERFILE: Dockerfile
    DOCKER_BUILDKIT: 1
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ''
build:tiles:
  before_script: *id001
  image: docker:24.0.5
  only:
    changes:
    - .gitlab-ci.yml
    - tiles/**/*
    refs:
    - merge_requests
    - master
  script: *id002
  services: *id003
  stage: build
  variables:
    CONTAINER: tiles
    DOCKERFILE: Dockerfile
    DOCKER_BUILDKIT: 1
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ''
build:tiles-cleaner:
  before_script: *id001
  image: docker:24.0.5
  only:
    changes:
    - .gitlab-ci.yml
    - tiles-cleaner/**/*
    refs:
    - merge_requests
    - master
  script: *id002
  services: *id003
  stage: build
  variables:
    CONTAINER: tiles-cleaner
    DOCKERFILE: Dockerfile
    DOCKER_BUILDKIT: 1
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ''
stages:
- build
- test
test:back:
  before_script:
  - cd back/
  - pip install uv==0.8.11
  image: registry.gitlab.com/bagage/batimap/ci-test-back
  only:
    changes:
    - .gitlab-ci.yml
    - back/**/*
    refs:
    - merge_requests
  script:
  - sed -i 's/psycopg2 =/psycopg2-binary =/' pyproject.toml
  - uv sync --dev
  - uv run pre-commit  run --all-files --show-diff-on-failure
  - uv run pytest --color=yes -v -rf
  services:
  - alias: postgis
    name: registry.gitlab.com/bagage/batimap/postgis
  - alias: redis
    name: redis:5-alpine
  stage: test
  variables:
    POSTGRES_DB: testdb
    POSTGRES_HOST_AUTH_METHOD: trust
    POSTGRES_PASSWORD: batimap
    POSTGRES_URI: postgresql://test:batimap@postgis:5432/testdb
    POSTGRES_USER: test
    REDIS_URI: redis://redis
test:front:
  artifacts:
    reports:
      junit: front/src/junit_karma.xml
  before_script:
  - yarn config set cache-folder cache-ci
  cache:
    paths:
    - cache-ci/
    untracked: true
  image: registry.gitlab.com/bagage/batimap/ci-test-front
  only:
    changes:
    - .gitlab-ci.yml
    - front/**/*
    refs:
    - merge_requests
  script:
  - cd front/
  - yarn
  - yarn lint
  - yarn prettier --check
  - yarn test --karma-config karma-ci.conf.js
  stage: test
test:front:buildprod:
  before_script:
  - yarn config set cache-folder cache-ci
  cache:
    paths:
    - cache-ci/
    untracked: true
  image: registry.gitlab.com/bagage/batimap/ci-test-front
  only:
    changes:
    - .gitlab-ci.yml
    - front/**/*
    refs:
    - merge_requests
  script:
  - cd front/
  - yarn
  - yarn build --prod
  stage: test
