image: library/node:9.11.1
installPackages:
  artifacts:
    paths:
    - node_modules
  script: npm i
  stage: setup
lintJS:
  script: npm run lint-js
  stage: test
lintSolidity:
  script: npm run lint-solidity
  stage: test
publishPackage:
  only:
    refs:
    - master
    variables:
    - $CI_COMMIT_MESSAGE =~ /^release version*/i
  script:
  - npm run deploy
  - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
  - npm publish
  stage: deploy
runTests:
  script:
  - npm test
  stage: test
stages:
- setup
- test
- deploy
