.elixir:
  before_script:
  - cd core
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  image: elixir:latest
.js:
  before_script:
  - cd web-ui
  - yarn install
  image: node:latest
core test:
  extends: .elixir
  only:
    changes:
    - core/**/*
  script:
  - mix test
  services:
  - postgres:latest
  stage: test
  variables:
    POSTGRES_DB: guildship_test
    POSTGRES_HOST: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres
deploy core:
  environment: production
  extends: .elixir
  only:
    changes:
    - core/**/*
    refs:
    - master
  script:
  - mix compile
  stage: deploy
deploy web:
  environment: production
  extends: .js
  only:
    changes:
    - web-ui/**/*
    refs:
    - master
  script:
  - yarn build
  stage: deploy
stages:
- test
- deploy
web test:
  extends: .js
  only:
    changes:
    - web-ui/**/*
  script:
  - yarn test
  stage: test
