.gcloud: &id001
- echo $GCLOUD_SERVICE_KEY | base64 --decode -i > ~/gcloud-service-key.json
- gcloud auth activate-service-account --key-file ~/gcloud-service-key.json
- gcloud --quiet container clusters get-credentials $CLOUDSDK_CONTAINER_CLUSTER
.prod_deploy:
  before_script: *id001
  environment: production
  image: google/cloud-sdk
  script: &id003
  - kubectl patch deployment $PRODUCTION_SERVICE_NAME -p '{"spec":{"template":{"spec":{"containers":[{"name":"'"$PRODUCTION_SERVICE_NAME"'","image":"'"$CI_REGISTRY_IMAGE:$CI_BUILD_REF"'"}]}}}}'
  stage: production
.staging_deploy:
  before_script: *id001
  environment: staging
  image: google/cloud-sdk
  script: &id002
  - kubectl patch deployment $STAGING_SERVICE_NAME -p '{"spec":{"template":{"spec":{"containers":[{"name":"'"$STAGING_SERVICE_NAME"'","image":"'"$CI_REGISTRY_IMAGE:$CI_BUILD_REF"'"}]}}}}'
  stage: staging
auto-deploy-master:
  before_script: *id001
  environment: staging
  image: google/cloud-sdk
  only:
  - master
  script: *id002
  stage: staging
auto-deploy-tags:
  before_script: *id001
  environment: production
  image: google/cloud-sdk
  only:
  - tags
  script: *id003
  stage: production
before_script:
- docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
build:
  except:
  - tags
  script:
  - docker build --pull -t $CI_REGISTRY_IMAGE:$CI_BUILD_REF .
  - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF
  stage: build
deploy to production:
  before_script: *id001
  environment: production
  image: google/cloud-sdk
  only:
  - master
  script: *id003
  stage: production
  when: manual
deploy to staging:
  before_script: *id001
  environment: staging
  except:
  - master
  - tags
  image: google/cloud-sdk
  script: *id002
  stage: staging
  when: manual
image: docker:latest
release-by-name:
  except:
  - master
  script:
  - docker pull $CI_REGISTRY_IMAGE:$CI_BUILD_REF
  - docker tag $CI_REGISTRY_IMAGE:$CI_BUILD_REF $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
  - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF
  stage: release
release-master:
  only:
  - master
  script:
  - docker pull $CI_REGISTRY_IMAGE:$CI_BUILD_REF
  - docker tag $CI_REGISTRY_IMAGE:$CI_BUILD_REF $CI_REGISTRY_IMAGE:latest
  - docker push $CI_REGISTRY_IMAGE:latest
  stage: release
services:
- docker:dind
stages:
- build
- test
- release
- staging
- production
test1:
  before_script: []
  except:
  - tags
  image: $CI_REGISTRY_IMAGE:$CI_BUILD_REF
  script:
  - echo "test1"
  services: []
  stage: test
test2:
  before_script: []
  except:
  - tags
  image: $CI_REGISTRY_IMAGE:$CI_BUILD_REF
  script:
  - echo "test2"
  services: []
  stage: test
variables:
  DOCKER_DRIVER: overlay
