apt-deploy:
  artifacts:
    name: debian-package
    paths:
    - $DEBIAN_PACKAGE_DIR/*.deb
  before_script:
  - apt-get -qq update >/dev/null
  dependencies:
  - debian-package-build
  environment:
    name: production
    url: http://apt.nobodyinperson.de
  only:
  - tags
  script:
  - apt-get -y -qq install apt-transport-https >/dev/null
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_DEPLOY_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - echo "$SSH_DEPLOY_HOSTKEYS" >> ~/.ssh/known_hosts
  - scp -qP "$SSH_DEPLOY_PORT" "$DEBIAN_PACKAGE_DIR"/*.deb "$SSH_DEPLOY_ADDRESS"
  stage: deploy
  variables:
    GIT_STRATEGY: none
apt-install-test:
  before_script:
  - apt-get -qq update >/dev/null
  dependencies:
  - debian-package-build
  only:
  - tags
  script:
  - apt-get -y -qq install apt-transport-https wget >/dev/null
  - set -e
  - export DEBFILE=($DEBIAN_PACKAGE_DIR/*.deb)
  - 'echo "debian package file: $DEBFILE"'
  - export PACKAGE_NAME=$(dpkg -I $DEBFILE | perl -ne 'if(s/^\s*package:\s*(\S+)\s*$/$1/ig){print;exit}')
  - export PACKAGE_VERSION=$(dpkg -I $DEBFILE | perl -ne 'if(s/^\s*version:\s*(\S+)\s*$/$1/ig){print;exit}')
  - 'echo "built package version: $PACKAGE_VERSION"'
  - wget -qO- https://apt.nobodyinperson.de/gpg.key | apt-key add -
  - echo "deb https://apt.nobodyinperson.de unstable main" | tee /etc/apt/sources.list.d/nobodyinperson.list
  - apt-get update -qq
  - apt-get download -y -qq $PACKAGE_NAME
  - export APT_PACKAGE_VERSION=$(dpkg -I $PACKAGE_NAME*.deb | perl -ne 'if(s/^\s*version:\s*(\S+)\s*$/$1/ig){print;exit}')
  - 'echo "apt package version: $APT_PACKAGE_VERSION"'
  - test "$PACKAGE_VERSION" = "$APT_PACKAGE_VERSION"
  - apt-get install -y -qq $PACKAGE_NAME >/dev/null
  stage: deploy-test
  variables:
    GIT_STRATEGY: none
autoconf-build:
  artifacts:
    expire_in: 1 week
    paths:
    - '*-*.tar.gz'
  script:
  - autoreconf --install
  - ./configure
  - make
  - make dist
  - make distcheck
  - make install
  - make uninstall
  stage: build
before_script:
- apt-get -qq update >/dev/null
- apt-get -qq -y install r-cran-optparse libgtksourceview-3.0-dev >/dev/null
debian-package-build:
  artifacts:
    name: ${CI_JOB_STAGE}_${CI_COMMIT_REF_NAME}
    paths:
    - $DEBIAN_PACKAGE_DIR/*
  script:
  - autoreconf --install
  - dpkg-buildpackage -us -uc
  - mkdir -p $DEBIAN_PACKAGE_DIR
  - cp ../*.deb ../*.dsc ../*.changes $DEBIAN_PACKAGE_DIR
  stage: build
debian-package-install-uninstall:
  before_script:
  - apt-get -qq update >/dev/null
  dependencies:
  - debian-package-build
  image: ubuntu
  script:
  - dpkg -i $DEBIAN_PACKAGE_DIR/*.deb || true
  - dpkg -r $(dpkg -I $DEBIAN_PACKAGE_DIR/*.deb | perl -ne 'if(s/^\s*package:\s*(\w+)$/$1/ig){print;exit}')
  stage: install-test
  variables:
    GIT_STRATEGY: none
debian-package-test:
  before_script: []
  dependencies:
  - debian-package-build
  script:
  - dpkg-deb -I $DEBIAN_PACKAGE_DIR/*.deb
  - dpkg -c $DEBIAN_PACKAGE_DIR/*.deb
  - lintian --fail-on-warnings $DEBIAN_PACKAGE_DIR/*.deb
  stage: build-test
  variables:
    GIT_STRATEGY: none
image: registry.gitlab.com/nobodyinperson/simbuto/ubuntu_16.04
stages:
- build
- build-test
- install-test
- app-test
- deploy
- deploy-test
variables:
  DEBIAN_PACKAGE_DIR: debian-package
  GIT_SUBMODULE_STRATEGY: recursive
