before_script:
- export GRADLE_USER_HOME=`pwd`/.gradle
build:
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
    - build
    - .gradle
    policy: push
  script: gradle --build-cache assemble
  stage: build
image: registry.gitlab.com/pierreduchemin/save-diamond/gradle-openjfx-7zip
release:
  artifacts:
    paths:
    - build/jfx/app
  only:
  - tags
  script:
  - gradle jfxJar
  - jarsigner -keystore src/main/deploy/keystore.jks -storepass "$SAVE_DIAMOND_STOREPASS"
    build/jfx/app/save-diamond.jar save-diamond -tsa http://timestamp.comodoca.com
  stage: release
stages:
- build
- test
- release
test:
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
    - build
    - .gradle
    policy: pull
  script: gradle check
  stage: test
variables:
  GRADLE_OPTS: -Dorg.gradle.daemon=false
