cache:
  paths:
  - node_modules
image: node:16
pages:
  artifacts:
    paths:
    - public
  rules:
  - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
  - npm install -g harp less
  - harp source public
  stage: deploy
stages:
- test
- deploy
test:
  rules:
  - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
  - npm install -g harp less
  - harp source public
  stage: test
