build:
  artifacts:
    paths:
    - ./*.apk
  script:
  - ./gradlew assemble
  - cp ./app/build/outputs/apk/*/*.apk ./
  - ls ./*.apk
  stage: build
debug:
  artifacts:
    paths:
    - Navdy-MapDownloader-debug.apk
  script:
  - mv *debug*.apk Navdy-MapDownloader-debug.apk
  stage: outputs
image: registry.gitlab.com/alelec/docker-android
release:
  artifacts:
    paths:
    - Navdy-MapDownloader.apk
  script:
  - mv *release*.apk Navdy-MapDownloader.apk
  stage: outputs
stages:
- build
- outputs
