cache:
  paths:
  - /tmp/docker-cache
deploy:
  environment:
    name: staging
    url: https://stay-woke-catalyst.herokuapp.com/
  image: ruby:2.3.1
  only:
  - master
  script:
  - gem install dpl
  - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY --strategy='git
    ssh'
  stage: deploy
image: rtlong/docker
services:
- docker:1.12.1-dind
stages:
- test
- deploy
variables:
  DOCKER_CACHE_DIR: /tmp/docker-cache
