build_app:
  script:
  - npm config set user 0
  - npm config set unsafe-perm true
  - npm install -g polymer-cli bower
  - bower cache clean --allow-root
  - bower install --allow-root
  - bower prune --allow-root
  - polymer build
  stage: build
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
  - build/default
deploy_production:
  environment:
    name: production
    url: https://memeservices.com
  only:
  - master
  script:
  - npm config set user 0
  - npm config set unsafe-perm true
  - npm install -g firebase-tools
  - pwd && ls
  - ls build
  - cd build
  - ls
  - firebase use --token $FIREBASE_PROD_KEY default
  - firebase deploy --non-interactive --token $FIREBASE_PROD_KEY
  stage: deploy
image: node:latest
stages:
- build
- deploy
