code quality:
  artifacts:
    reports:
      codequality: gl-codequality.json
  script:
  - npm ci
  - npm install --save-dev eslint eslint-formatter-gitlab
  - npm run lint -- --format gitlab .
  stage: test
image: node:lts-alpine
outdated:
  allow_failure: true
  script:
  - npm outdated
  stage: dependencies
package:
  artifacts:
    paths:
    - ./*.tgz
  only:
  - tags
  script:
  - npm pack
  stage: build
publish on npm:
  environment:
    name: npm
    url: https://www.npmjs.com/package/@formschema/native
  needs:
  - package
  - rollup build
  only:
  - tags
  - triggers
  script:
  - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
  - npm publish
  stage: publish
rollup build:
  artifacts:
    expire_in: 4 weeks
    paths:
    - dist
  script:
  - npm ci
  - npm run build
  stage: build
security scan:
  allow_failure: false
  script:
  - npm i -g npm
  - npm audit --production
  stage: dependencies
stages:
- test
- dependencies
- build
- publish
test & coverage:
  artifacts:
    reports:
      junit:
      - junit.xml
    when: always
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  script:
  - npm ci
  - npm i -D jest-junit
  - npm test -- --ci --reporters=default --reporters=jest-junit
  stage: test
