sign_off:
  before_script:
  - apk add --no-cache git
  image: ${GITLAB_CI_IMAGE_ALPINE}
  needs: []
  script: 'git log --grep "^Signed-off-by: .\+<.\+\(@\| at \).\+\(\.\| dot \).\+>$"
    --invert-grep --format="Detected commit ''%h'' with missing or bad sign-off! Please
    read ''CONTRIBUTING.md''." --exit-code $(rev=$(git rev-parse -q --verify "$GITLAB_CI_SIGN_OFF_EXCLUDE^{commit}")
    && echo "$rev..")'
  stage: static
stages:
- static
static_ansible:
  image: ${GITLAB_CI_IMAGE_ANSIBLE}
  needs: []
  script:
  - ansible-playbook -i production.dist/inventory/hosts --syntax-check -vvv site.yml
  - ansible-lint
  stage: static
variables:
  GITLAB_CI_IMAGE_ALPINE: alpine:3.16.0
  GITLAB_CI_IMAGE_ANSIBLE: librespace/ansible:9.13.0
  GITLAB_CI_SIGN_OFF_EXCLUDE: 560ebadf7353fd458be7bfd2eb08546465cc1e71
