build:
  artifacts:
    paths:
    - ./cljfmt
  image: mrroman/graalvm-ce
  script:
  - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
  - bash ./lein
  - bash ./lein uberjar
  - native-image -jar target/cljfmt-graalvm-0.1.0-SNAPSHOT-standalone.jar -H:Name="cljfmt"
  stage: release
stages:
- release
