image: th0br0/iota-buildenv:latest
stages:
- test
test32:
  script:
  - tools/ci/build.sh 32
  stage: test
test64:
  script:
  - tools/ci/build.sh 64
  stage: test
variables:
  GIT_SUBMODULE_STRATEGY: recursive
