before_script:
- if [ -d .git ]; then echo "is git dir"; else git clone $CI_REPOSITORY_URL . ; fi;
- rm -f .git/index.lock
- rm -f .git/shallow.lock
- rm -f .git/HEAD.lock
- rm -f .git/hocks/post-checkout
- git remote set-url origin $CI_REPOSITORY_URL
- git fetch origin --prune +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
- git checkout -f -q $CI_COMMIT_SHA
- if [ ! -z "${SOURCE_PROJECT}" -a "${SOURCE_PROJECT}" != " " ]; then echo "THIS SEEMS
  TO BE A MERGE PIPELINE FROM ${SOURCE_PROJECT}/${SOURCE_BRANCH}"; git pull "https://gitlab.com/${SOURCE_PROJECT}/game.git"
  "${SOURCE_BRANCH}"; fi;
- git submodule update --init --recursive
- git status
- if [ -d target ]; then ls -la target; fi;
build-headless:
  script:
  - (cd headless && cargo build)
  stage: build
build-login-cli:
  script:
  - (cd login-cli && cargo build)
  stage: build
build-server-cli:
  script:
  - (cd server-cli && cargo build)
  stage: build
build-voxygen:
  script:
  - (cd voxygen && cargo build)
  stage: build
clean-code:
  script:
  - rustup component add rustfmt-preview
  - cargo fmt --all -- --check
  stage: build
clippy:
  allow_failure: true
  script:
  - rustup component add clippy-preview --toolchain=nightly
  - cargo clippy --all -- -D clippy || echo "This job is disabled, because we are
    not activly using it now, so we dont want to see yellow failed partly"
  stage: post-run
coverage:
  script:
  - if cargo install --list | grep -i "cargo-tarpaulin"; then echo "tarpaulin already
    installed"; else RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin;
    fi
  - cargo tarpaulin --skip-clean --all --exclude headless || echo "There is a problem
    in tarpaulin which sometimes fails"
  stage: post-run
nightly-linux-debug:
  artifacts:
    expire_in: 1 week
    paths:
    - nightly-linux-debug.tar.bz2
  only:
    refs:
    - master
  script:
  - (cd voxygen && cargo build)
  - (cd server-cli && cargo build)
  - (cd headless && cargo build)
  - rm -r -f nightly/client
  - rm -r -f nightly
  - mkdir nightly
  - mkdir nightly/client
  - cp target/debug/server-cli nightly/client/
  - cp target/debug/voxygen nightly/client/
  - cp target/debug/headless nightly/client/
  - cp -r voxygen/assets nightly/
  - cp -r voxygen/shaders nightly/client/
  - rm -f nightly-linux-debug.tar.bz2
  - tar -cvjSf nightly-linux-debug.tar.bz2 nightly
  stage: deploy
  when: always
nightly-linux-optimized:
  artifacts:
    expire_in: 2 days
    paths:
    - nightly-linux-optimized.tar.bz2
  only:
    refs:
    - master
  script:
  - (cd voxygen && cargo build --release)
  - (cd server-cli && cargo build --release)
  - (cd headless && cargo build --release)
  - rm -r -f nightly/client
  - rm -r -f nightly
  - mkdir nightly
  - mkdir nightly/client
  - cp target/release/server-cli nightly/client/
  - cp target/release/voxygen nightly/client/
  - cp target/release/headless nightly/client/
  - cp -r voxygen/assets nightly/
  - cp -r voxygen/shaders nightly/client/
  - rm -f nightly-linux-optimized.tar.bz2
  - tar -cvjSf nightly-linux-optimized.tar.bz2 nightly
  stage: deploy
  when: manual
nightly-windows-debug:
  artifacts:
    expire_in: 1 week
    paths:
    - nightly-windows-debug.zip
  only:
    refs:
    - master
  script:
  - (cd voxygen && cargo build --target=x86_64-pc-windows-gnu)
  - (cd server-cli && cargo build --target=x86_64-pc-windows-gnu)
  - (cd headless && cargo build --target=x86_64-pc-windows-gnu)
  - rm -r -f nightly/client
  - rm -r -f nightly
  - mkdir nightly
  - mkdir nightly/client
  - cp target/x86_64-pc-windows-gnu/debug/server-cli.exe nightly/client/
  - cp target/x86_64-pc-windows-gnu/debug/voxygen.exe nightly/client/
  - cp target/x86_64-pc-windows-gnu/debug/headless.exe nightly/client/
  - cp -r voxygen/assets nightly/
  - cp -r voxygen/shaders nightly/client/
  - rm -f nightly-windows-debug.zip
  - zip -r nightly-windows-debug.zip nightly
  stage: deploy
nightly-windows-optimized:
  artifacts:
    expire_in: 2 days
    paths:
    - nightly-windows-optimized.zip
  only:
    refs:
    - master
  script:
  - (cd voxygen && cargo build --release --target=x86_64-pc-windows-gnu)
  - (cd server-cli && cargo build --release --target=x86_64-pc-windows-gnu)
  - (cd headless && cargo build --release --target=x86_64-pc-windows-gnu)
  - rm -r -f nightly/client
  - rm -r -f nightly
  - mkdir nightly
  - mkdir nightly/client
  - cp target/x86_64-pc-windows-gnu/release/server-cli.exe nightly/client/
  - cp target/x86_64-pc-windows-gnu/release/voxygen.exe nightly/client/
  - cp target/x86_64-pc-windows-gnu/release/headless.exe nightly/client/
  - cp -r voxygen/assets nightly/
  - cp -r voxygen/shaders nightly/client/
  - rm -f nightly-windows-optimized.zip
  - zip -r nightly-windows-optimized.zip nightly
  stage: deploy
  when: manual
stable-linux-optimized:
  artifacts:
    expire_in: 30d
    paths:
    - stable-linux-optimized.tar.bz2
  only:
    refs:
    - /^v[0-9]+\.[0-9]+\.[0-9]+/
  script:
  - (cd voxygen && cargo build --release)
  - (cd server-cli && cargo build --release)
  - (cd headless && cargo build --release)
  - rm -r -f stable/client
  - rm -r -f stable
  - mkdir stable
  - mkdir stable/client
  - cp target/release/server-cli stable/client/
  - cp target/release/voxygen stable/client/
  - cp target/release/headless stable/client/
  - cp -r voxygen/assets stable/
  - cp -r voxygen/shaders nightly/client/
  - rm -f stable-linux-optimized.tar.bz2
  - tar -cvjSf stable-linux-optimized.tar.bz2 stable
  stage: deploy
stable-windows-optimized:
  artifacts:
    expire_in: 30d
    paths:
    - stable-windows-optimized.zip
  only:
    refs:
    - /^v[0-9]+\.[0-9]+\.[0-9]+/
  script:
  - (cd voxygen && cargo build --release --target=x86_64-pc-windows-gnu)
  - (cd server-cli && cargo build --release --target=x86_64-pc-windows-gnu)
  - (cd headless && cargo build --release --target=x86_64-pc-windows-gnu)
  - rm -r -f stable/client
  - rm -r -f stable
  - mkdir stable
  - mkdir stable/client
  - cp target/x86_64-pc-windows-gnu/release/server-cli.exe stable/client/
  - cp target/x86_64-pc-windows-gnu/release/voxygen.exe stable/client/
  - cp target/x86_64-pc-windows-gnu/release/headless.exe stable/client/
  - cp -r voxygen/assets stable/
  - cp -r voxygen/shaders nightly/client/
  - rm -f stable-windows-optimized.zip
  - zip -r stable-windows-optimized.zip stable
  stage: deploy
stages:
- build
- test
- deploy
- post-run
unittests:
  script:
  - cargo test
  stage: test
variables:
  GIT_STRATEGY: none
