image: docker:latest
maven-build:
  artifacts:
    paths:
    - news-rest/target/*.jar
  cache:
    key: rest-mvn
    paths:
    - .m2/
  image: maven:3-jdk-8-alpine
  script: mvn package -B -Dnews-api.apikey=$NEWS_APIKEY
  stage: build
maven-test:
  cache:
    key: rest-mvn
  image: maven:3-jdk-8-alpine
  script: mvn integration-test -B -Dnews-api.apikey=$NEWS_APIKEY
  stage: test
news-frontend-build:
  artifacts:
    paths:
    - news-frontend/dist/news-frontend/
  cache:
    key: news-frontend
    paths:
    - news-frontend/node_modules
  image: node:8-alpine
  script:
  - cd news-frontend
  - npm install
  - ./node_modules/@angular/cli/bin/ng build
  stage: build
news-frontend-docker-build:
  before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  dependencies:
  - news-frontend-build
  script:
  - docker build -t $DIMG_FRONTEND:latest news-frontend/
  - docker push $DIMG_FRONTEND:latest
  stage: docker-build
news-frontend-docker-release:
  before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  dependencies:
  - news-frontend-build
  only:
  - master
  script:
  - docker pull $DIMG_FRONTEND:latest
  - docker tag $DIMG_FRONTEND:latest $DIMG_FRONTEND:$CI_COMMIT_REF_SLUG
  - docker push $DIMG_FRONTEND:$CI_COMMIT_REF_SLUG
  stage: docker-release
news-frontend-docker-test:
  script:
  - docker pull $DIMG_FRONTEND:latest
  - docker run -e NEWS_API_URL="http://localhost:8080" -d $DIMG_FRONTEND:latest
  stage: docker-test
news-frontend-test:
  before_script:
  - Xvfb :0 -ac -screen 0 1024x768x24 &
  - export DISPLAY=:99
  cache:
    key: news-frontend
  image: registry.gitlab.com/dmejer/node-chrome-docker-img:master
  script:
  - cd news-frontend
  - rm package-lock.json
  - npm install
  - ./node_modules/@angular/cli/bin/ng test --watch=false --browsers ChromeHeadless
  stage: test
news-rest-docker-build:
  before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  cache:
    key: rest-mvn
  script:
  - docker build -t $DIMG_BACKEND:latest news-rest/
  - docker push $DIMG_BACKEND:latest
  stage: docker-build
news-rest-docker-release:
  before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  cache:
    key: rest-mvn
  only:
  - master
  script:
  - docker pull $DIMG_BACKEND:latest
  - docker tag $DIMG_BACKEND:latest $DIMG_BACKEND:$CI_COMMIT_REF_SLUG
  - docker push $DIMG_BACKEND:$CI_COMMIT_REF_SLUG
  stage: docker-release
news-rest-docker-test:
  script:
  - docker pull $DIMG_BACKEND:latest
  - docker run -p 8080:8080 -e news-api.apikey="$NEWS_APIKEY" -d $DIMG_BACKEND:latest
  stage: docker-test
services:
- docker:dind
stages:
- build
- test
- docker-build
- docker-test
- docker-release
variables:
  DIMG_BACKEND: registry.gitlab.com/dmejer/spring-angular-docker-example/news-rest
  DIMG_FRONTEND: registry.gitlab.com/dmejer/spring-angular-docker-example/news-frontend
  DOCKER_DRIVER: overlay2
  MAVEN_OPTS: -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2
  SPRING_PROFILES_ACTIVE: gitlab-ci
