.notify-common:
  image: node:carbon
  script: &id001
  - set -euo pipefail
  - apt update && apt install jq -y
  - CF_TOKEN=$(curl -s -u "${CF_TECHUSER_CLIENT_ID}:${CF_TECHUSER_CLIENT_SECRET}"
    -d "grant_type=client_credentials" -X POST "${CF_TECHUSER_OAUTH_ENDPOINT}" | jq
    -r -e '.access_token')
  - 'curl -s -X POST -H "Authorization: Bearer ${CF_TOKEN}" -H "Content-Type: application/json"
    --data '' { "body": {"message": "MindSphere devops-demo deployment successful:
    ''"${CI_ENVIRONMENT_NAME}"''"}, "recipientsTo": "''"${NOTIFICATION_EMAIL_ADDRESSES}"''",
    "from": "gitlab", "subject": "MindSphere devops-demo deployment: ''"${CI_ENVIRONMENT_NAME}"''"}
    '' "${CF_API_PUBLISH_EMAIL_ENDPOINT}"'
  stage: notify
mindsphere:
  before_script:
  - curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github"
    | tar -zx
  - mv cf /usr/local/bin
  - mkdir -p ~/.cf
  - echo "{\"ConfigVersion\":3,\"Target\":\"$CF_API\",\"AccessToken\":\"bearer ${CF_ACCESS_TOKEN}\",\"RefreshToken\":\"${CF_REFRESH_TOKEN}\"}"
    > ~/.cf/config.json
  environment:
    name: dev
  image: node:carbon
  only:
  - master
  script:
  - cf target -o "$CF_ORG" -s "$CF_SPACE_DEV"
  - yarn
  - yarn build:prod --no-progress
  - yarn --cwd server
  - cf push --var mdspTenant="$MDSP_TENANT" --var mdspRegion="$MDSP_REGION"
  stage: deploy
notify:
  environment:
    name: dev
  image: node:carbon
  only:
  - master
  script: *id001
  stage: notify
stages:
- test
- deploy
- notify
test:
  artifacts:
    reports:
      junit:
      - coverage/*.xml
      - test-reports/*.xml
  before_script:
  - apt-get update
  - apt-get -y install zip
  image: node:carbon
  script:
  - yarn
  - yarn commitlint
  - yarn lint
  - yarn build:prod --no-progress
  - yarn build:dev --no-progress
  - yarn test --no-progress --code-coverage
  - yarn --cwd server
  - yarn --cwd devops/devopsadmin
  - yarn --cwd agent
  - yarn license:all
  - export BASE_URL=http://$(hostname -i):3000
  - yarn e2e
  - yarn mdsp:zip
  services:
  - selenium/standalone-chrome:3.5.2
  - mongo:3.2
  stage: test
  variables:
    MONGODB_URL: mongodb://mongo:27017/e2e
    SELENIUM_URL: http://selenium__standalone-chrome:4444/wd/hub
