cache:
  paths:
  - node_modules/
coverage:
  allow_failure: false
  artifacts:
    name: plugin-coverage
    paths:
    - coverage/
  coverage: '/^Statements *: (\d+\.\d+%)/'
  only:
  - master
  - development
  script:
  - npm install --save-dev
  - node node_modules/.bin/istanbul cover ./tests/perform-tests.js coverage
  stage: test
documents:
  allow_failure: false
  artifacts:
    name: plugin-documentation
    paths:
    - docs/
  script:
  - npm install --save-dev
  - node node_modules/.bin/jsdoc -c ./.jsdoc.conf.json
  stage: build
image: node:latest
pages:
  artifacts:
    expire_in: 30 days
    paths:
    - public
  dependencies:
  - documents
  - coverage
  only:
  - master
  script:
  - mv docs public/
  - mv coverage/lcov-report/ public/coverage
  stage: deploy
stages:
- build
- test
- deploy
test:
  allow_failure: false
  except:
  - master
  script:
  - npm install --save-dev
  - node ./tests/perform-tests.js
  stage: test
