Darwin GHC 8107:
  script:
  - nix build -L .#ghc8107 --system x86_64-darwin
  stage: build
Darwin GHC 865:
  script:
  - nix build -L .#ghc865 --system x86_64-darwin
  stage: build
Darwin GHC 884:
  script:
  - nix build -L .#ghc884 --system x86_64-darwin
  stage: build
Darwin GHC 901:
  script:
  - nix build -L .#ghc901 --system x86_64-darwin
  stage: build
Linux GHC 8107:
  script:
  - nix build -L .#ghc8107 --system x86_64-linux
  stage: build
Linux GHC 865:
  script:
  - nix build -L .#ghc865 --system x86_64-linux
  stage: build
Linux GHC 884:
  script:
  - nix build -L .#ghc884 --system x86_64-linux
  stage: build
Linux GHC 901:
  script:
  - nix build -L .#ghc901 --system x86_64-linux
  stage: build
image: nixos/nix
stages:
- build
