build-branch:
  before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  - docker run --rm --privileged multiarch/qemu-user-static:register || true
  except:
  - devel
  - master
  - rc
  - tags
  script:
  - docker pull $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG || true
  - docker build -f Dockerfile ${ENV64:+--build-arg ENV64="$ENV64"} --cache-from $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG
    --tag $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA --tag $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG
    .
  - test -n "$CI_BUILD_TAG" && docker tag $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    $CONTAINER_IMAGE:$CI_BUILD_TAG || true
  - docker push $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  - docker push $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG
  - test -n "$CI_BUILD_TAG" && docker push $CONTAINER_IMAGE:$CI_BUILD_TAG || true
  stage: build
build-devel:
  before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  - docker run --rm --privileged multiarch/qemu-user-static:register || true
  only:
  - devel
  script:
  - docker pull $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG || true
  - docker build -f Dockerfile ${ENV64_devel:+--build-arg ENV64="$ENV64_devel"} --cache-from
    $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG --tag $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    --tag $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG .
  - test -n "$CI_BUILD_TAG" && docker tag $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    $CONTAINER_IMAGE:$CI_BUILD_TAG || true
  - docker push $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  - docker push $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG
  - test -n "$CI_BUILD_TAG" && docker push $CONTAINER_IMAGE:$CI_BUILD_TAG || true
  stage: build
build-local:
  before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  - docker run --rm --privileged multiarch/qemu-user-static:register || true
  only:
  - tags
  script:
  - docker pull $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG || true
  - docker build -f Dockerfile ${ENV64_local:+--build-arg ENV64="$ENV64_local"} --build-arg=NS=local
    --cache-from $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG --tag $CONTAINER_IMAGE:local
    .
  - docker push $CONTAINER_IMAGE:local
  stage: build
build-master:
  before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  - docker run --rm --privileged multiarch/qemu-user-static:register || true
  only:
  - master
  script:
  - docker pull $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG || true
  - docker build -f Dockerfile ${ENV64_prod:+--build-arg ENV64="$ENV64_prod"} --build-arg
    NS=www-prod --cache-from $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG --tag $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    --tag $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG .
  - test -n "$CI_BUILD_TAG" && docker tag $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    $CONTAINER_IMAGE:$CI_BUILD_TAG || true
  - docker push $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  - docker push $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG
  - test -n "$CI_BUILD_TAG" && docker push $CONTAINER_IMAGE:$CI_BUILD_TAG || true
  stage: build
build-rc:
  before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  - docker run --rm --privileged multiarch/qemu-user-static:register || true
  only:
  - rc
  script:
  - docker pull $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG || true
  - docker build -f Dockerfile ${ENV64_prod:+--build-arg ENV64="$ENV64_prod"} --build-arg
    NS=www-prod --cache-from $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG --tag $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    --tag $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG .
  - test -n "$CI_BUILD_TAG" && docker tag $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    $CONTAINER_IMAGE:$CI_BUILD_TAG || true
  - docker push $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  - docker push $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG
  - test -n "$CI_BUILD_TAG" && docker push $CONTAINER_IMAGE:$CI_BUILD_TAG || true
  stage: build
build-release-branch:
  before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  - docker run --rm --privileged multiarch/qemu-user-static:register || true
  only:
  - /^[0-9]*-release$/
  script:
  - docker pull $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG || true
  - docker build -f Dockerfile ${ENV64_prod:+--build-arg ENV64="$ENV64_prod"} --cache-from
    $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG --tag $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    --tag $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG .
  - docker push $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  - docker push $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG
  stage: build
build-standalone:
  before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  - docker run --rm --privileged multiarch/qemu-user-static:register || true
  only:
  - tags
  script:
  - docker pull $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG || true
  - docker build -f Dockerfile ${ENV64_standalone:+--build-arg ENV64="$ENV64_standalone"}
    --build-arg=NS=standalone --cache-from $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG --tag
    $CONTAINER_IMAGE:standalone .
  - docker push $CONTAINER_IMAGE:standalone
  stage: build
build-tag:
  before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  - docker run --rm --privileged multiarch/qemu-user-static:register || true
  only:
  - tags
  script:
  - docker pull $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG || true
  - docker build -f Dockerfile ${ENV64_prod:+--build-arg ENV64="$ENV64_prod"} --build-arg
    NS=www-prod --cache-from $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG --tag $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    --tag $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG .
  - test -n "$CI_BUILD_TAG" && docker tag $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    $CONTAINER_IMAGE:$CI_BUILD_TAG || true
  - docker push $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  - docker push $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG
  - test -n "$CI_BUILD_TAG" && docker push $CONTAINER_IMAGE:$CI_BUILD_TAG || true
  stage: build
deploy-devel:
  image: alpine:3.7
  only:
  - master
  script:
  - apk update  && apk add --no-cache curl
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
  - mkdir -p $HOME/.kube
  - echo -n $KUBE_CONFIG_DEV | base64 -d > $HOME/.kube/config
  - kubectl set image deploy/pv-pantahub-www pantahub-www=$CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  stage: deploy
deploy-prod:
  image: alpine:3.7
  only:
  - tags
  script:
  - apk update  && apk add --no-cache curl
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
  - mkdir -p $HOME/.kube
  - echo -n $KUBE_CONFIG_PROD | base64 -d > $HOME/.kube/config
  - kubectl set image deploy/pv-prod-pantahub-www pantahub-www=$CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  stage: deploy
image: docker:27.3.1-cli
services:
- alias: docker
  name: docker:27.3.1-dind
stages:
- build
- deploy
variables:
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: recursive
