container-image:
  before_script:
  - apk add --no-cache docker-cli-buildx
  image: docker:24.0.7-alpine3.19
  only:
  - web
  script:
  - docker buildx build --file=Dockerfile --tag=dev --target=dev .
  - docker buildx build --file=Dockerfile --tag=run --target=run .
  - "if [ -z \"${DOCKER_USERNAME}\" ] || [ -z \"${DOCKER_SECRET}\" ] || [ -z \"${DOCKER_USER}\"\
    \ ] || [ -z \"${DOCKER_PASSWORD}\" ]; then\n  echo \"Error: Una o m\xE1s variables\
    \ necesarias no est\xE1n definidas.\"\n  exit 1\nfi\n\nif [ -z \"$(cat .omnileads_version)\"\
    \ ]; then\n  echo \"Error: El archivo .omnileads_version no existe o est\xE1 vac\xED\
    o.\"\n  exit 1\nfi\n\n# If IMAGE_VERSION is empty, calculate default\nif [ -z\
    \ \"${IMAGE_VERSION}\" ]; then\n  IMAGE_VERSION=\"$(date +%Y%m%d)-${CI_COMMIT_SHORT_SHA}\"\
    \nfi\n\nif [[ \"${CI_COMMIT_BRANCH}\" == \"master\" ]]; then\n  echo \"${DOCKER_SECRET}\"\
    \ | docker login --username \"${DOCKER_USERNAME}\" --password-stdin\n  docker\
    \ tag run omnileads/omlapp:$IMAGE_VERSION\n  docker push docker.io/omnileads/omlapp:$IMAGE_VERSION\n\
    else\n  echo \"${DOCKER_PASSWORD}\" | docker login --username \"${DOCKER_USER}\"\
    \ --password-stdin\n  docker tag run freetechsolutions/omlapp:$IMAGE_VERSION\n\
    \  docker push docker.io/freetechsolutions/omlapp:$IMAGE_VERSION\nfi"
  services:
  - docker:24.0.7-dind-alpine3.19
  stage: build
stages:
- test
- build
test:
  before_script:
  - mkdir -p /opt/omnileads/ominicontacto/
  - mkdir -p /opt/omnileads/static
  - mkdir -p /opt/omnileads/media_root
  - rm "${CI_PROJECT_DIR}"/omnileads_ui/.eslintrc.js
  image: freetechsolutions/python-flake8:250213.01
  rules:
  - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"
  - if: $RUN_TEST == "true"
  script:
  - bash check-js.sh
  - flake8
  - python manage.py test --failfast
  - python manage.py compilemessages
  services:
  - alias: plpython
    name: freetechsolutions/omlpgsql:develop
  - redis
  stage: test
  variables:
    DATABASE_URL: postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB
    DJANGO_SETTINGS_MODULE: ominicontacto.settings.gitlab
    POSTGRES_DB: omnileads
    POSTGRES_PASSWORD: omnileadsrw
    POSTGRES_USER: omnileads
variables:
  IMAGE_VERSION: ''
