.composer_cache:
  cache: &id002
    paths:
    - vendor/
.composer_install:
  before_script: &id001
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install --prefer-dist --classmap-authoritative --no-interaction
    --no-progress
.composer_test:
  script: &id003
  - php composer.phar test
github:
  before_script:
  - apk add --update --no-cache bash git openssh
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - ssh-keyscan -H 'github.com' >> ~/.ssh/known_hosts
  - ssh-keyscan github.com | sort -u - ~/.ssh/known_hosts -o ~/.ssh/known_hosts
  - bash -c "ssh-add <(echo '$SSH_GITHUB_GITLAB')"
  image: alpine:latest
  script:
  - git push --mirror git@github.com:ThePixelDeveloper/SitemapBundle.git
  stage: mirror
php 7.0:
  before_script: *id001
  cache: *id002
  image: php:7.0-alpine
  script: *id003
  stage: test
php 7.1:
  before_script: *id001
  cache: *id002
  image: php:7.1-alpine
  script: *id003
  stage: test
php 7.2:
  before_script: *id001
  cache: *id002
  image: php:7.2-rc-alpine
  script: *id003
  stage: test
stages:
- mirror
- test
