Digital Ocean:
  only:
  - branches
  script:
  - /usr/local/bin/dep/deployer.phar deploy digital-ocean --branch="$CI_COMMIT_REF_NAME"
  stage: Deploy
  tags:
  - deploy
  when: manual
Google Cloud:
  only:
  - branches
  script:
  - /usr/local/bin/dep/deployer.phar deploy google-cloud-platform --branch="$CI_COMMIT_REF_NAME"
  stage: Deploy
  tags:
  - deploy
  when: manual
Tag All:
  only:
  - tags
  script:
  - /usr/local/bin/dep/deployer.phar deploy all --tag="$CI_COMMIT_TAG"
  stage: Deploy
  tags:
  - deploy
  when: manual
before_script:
- cd /home/gitlab-runner/deploy
- git fetch origin && git checkout origin/$CI_COMMIT_REF_NAME&& git pull origin $CI_COMMIT_REF_NAME
stages:
- Deploy
