cache:
  paths:
  - .m2/repository
code_quality:
  artifacts:
    expire_in: 2 week
    expose_as: Code Quality Report
    paths:
    - gl-code-quality-report.json
  stage: test
code_quality_html:
  artifacts:
    paths:
    - gl-code-quality-report.html
  extends: code_quality
  variables:
    REPORT_FORMAT: html
image: docker:latest
include:
- template: Code-Quality.gitlab-ci.yml
- template: Dependency-Scanning.gitlab-ci.yml
maven-build:
  artifacts:
    expire_in: 2 week
    paths:
    - target/*.jar
    - target/generate*/**
  before_script:
  - apt update
  - apt install -y eatmydata
  - eatmydata apt install -y openjdk-17-jdk
  - eatmydata apt install -y openjdk-17-jre
  - eatmydata apt install -y maven
  - eatmydata java -version
  - eatmydata mvn -v
  image: debian:bullseye
  script:
  - eatmydata mvn package -B
  stage: build
noark5tester-inoutin:
  allow_failure: false
  artifacts:
    expire_in: 2 week
    paths:
    - nikita-run.log
    - noark5-tester/json-dump-*/*
    - noark5-tester/uttrekk-*/*
    - noark5-tester/nikita-*-validation-report.txt
  before_script:
  - apt update
  - apt install -y eatmydata
  - eatmydata apt install -y curl wget iptables apt libdevmapper-dev systemctl jq
  - eatmydata apt install -y apt-transport-https gnupg lsb-release
  - eatmydata apt install -y openjdk-17-jre
  - eatmydata apt install -y openjdk-17-jdk
  - scripts/keycloak-setup-start.sh &
  - "until eatmydata curl --output /dev/null --silent --head --fail http://localhost:8080/;\
    \ do\n  sleep 2\ndone\ncurl --output /dev/null --silent --head --fail http://localhost:8080/\n"
  - eatmydata apt install -y maven
  - eatmydata apt install -y git curl python3 unoconv python3-tz python3-six python3-dateutil
    python3-stdnum python3-lxml libxml2-utils
  - eatmydata apt install -y tesseract-ocr-nor
  - eatmydata git clone https://codeberg.org/noark/noark-extraction-validator
  - eatmydata git clone https://codeberg.org/noark/noark5-tester
  image: debian:bullseye
  script:
  - eatmydata scripts/run-inoutin-test
  stage: use
  variables:
    baseurl: http://localhost:8092/noark5v5/
noark5tester-runtest:
  allow_failure: false
  artifacts:
    expire_in: 2 week
    paths:
    - nikita-run.log
  before_script:
  - apt update
  - apt install -y eatmydata
  - eatmydata apt install -y curl wget iptables apt libdevmapper-dev systemctl jq
  - eatmydata apt install -y apt-transport-https gnupg lsb-release
  - eatmydata apt install -y openjdk-17-jre
  - eatmydata apt install -y openjdk-17-jdk
  - scripts/keycloak-setup-start.sh &
  - "until eatmydata curl --output /dev/null --silent --head --fail http://localhost:8080/;\
    \ do\n  sleep 2\ndone\ncurl --output /dev/null --silent --head --fail http://localhost:8080/\n"
  - eatmydata apt install -y maven
  - eatmydata apt install -y git curl python3 unoconv python3-tz
  - eatmydata apt install -y tesseract-ocr-nor
  - eatmydata git clone https://codeberg.org/noark/noark5-tester
  image: debian:bullseye
  script:
  - eatmydata scripts/run-runtest
  stage: test
  variables:
    admin_password: admin
    admin_username: admin
    baseurl: http://localhost:8092/noark5v5/
    client_name: nikita-client
    password: password
    realm_name: recordkeeping
    role_name: RECORDS_MANAGER
    username: admin@example.com
stages:
- build
- test
- use
- deploy
variables:
  GIT_DEPTH: '0'
  MAVEN_OPTS: -Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
    -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true
