.verify:
  except: &id001
  - master
  script: &id002
  - mvn $MAVEN_CLI_OPTS verify
  stage: test
build_docker_image:
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
    - target
    policy: pull
  image: docker:git
  only:
  - master
  script:
  - ls -la
  - docker login -u $CI_DOCKER_U -p $CI_DOCKER_PW registry.gitlab.com
  - docker build -t registry.gitlab.com/adrian.kozlowski/ircbot:$CI_COMMIT_REF_NAME
    .
  - docker push registry.gitlab.com/adrian.kozlowski/ircbot:$CI_COMMIT_REF_NAME
  services:
  - docker:dind
  stage: release
cache:
  paths:
  - .m2/repository/
  - target/
deploy:
  image: maven:3.6.3-jdk-11-openj9
  only:
  - master
  script:
  - mvn $MAVEN_CLI_OPTS deploy
  stage: release
stages:
- test
- build
- release
- deploy
validate:
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
    - target
    policy: push
  image: maven:3.6.3-jdk-11-openj9
  script:
  - mvn $MAVEN_CLI_OPTS install
  stage: build
variables:
  MAVEN_CLI_OPTS: -s .m2/settings.xml --batch-mode --errors --fail-at-end --show-version
    -DinstallAtEnd=true -DdeployAtEnd=true
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
    -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true
verify:jdk8:
  except: *id001
  image: maven:3.6.3-jdk-11-openj9
  script: *id002
  stage: test
