deploy-ke-heroku:
  image: openjdk:8-jdk
  script:
  - apt-get update
  - apt-get install wget -y
  - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  - heroku plugins:install heroku-cli-deploy
  - heroku deploy:jar target/*.jar --app $HEROKU_APP_NAME
  stage: deploy
  variables:
    HEROKU_API_KEY: $HEROKU_API_KEY
deploy-ke-vps:
  image: ubuntu:latest
  script:
  - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && ssh-keyscan -H "$VPS_HOST" >> ~/.ssh/known_hosts'
  - scp target/*.jar ubuntu@$VPS_HOST:/var/lib/catalogapp/
  - ssh ubuntu@$VPS_HOST sudo service catalogapp restart
  stage: deploy
melakukan-build-dan-package:
  artifacts:
    paths:
    - target/*.jar
  image: maven:3-jdk-8
  script:
  - mvn clean package -DskipTests
  stage: build
stages:
- build
- deploy
