import base64
import time
import httpx
from dataclasses import dataclass
from urllib.parse import urlparse


@dataclass
class PublishResult:
    """Result of publishing a YAML file to a remote repository."""

    success: bool
    message: str
    url: str | None = None  # link to the committed file or PR

_RETRYABLE_STATUS_CODES = {500, 502, 503, 504}
_MAX_RETRIES = 3
_BACKOFF_BASE = 2  # seconds
def _request_with_retry(method: str, url: str, **kwargs) -> httpx.Response:

    """Make an HTTP request with automatic retry on transient server errors."""

    last_exc: httpx.HTTPStatusError | None = None
    for attempt in range(_MAX_RETRIES + 1):
        resp = httpx.request(method, url, **kwargs)
        if resp.status_code not in _RETRYABLE_STATUS_CODES:
            resp.raise_for_status()
            return resp
        # Retryable error
        if attempt < _MAX_RETRIES:
            wait = _BACKOFF_BASE ** attempt  # 1s, 2s, 4s
            time.sleep(wait)
        else:
            resp.raise_for_status()  # raise on final attempt
    # Should never reach here, but just in case
    raise httpx.HTTPError(f"Request failed after {_MAX_RETRIES + 1} attempts")



def publish_to_repo(
    yaml_content: str,
    repo_url: str,
    platform: str,
    token: str,
    file_path: str | None = None,
    branch: str = "main",
    commit_message: str | None = None,
    create_pr: bool = False,
    pr_branch: str = "yaml-wizard/ci-pipeline",
) -> PublishResult:
    """Publish a YAML file to a GitHub or GitLab repository.

    Can either commit directly to a branch or create a pull/merge request.
    """
    platform = platform.lower()
    if platform == "github":
        return _publish_github(
            yaml_content, repo_url, token, file_path, branch,
            commit_message, create_pr, pr_branch,
        )
    elif platform == "gitlab":
        return _publish_gitlab(
            yaml_content, repo_url, token, file_path, branch,
            commit_message, create_pr, pr_branch,
        )
    else:
        return PublishResult(success=False, message=f"Unknown platform: {platform}")




# ── GITHUB ──────────────────────────────────────────────────────────────────


def _publish_github(
    yaml_content: str,
    repo_url: str,
    token: str,
    file_path: str | None,
    branch: str,
    commit_message: str | None,
    create_pr: bool,
    pr_branch: str,) -> PublishResult:
    

    """Publish YAML to a GitHub repository via the Contents API."""
    """directly to a branch or via pull request"""


    owner, repo = _parse_github_repo(repo_url)
    api_base = "https://api.github.com"
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    if file_path is None:
        file_path = ".github/workflows/ci.yml"

    if commit_message is None:
        commit_message = f"ci: add {file_path} via YAML Wizard"

    target_branch = pr_branch if create_pr else branch

    try:
        # If creating a PR, first create the branch from the base
        if create_pr:
            _github_create_branch(api_base, headers, owner, repo, branch, pr_branch)

        # Check if file already exists (to get its SHA for updates)
        existing_sha = _github_get_file_sha(
            api_base, headers, owner, repo, file_path, target_branch,
        )

        # Create or update the file
        content_b64 = base64.b64encode(yaml_content.encode()).decode()
        payload: dict = {
            "message": commit_message,
            "content": content_b64,
            "branch": target_branch,
        }
        if existing_sha:
            payload["sha"] = existing_sha

        resp = _request_with_retry(
            "PUT",
            f"{api_base}/repos/{owner}/{repo}/contents/{file_path}",
            json=payload,
            headers=headers,
            timeout=30.0,
        )
        file_url = resp.json().get("content", {}).get("html_url", "")

        # Create PR if requested
        if create_pr:
            pr_result = _github_create_pr(
                api_base, headers, owner, repo,
                head=pr_branch, base=branch,
                title=f"ci: add CI/CD pipeline via YAML Wizard",
                body=(
                    f"This PR adds a CI/CD pipeline generated by YAML Wizard.\n\n"
                    f"**File:** `{file_path}`\n\n"
                    f"Please review the workflow before merging."
                ),
            )
            return PublishResult(
                success=True,
                message=f"Pull request created: {pr_result}",
                url=pr_result,
            )

        return PublishResult(
            success=True,
            message=f"File committed to {target_branch}: {file_path}",
            url=file_url,
        )

    except httpx.HTTPStatusError as e:
        error_body = e.response.text
        if e.response.status_code == 401:
            return PublishResult(success=False, message="Authentication failed — check your token")
        elif e.response.status_code == 403:
            return PublishResult(success=False, message="Permission denied — token may lack 'repo' scope")
        elif e.response.status_code == 404:
            return PublishResult(success=False, message=f"Repository not found: {owner}/{repo}")
        elif e.response.status_code == 409:
            return PublishResult(success=False, message=f"Conflict — file may have been updated. Try again. Details: {error_body}")
        elif e.response.status_code == 422:
            return PublishResult(success=False, message=f"Validation error: {error_body}")
        elif e.response.status_code == 500:
            return PublishResult(success=False, message=f"GitHub server error (500) — retried {_MAX_RETRIES} times. Details: {error_body}")
        elif e.response.status_code in (502, 503, 504):
            return PublishResult(success=False, message=f"GitHub temporarily unavailable ({e.response.status_code}) — retried {_MAX_RETRIES} times, try again later")
        return PublishResult(success=False, message=f"GitHub API error (HTTP {e.response.status_code}): {error_body}")
    except httpx.HTTPError as e:
        # Extract response body if available
        detail = ""
        if isinstance(e, httpx.HTTPStatusError):
            detail = f" — {e.response.status_code}: {e.response.text[:200]}"
        return PublishResult(success=False, message=f"Network error: {e}{detail}")
    except ValueError as e:
        return PublishResult(success=False, message=str(e))
    



def _parse_github_repo(repo_url: str) -> tuple[str, str]:

    """Extract owner/repo from a GitHub URL."""

    parsed = urlparse(repo_url)
    path = parsed.path.strip("/")
    if path.endswith(".git"):
        path = path[:-4]
    parts = path.split("/")
    if len(parts) >= 2:
        return parts[0], parts[1]
    raise ValueError(f"Cannot parse GitHub repo from URL: {repo_url}")



def _github_create_branch(
    api_base: str, headers: dict, owner: str, repo: str,
    source_branch: str, new_branch: str,) -> None:
    
    """Create a new branch from a source branch."""

    # Get the SHA of the source branch
    resp = httpx.get(
        f"{api_base}/repos/{owner}/{repo}/git/ref/heads/{source_branch}",
        headers=headers,
        timeout=15.0,
    )
    resp.raise_for_status()
    sha = resp.json()["object"]["sha"]

    # Create the new branch
    resp = _request_with_retry(
        "POST",
        f"{api_base}/repos/{owner}/{repo}/git/refs",
        json={"ref": f"refs/heads/{new_branch}", "sha": sha},
        headers=headers,
        timeout=15.0,
    )
    # 422 = branch already exists, which is fine
    if resp.status_code not in (201, 422):
        resp.raise_for_status()


def _github_get_file_sha(
    api_base: str, headers: dict, owner: str, repo: str, path: str, branch: str,) -> str | None:

    """Get the SHA of an existing file (needed for updates)."""

    try:
        resp = httpx.get(
            f"{api_base}/repos/{owner}/{repo}/contents/{path}",
            params={"ref": branch},
            headers=headers,
            timeout=15.0,
        )
        if resp.status_code == 200:
            return resp.json().get("sha")
    except httpx.HTTPError:
        pass
    return None


def _github_create_pr(
    api_base: str, headers: dict, owner: str, repo: str,
    head: str, base: str, title: str, body: str,) -> str:

    """Create a pull request and return its URL."""

    resp = _request_with_retry(
        "POST",
        f"{api_base}/repos/{owner}/{repo}/pulls",
        json={"title": title, "body": body, "head": head, "base": base},
        headers=headers,
        timeout=15.0,
    )
    return resp.json().get("html_url", "")




# ── GITLAB ──────────────────────────────────────────────────────────────────


def _publish_gitlab(
    yaml_content: str,
    repo_url: str,
    token: str,
    file_path: str | None,
    branch: str,
    commit_message: str | None,
    create_pr: bool,
    pr_branch: str,) -> PublishResult:

    """Publish YAML to a GitLab repository via the Repository Files API."""
    """directly to a branch or via merge request"""

    parsed = urlparse(repo_url)
    #https://gitlab.com/group/project
    #becomes: scheme: https + hostname: gitlab.com + path: /group/project
    #GitLab has multiple hosts so we extract it from repos, companies can have diff host than the public one
    gitlab_host = f"{parsed.scheme}://{parsed.hostname}"
    
    project_id = _parse_gitlab_project(repo_url)
    api_base = f"{gitlab_host}/api/v4" #GitLab API version 4 is the standard REST API base.
    headers = {"PRIVATE-TOKEN": token}

    if file_path is None:
        file_path = ".gitlab-ci.yml"

    if commit_message is None:
        commit_message = f"ci: add {file_path} via YAML Wizard"

    target_branch = pr_branch if create_pr else branch

    try:
        # Create branch if making merge request
        if create_pr:
            httpx.post(
                f"{api_base}/projects/{project_id}/repository/branches",
                params={"branch": pr_branch, "ref": branch},
                headers=headers,
                timeout=15.0,
            )

        # Check if file exists
        file_exists = _gitlab_file_exists(api_base, headers, project_id, file_path, target_branch)

        # Create or update file
        encoded_path = file_path.replace("/", "%2F")
        payload = {
            "branch": target_branch,
            "content": yaml_content,
            "commit_message": commit_message,
        }

        if file_exists:
            resp = httpx.put(
                f"{api_base}/projects/{project_id}/repository/files/{encoded_path}",
                json=payload,
                headers=headers,
                timeout=30.0,
            )
        else:
            resp = httpx.post(
                f"{api_base}/projects/{project_id}/repository/files/{encoded_path}",
                json=payload,
                headers=headers,
                timeout=30.0,
            )
        resp.raise_for_status()

        # Create merge request if requested
        if create_pr:
            mr_resp = httpx.post(
                f"{api_base}/projects/{project_id}/merge_requests",
                json={
                    "source_branch": pr_branch,
                    "target_branch": branch,
                    "title": "ci: add CI/CD pipeline via YAML Wizard",
                    "description": (
                        f"This MR adds a CI/CD pipeline generated by YAML Wizard.\n\n"
                        f"**File:** `{file_path}`\n\n"
                        f"Please review the pipeline before merging."
                    ),
                },
                headers=headers,
                timeout=15.0,
            )
            mr_resp.raise_for_status()
            mr_url = mr_resp.json().get("web_url", "")
            return PublishResult(
                success=True,
                message=f"Merge request created: {mr_url}",
                url=mr_url,
            )

        file_url = f"{gitlab_host}/{repo_url.split(gitlab_host)[-1].strip('/')}/blob/{target_branch}/{file_path}"
        return PublishResult(
            success=True,
            message=f"File committed to {target_branch}: {file_path}",
            url=file_url,
        )

    except httpx.HTTPStatusError as e:
        if e.response.status_code == 401:
            return PublishResult(success=False, message="Authentication failed — check your token")
        elif e.response.status_code == 403:
            return PublishResult(success=False, message="Permission denied — token may lack write access")
        return PublishResult(success=False, message=f"GitLab API error (HTTP {e.response.status_code}): {e.response.text}")
    except httpx.HTTPError as e:
        return PublishResult(success=False, message=f"Network error: {e}")
    except ValueError as e:
        return PublishResult(success=False, message=str(e))


def _gitlab_file_exists(api_base: str, headers: dict, project_id: str, path: str, branch: str,
                        ) -> bool:
    
    """Check if a file exists in the GitLab repository."""
    
    encoded_path = path.replace("/", "%2F")
    try:
        resp = httpx.get(
            f"{api_base}/projects/{project_id}/repository/files/{encoded_path}",
            params={"ref": branch},
            headers=headers,
            timeout=15.0,
        )
        return resp.status_code == 200
    except httpx.HTTPError:
        return False
    
def _parse_gitlab_project(repo_url: str) -> str:

    """Extract URL-encoded project path from a GitLab URL."""

    # GitLab API does NOT use raw paths like:group/project
    # It requires URL-encoded project path:(group%2Fproject)<- our output

    parsed = urlparse(repo_url)
    path = parsed.path.strip("/")
    if path.endswith(".git"):
        path = path[:-4]
    return path.replace("/", "%2F")